//===- kernel.cc ------------------------------------------------*- C++ -*-===//
//
// DENSE bf16 special-value sub sweep capture kernel (GENERATED by
// tools/gen_special_value_dense.py). Single op (aie::sub) repeated across a
// dense Inf/NaN operand matrix -- no pipeline-adjacency confound. Inputs and
// outputs are staged as raw bit patterns; the signature uses the real element
// type so the DMA moves bytes verbatim (NaN!=NaN-safe bit-exact compare).
//
//===----------------------------------------------------------------------===//

#include <stdint.h>

#include <aie_api/aie.hpp>

#define SWEEP_N 2048

using V = aie::vector<bfloat16, 32>;
__attribute__((noinline)) static V vop(V a, V b) { return aie::sub(a, b); }

extern "C" {

void sub_bf16(bfloat16 *restrict a, bfloat16 *restrict b,
              bfloat16 *restrict c) {
  event0();
  for (int i = 0; i < SWEEP_N; i += 32) {
    aie::vector<bfloat16, 32> va = aie::load_v<32>(a + i);
    aie::vector<bfloat16, 32> vb = aie::load_v<32>(b + i);
    aie::vector<bfloat16, 32> vc = vop(va, vb);
    aie::store_v(c + i, vc);
  }
  event1();
}

} // extern "C"
