//===- kernel.cc ------------------------------------------------*- C++ -*-===//
// Chained-state isolation probe (GENERATED by tools/gen_chain_state_probe.py).
// out = aie::add(aie::add(a, c), b). Operands a,c,b are concatenated regions of
// one input buffer (in[0..N)=a, in[N..2N)=c, in[2N..3N)=b) to fit the shim's
// two MM2S DMA channels.
//===----------------------------------------------------------------------===//

#include <stdint.h>
#include <aie_api/aie.hpp>

#define SWEEP_N 512

using V = aie::vector<bfloat16, 32>;
// Two SEPARATE noinline adds, matching the fuzzer chain's h3/h4 structure: the
// intermediate is narrowed to bf16 and re-widened across the call boundary
// (vconv.bf16.fp32 -> store/return -> vconv.fp32.bf16), rather than kept in an
// fp32 accumulator as a single inlined `add(add(...))` would.
__attribute__((noinline)) static V h_add(V a, V b) { return aie::add(a, b); }

extern "C" {

void chain_probe(bfloat16 *restrict in, bfloat16 *restrict o) {
  event0();
  bfloat16 *a = in;
  bfloat16 *c = in + SWEEP_N;
  bfloat16 *b = in + 2 * SWEEP_N;
  for (int i = 0; i < SWEEP_N; i += 32) {
    V va = aie::load_v<32>(a + i);
    V vc = aie::load_v<32>(c + i);
    V vb = aie::load_v<32>(b + i);
    V t = h_add(va, vc);
    aie::store_v(o + i, h_add(t, vb));
  }
  event1();
}

} // extern "C"
