//! Control packet response generation.
//!
//! When an OP_READ control packet is processed, the tile reads the requested
//! registers and generates a response packet. The response is serialized as
//! stream words and sent back through the TileCtrl master port, routed to
//! the requestor via packet switching.
//!
//! # Response Format
//!
//! The response consists of:
//! 1. A response header word (same format as the original control packet header,
//!    with the read address and response_id preserved)
//! 2. One or more data words containing the register values
//!
//! The response_id from the original read request is echoed back so the
//! requestor can match responses to requests.

use super::parser::{CtrlOpCode, build_header};

/// A response generated by processing an OP_READ control packet.
///
/// Contains the register values read from the tile, along with routing
/// information needed to deliver the response back to the requestor.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ControlPacketResponse {
    /// Register address from the original read request.
    pub address: u32,
    /// Register values read (one per beat requested).
    pub data: Vec<u32>,
    /// Response/stream ID from the original read request, echoed back
    /// for request-response matching.
    pub response_id: u8,
}

impl ControlPacketResponse {
    /// Create a response for a single-register read.
    pub fn single(address: u32, value: u32, response_id: u8) -> Self {
        Self {
            address,
            data: vec![value],
            response_id,
        }
    }

    /// Create a response for a multi-register read.
    pub fn multi(address: u32, values: Vec<u32>, response_id: u8) -> Self {
        Self {
            address,
            data: values,
            response_id,
        }
    }

    /// Number of register values in this response.
    pub fn beat_count(&self) -> u8 {
        self.data.len() as u8
    }

    /// Serialize the response into stream words for the TileCtrl slave port.
    ///
    /// Returns a vector of `(word, tlast)` pairs suitable for injection
    /// into a stream port. The first word is the response header, followed
    /// by the data words. The last word has `tlast=true`.
    ///
    /// This matches the format expected by `array.rs:drain_ctrl_responses()`.
    pub fn to_stream_words(&self) -> Vec<(u32, bool)> {
        let mut words = Vec::with_capacity(1 + self.data.len());

        // Response header: same format as control packet header.
        // Use OP_READ opcode, original address, beat count, and response_id.
        let header = build_header(
            self.address,
            self.beat_count(),
            CtrlOpCode::Read,
            self.response_id,
        );

        let total = 1 + self.data.len();
        words.push((header, total == 1));

        for (i, &value) in self.data.iter().enumerate() {
            let is_last = i == self.data.len() - 1;
            words.push((value, is_last));
        }

        words
    }

    /// Serialize to raw 32-bit words (without tlast metadata).
    ///
    /// Returns header followed by data words. Useful for tests and
    /// contexts where tlast tracking is not needed.
    pub fn to_raw_words(&self) -> Vec<u32> {
        let mut words = Vec::with_capacity(1 + self.data.len());
        let header = build_header(
            self.address,
            self.beat_count(),
            CtrlOpCode::Read,
            self.response_id,
        );
        words.push(header);
        words.extend_from_slice(&self.data);
        words
    }
}

impl std::fmt::Display for ControlPacketResponse {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "CtrlResp(addr=0x{:05X} resp_id={} data=[", self.address, self.response_id)?;
        for (i, val) in self.data.iter().enumerate() {
            if i > 0 { write!(f, ", ")?; }
            write!(f, "0x{:08X}", val)?;
        }
        write!(f, "])")
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::device::control_packets::parser::parse_header;

    #[test]
    fn single_register_response() {
        let resp = ControlPacketResponse::single(0x100, 0xDEAD_BEEF, 42);
        assert_eq!(resp.address, 0x100);
        assert_eq!(resp.data, vec![0xDEAD_BEEF]);
        assert_eq!(resp.response_id, 42);
        assert_eq!(resp.beat_count(), 1);
    }

    #[test]
    fn multi_register_response() {
        let resp = ControlPacketResponse::multi(0x200, vec![0x11, 0x22, 0x33], 7);
        assert_eq!(resp.beat_count(), 3);
        assert_eq!(resp.data.len(), 3);
    }

    #[test]
    fn to_stream_words_single_value() {
        let resp = ControlPacketResponse::single(0x100, 0xCAFE, 5);
        let words = resp.to_stream_words();

        // Header + 1 data word = 2 stream words
        assert_eq!(words.len(), 2);

        // First word is header, not last
        let (header, tlast0) = words[0];
        assert!(!tlast0);

        // Parse header to verify fields
        let fields = parse_header(header).unwrap();
        assert_eq!(fields.address, 0x100);
        assert_eq!(fields.opcode, super::super::parser::CtrlOpCode::Read);
        assert_eq!(fields.response_id, 5);
        assert_eq!(fields.beats, 1);

        // Second word is data, is last
        let (data, tlast1) = words[1];
        assert_eq!(data, 0xCAFE);
        assert!(tlast1);
    }

    #[test]
    fn to_stream_words_multiple_values() {
        let resp = ControlPacketResponse::multi(0x200, vec![0xAA, 0xBB, 0xCC], 10);
        let words = resp.to_stream_words();

        // Header + 3 data words = 4 stream words
        assert_eq!(words.len(), 4);

        // Only the last word has tlast=true
        assert!(!words[0].1); // header
        assert!(!words[1].1); // data[0]
        assert!(!words[2].1); // data[1]
        assert!(words[3].1);  // data[2]

        // Verify data values
        assert_eq!(words[1].0, 0xAA);
        assert_eq!(words[2].0, 0xBB);
        assert_eq!(words[3].0, 0xCC);
    }

    #[test]
    fn to_raw_words_matches_stream_words() {
        let resp = ControlPacketResponse::multi(0x300, vec![0x11, 0x22], 3);
        let raw = resp.to_raw_words();
        let stream: Vec<u32> = resp.to_stream_words().iter().map(|&(w, _)| w).collect();
        assert_eq!(raw, stream);
    }

    #[test]
    fn response_header_roundtrip() {
        // Build a response and verify the header can be re-parsed
        let resp = ControlPacketResponse::single(0x1A000, 0x42, 63);
        let raw = resp.to_raw_words();
        let fields = parse_header(raw[0]).unwrap();
        assert_eq!(fields.address, 0x1A000);
        assert_eq!(fields.beats, 1);
        assert_eq!(fields.response_id, 63);
        assert_eq!(fields.opcode, super::super::parser::CtrlOpCode::Read);
    }

    #[test]
    fn response_display() {
        let resp = ControlPacketResponse::single(0x100, 0xDEAD, 5);
        let s = format!("{}", resp);
        assert!(s.contains("0x00100"));
        assert!(s.contains("resp_id=5"));
        assert!(s.contains("0x0000DEAD"));
    }

    #[test]
    fn response_display_multi() {
        let resp = ControlPacketResponse::multi(0x200, vec![0xAA, 0xBB], 0);
        let s = format!("{}", resp);
        assert!(s.contains("0x000000AA"));
        assert!(s.contains("0x000000BB"));
    }

    #[test]
    fn empty_data_response_stream_words() {
        // Edge case: a response with no data (shouldn't happen in practice
        // but the code should handle it gracefully).
        let resp = ControlPacketResponse {
            address: 0x100,
            data: vec![],
            response_id: 0,
        };
        let words = resp.to_stream_words();
        // Just the header, which is also the last word
        assert_eq!(words.len(), 1);
        assert!(words[0].1); // tlast
    }
}
