//! DMA timing configuration.
//!
//! Provides cycle counts for each phase of a DMA transfer. The unified
//! channel FSM (`ChannelFsm`) uses these values directly as countdown
//! timers in its state variants -- no separate timing state machine needed.
//!
//! # Timing Model
//!
//! ```text
//! ┌──────────┐  ┌─────────┐  ┌──────────────┐  ┌─────────┐  ┌──────────┐
//! │ BD Setup │->│ Lock    │->│ Data         │->│ Lock    │->│ BD Chain │
//! │ (4 cyc)  │  │ Acquire │  │ Transfer     │  │ Release │  │ (2 cyc)  │
//! │          │  │ (1 cyc) │  │ (N/bandwidth)│  │ (1 cyc) │  │          │
//! └──────────┘  └─────────┘  └──────────────┘  └─────────┘  └──────────┘
//! ```

/// DMA timing configuration.
#[derive(Debug, Clone, Copy)]
pub struct DmaTimingConfig {
    /// Cycles to parse and setup a buffer descriptor
    pub bd_setup_cycles: u8,

    /// Cycles from channel start to first data movement
    pub channel_start_cycles: u8,

    /// Words (32-bit) transferred per cycle per channel
    pub words_per_cycle: u8,

    /// Memory access latency in cycles
    pub memory_latency_cycles: u8,

    /// Cycles to acquire a lock
    pub lock_acquire_cycles: u8,

    /// Cycles to release a lock
    pub lock_release_cycles: u8,

    /// Cycles between BD completion and next BD start
    pub bd_chain_cycles: u8,

    /// Extra pipeline latency for shim tile DDR access (NoC + DDR controller).
    /// Applied once per BD, between MemoryLatency and Transferring, only for
    /// shim tiles with host memory endpoints.
    pub host_memory_latency_cycles: u16,
}

impl Default for DmaTimingConfig {
    fn default() -> Self {
        // Default to AIE2 for test convenience.  Production callers
        // should use from_model() with the arch-appropriate model.
        Self::from_model(&xdna_archspec::aie2::dma::AIE2_DMA_MODEL)
    }
}

impl DmaTimingConfig {
    /// Create timing config from a DmaModel's per-arch constants.
    ///
    /// The constants come from the arch impl (AIE2: reads from
    /// `xdna_archspec::aie2::timing::DMA_*`).  This is a cold path --
    /// called once per DmaEngine construction.
    pub fn from_model(model: &'static dyn xdna_archspec::dma::DmaModel) -> Self {
        let m = model.timing_config();
        Self {
            bd_setup_cycles: m.bd_setup_cycles,
            channel_start_cycles: m.channel_start_cycles,
            words_per_cycle: m.words_per_cycle,
            memory_latency_cycles: m.memory_latency_cycles,
            lock_acquire_cycles: m.lock_acquire_cycles,
            lock_release_cycles: m.lock_release_cycles,
            bd_chain_cycles: m.bd_chain_cycles,
            host_memory_latency_cycles: m.host_memory_latency_cycles,
        }
    }

    /// Calculate total cycles for a transfer of given size.
    pub fn transfer_cycles(&self, bytes: u64, has_acquire_lock: bool, has_release_lock: bool) -> u64 {
        let words = (bytes + 3) / 4; // Round up to words
        let data_cycles = (words + self.words_per_cycle as u64 - 1) / self.words_per_cycle as u64;

        let mut total = self.bd_setup_cycles as u64
            + self.channel_start_cycles as u64
            + self.memory_latency_cycles as u64
            + data_cycles;

        if has_acquire_lock {
            total += self.lock_acquire_cycles as u64;
        }
        if has_release_lock {
            total += self.lock_release_cycles as u64;
        }

        total
    }

    /// Calculate cycles for BD chaining.
    pub fn chain_cycles(&self) -> u64 {
        self.bd_chain_cycles as u64 + self.bd_setup_cycles as u64
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_timing_config_default() {
        let config = DmaTimingConfig::default();
        assert_eq!(config.bd_setup_cycles, 4);
        // AIE2: 128-bit data bus, which is 4 x 32-bit words per cycle.
        // Source: xdna_archspec::aie2::timing::DMA_WORDS_PER_CYCLE = 4
        // (generated by crates/xdna-archspec/build.rs from AM025
        // xaiemlgbl_params.h's DATAMEMORY_WIDTH=128).
        assert_eq!(config.words_per_cycle, 4);
    }

    #[test]
    fn test_transfer_cycles_simple() {
        let config = DmaTimingConfig::default();

        // 16 bytes = 4 words at 4 words/cycle = 1 data cycle, no locks
        let cycles = config.transfer_cycles(16, false, false);
        // BD setup (4) + channel start (2) + memory latency (5) + data (1) = 12
        assert_eq!(cycles, 12);
    }

    #[test]
    fn test_transfer_cycles_with_locks() {
        let config = DmaTimingConfig::default();

        // 16 bytes = 4 words at 4 words/cycle = 1 data cycle, with locks
        let cycles = config.transfer_cycles(16, true, true);
        // BD setup (4) + channel start (2) + memory latency (5) + data (1) + acquire (1) + release (1) = 14
        assert_eq!(cycles, 14);
    }
}
