//! Stream switch model trait and data carrier.
//!
//! The AIE2 family (NPU1/NPU4/NPU5/NPU6) shares a single
//! stream-switch feature set. AIE1 (Versal) diverges on exactly one
//! flag (deterministic merge: absent on AIE1, present on AIE2) and
//! on topology data (port counts per tile kind). This module
//! exposes:
//!
//! - `StreamSwitchModel` (2-method trait): the one behavioral flag
//!   + one topology accessor.
//! - `StreamSwitchTopology` (data carrier): three `TileStreamPorts`
//!   sub-structs (compute, memtile, shim) + a `for_tile` accessor.
//! - `TileStreamPorts`: per-tile-kind master/slave port arrays and
//!   N/S range data.
//!
//! See `docs/arch/stream-switch-model.md` for the per-seam design
//! note explaining the shape-vs-values principle and alternatives.

use crate::types::TileKind;

/// Per-tile-kind stream-switch port layout.
///
/// Ports are u8 ordinals encoded per
/// `xdna_archspec::aie2::port_type::{CORE, FIFO, CTRL, north(n),
/// south(n), east(n), west(n), dma(n)}`. The underlying port arrays
/// are generated by build.rs from AM025 `Stream_Switch_*_Config`
/// register names.
///
/// Range fields are `(start, end)` inclusive. Shim tiles have
/// `(0, 0)` sentinels for `south_master` and `south_slave` because
/// shim's south-side ports are the external-NoC interface rather
/// than intra-array neighbors -- the `(0, 0)` sentinel models
/// "no intra-array south-facing ports," preserving the semantic
/// carried by the (now-deleted) runtime-side `PortLayout`
/// extension trait.
#[derive(Debug, Clone, Copy)]
pub struct TileStreamPorts {
    /// Ordered port-type ordinals for stream-switch master ports.
    pub master_ports: &'static [u8],
    /// Ordered port-type ordinals for stream-switch slave ports.
    pub slave_ports: &'static [u8],
    /// North-facing master port range `(start, end)` inclusive.
    pub north_master: (u8, u8),
    /// South-facing master port range `(start, end)` inclusive.
    /// `(0, 0)` sentinel if tile kind has no intra-array south.
    pub south_master: (u8, u8),
    /// North-facing slave port range `(start, end)` inclusive.
    pub north_slave: (u8, u8),
    /// South-facing slave port range `(start, end)` inclusive.
    /// `(0, 0)` sentinel if tile kind has no intra-array south.
    pub south_slave: (u8, u8),
}

/// Stream-switch topology data for a given architecture.
///
/// Aggregates per-tile-kind `TileStreamPorts` values. Use the
/// `for_tile` accessor to dispatch to the right sub-struct; the
/// public fields are also directly accessible for compile-time
/// destructuring (e.g., `topo.compute.master_ports`).
#[derive(Debug, Clone, Copy)]
pub struct StreamSwitchTopology {
    pub compute: TileStreamPorts,
    pub memtile: TileStreamPorts,
    pub shim: TileStreamPorts,
}

impl StreamSwitchTopology {
    /// Select the per-tile-kind port layout.
    ///
    /// `ShimNoc` and `ShimPl` both route to the shim fields (both
    /// are physical shim tiles; `PL` vs `NoC` is an interface
    /// variant, not a stream-switch variant).
    pub fn for_tile(&self, tile: TileKind) -> &TileStreamPorts {
        match tile {
            TileKind::Compute => &self.compute,
            TileKind::Mem => &self.memtile,
            TileKind::ShimNoc | TileKind::ShimPl => &self.shim,
        }
    }
}

/// Stream-switch model trait.
///
/// Two methods:
/// - `supports_deterministic_merge`: AIE1 = false, AIE2/AIE2P = true.
///   Per aie-rt `xaiegbl_reginit.c` / `xaiemlgbl_reginit.c`
///   `DetMergeFeature`.
/// - `topology`: returns the architecture's
///   `StreamSwitchTopology` as a `&'static` reference suitable for
///   caching via `OnceLock` on the runtime side.
///
/// Not on the trait:
/// - `supports_packet_routing`: invariant `true` across all AIE
///   generations per aie-rt shared `xaie_ss.c` (no arch-dispatch).
/// - Port validity checking (per-tile-kind which-slave-can-reach-which-master
///   rules on AIE2): programming-time concern, not emulated today.
/// - Packet slot count / arbiter count: invariant across arches
///   (4 / 8 respectively). Constants live on the carrier only if
///   they later diverge.
pub trait StreamSwitchModel: Send + Sync + core::fmt::Debug {
    fn supports_deterministic_merge(&self) -> bool;
    fn topology(&self) -> &'static StreamSwitchTopology;
}

#[cfg(test)]
mod tests {
    use super::*;

    // A minimal synthetic topology for testing the for_tile accessor.
    // Uses the by-value data-struct property: no trait impl needed to
    // exercise carrier semantics.
    static TEST_MASTER_PORTS: &[u8] = &[1, 2, 3];
    static TEST_SLAVE_PORTS: &[u8] = &[4, 5, 6, 7];

    static TEST_TOPO: StreamSwitchTopology = StreamSwitchTopology {
        compute: TileStreamPorts {
            master_ports: TEST_MASTER_PORTS,
            slave_ports: TEST_SLAVE_PORTS,
            north_master: (1, 2),
            south_master: (3, 4),
            north_slave: (5, 6),
            south_slave: (7, 8),
        },
        memtile: TileStreamPorts {
            master_ports: TEST_MASTER_PORTS,
            slave_ports: TEST_SLAVE_PORTS,
            north_master: (11, 12),
            south_master: (13, 14),
            north_slave: (15, 16),
            south_slave: (17, 18),
        },
        shim: TileStreamPorts {
            master_ports: TEST_MASTER_PORTS,
            slave_ports: TEST_SLAVE_PORTS,
            north_master: (21, 22),
            south_master: (0, 0),
            north_slave: (23, 24),
            south_slave: (0, 0),
        },
    };

    #[test]
    fn for_tile_compute_dispatches_correctly() {
        let ports = TEST_TOPO.for_tile(TileKind::Compute);
        assert_eq!(ports.north_master, (1, 2));
        assert_eq!(ports.south_slave, (7, 8));
    }

    #[test]
    fn for_tile_memtile_dispatches_correctly() {
        let ports = TEST_TOPO.for_tile(TileKind::Mem);
        assert_eq!(ports.north_master, (11, 12));
    }

    #[test]
    fn for_tile_shim_noc_and_pl_return_same() {
        let noc = TEST_TOPO.for_tile(TileKind::ShimNoc);
        let pl = TEST_TOPO.for_tile(TileKind::ShimPl);
        assert_eq!(noc.north_master, pl.north_master);
        assert_eq!(noc.south_master, (0, 0));
        assert_eq!(noc.south_slave, (0, 0));
    }

    // === Migrated from src/device/port_layout.rs ===
    //
    // These tests originally asserted properties of the runtime-side
    // PortLayout extension trait. With PortLayout deleted and its data
    // source (the archspec-generated port arrays) reachable via
    // AIE2_STREAM_SWITCH_TOPOLOGY, the assertions are restated against
    // the carrier.

    #[test]
    fn test_npu1_port_layouts_migrated() {
        use crate::aie2::stream_switch_model::AIE2_STREAM_SWITCH_TOPOLOGY;

        // Verify port counts match AM025 spec (restated from the original
        // `test_npu1_port_layouts` in src/device/port_layout.rs).
        assert_eq!(AIE2_STREAM_SWITCH_TOPOLOGY.shim.master_ports.len(), 22);
        assert_eq!(AIE2_STREAM_SWITCH_TOPOLOGY.shim.slave_ports.len(), 23);

        assert_eq!(AIE2_STREAM_SWITCH_TOPOLOGY.memtile.master_ports.len(), 17);
        assert_eq!(AIE2_STREAM_SWITCH_TOPOLOGY.memtile.slave_ports.len(), 18);

        assert_eq!(AIE2_STREAM_SWITCH_TOPOLOGY.compute.master_ports.len(), 23);
        assert_eq!(AIE2_STREAM_SWITCH_TOPOLOGY.compute.slave_ports.len(), 25);
    }

    #[test]
    fn test_npu1_port_ranges_migrated() {
        use crate::aie2::stream_switch::{compute, mem_tile, shim};
        use crate::aie2::stream_switch_model::AIE2_STREAM_SWITCH_TOPOLOGY;

        // Shim north masters: 12-17 (6 ports)
        assert_eq!(AIE2_STREAM_SWITCH_TOPOLOGY.shim.north_master, (12, 17));
        let (start, end) = AIE2_STREAM_SWITCH_TOPOLOGY.shim.north_master;
        assert_eq!(end - start + 1, 6);

        // MemTile south masters: 7-10 (4 ports)
        assert_eq!(AIE2_STREAM_SWITCH_TOPOLOGY.memtile.south_master, (7, 10));

        // MemTile north masters: 11-16 (6 ports)
        assert_eq!(AIE2_STREAM_SWITCH_TOPOLOGY.memtile.north_master, (11, 16));

        // Shim has no intra-array south (sentinel).
        assert_eq!(AIE2_STREAM_SWITCH_TOPOLOGY.shim.south_master, (0, 0));
        assert_eq!(AIE2_STREAM_SWITCH_TOPOLOGY.shim.south_slave, (0, 0));

        // E/W generated constants (not in carrier fields today, but the
        // drift-detection test above locks them. These direct-access
        // assertions are preserved here because they were in the
        // original test.)
        assert_eq!(compute::EAST_MASTER_START, 19);
        assert_eq!(compute::EAST_MASTER_END, 22);
        assert_eq!(compute::WEST_MASTER_START, 9);
        assert_eq!(compute::WEST_MASTER_END, 12);
        assert_eq!(shim::EAST_MASTER_START, 18);
        assert_eq!(shim::EAST_MASTER_END, 21);
        assert_eq!(shim::WEST_MASTER_START, 8);
        assert_eq!(shim::WEST_MASTER_END, 11);
        assert_eq!(shim::SOUTH_MASTER_START, 2);
        assert_eq!(shim::SOUTH_MASTER_END, 7);

        // Slave-side E/W/SOUTH constants (migrated from original test)
        assert_eq!(compute::EAST_SLAVE_START, 19);
        assert_eq!(compute::EAST_SLAVE_END, 22);
        assert_eq!(compute::WEST_SLAVE_START, 11);
        assert_eq!(compute::WEST_SLAVE_END, 14);
        assert_eq!(shim::EAST_SLAVE_START, 18);
        assert_eq!(shim::EAST_SLAVE_END, 21);
        assert_eq!(shim::WEST_SLAVE_START, 10);
        assert_eq!(shim::WEST_SLAVE_END, 13);
        assert_eq!(shim::SOUTH_SLAVE_START, 2);
        assert_eq!(shim::SOUTH_SLAVE_END, 9);

        // Arithmetic count checks (restated from original test)
        assert_eq!(compute::EAST_MASTER_END - compute::EAST_MASTER_START + 1, 4);
        assert_eq!(compute::WEST_MASTER_END - compute::WEST_MASTER_START + 1, 4);
        assert_eq!(shim::EAST_MASTER_END - shim::EAST_MASTER_START + 1, 4);
        assert_eq!(shim::WEST_MASTER_END - shim::WEST_MASTER_START + 1, 4);
        assert_eq!(shim::SOUTH_MASTER_END - shim::SOUTH_MASTER_START + 1, 6);

        // MemTile has no E/W ports (structural check: the symbols must
        // still exist on compute/shim but not mem_tile).
        assert_eq!(mem_tile::SOUTH_MASTER_START, 7);
        assert_eq!(mem_tile::NORTH_MASTER_START, 11);
    }

    #[test]
    fn test_shim_pl_same_as_shim_noc_migrated() {
        use crate::aie2::stream_switch_model::AIE2_STREAM_SWITCH_TOPOLOGY;

        let noc = AIE2_STREAM_SWITCH_TOPOLOGY.for_tile(TileKind::ShimNoc);
        let pl = AIE2_STREAM_SWITCH_TOPOLOGY.for_tile(TileKind::ShimPl);
        assert_eq!(noc.master_ports, pl.master_ports);
        assert_eq!(noc.slave_ports, pl.slave_ports);
        assert_eq!(noc.north_master, pl.north_master);
    }
}
