//===- kernel.cc ------------------------------------------------*- C++ -*-===//
//
// NaN/Inf-input sweep capture kernel (GENERATED by tools/gen_nan_inf_sweep.py).
// fp32 elementwise vector add (aie::add) over a 256-element operand-class
// matrix. Single op, repeated across the matrix -- no pipeline-adjacency
// confound. Inputs/outputs are staged as raw bit patterns (uint32_t); the
// kernel signature uses the real element type (float*) so the DMA moves
// bytes verbatim and the host compare is bit-exact (NaN!=NaN safe).
//
//===----------------------------------------------------------------------===//

#include <stdint.h>

#include <aie_api/aie.hpp>

#define SWEEP_N 256

extern "C" {

void add_fp32(float *restrict a, float *restrict b,
                     float *restrict c) {
  event0();
  for (int i = 0; i < SWEEP_N; i += 8) {
    aie::vector<float, 8> va = aie::load_v<8>(a + i);
    aie::vector<float, 8> vb = aie::load_v<8>(b + i);
  aie::vector<float, 8> vc = aie::add(va, vb);
    aie::store_v(c + i, vc);
  }
  event1();
}

} // extern "C"
