//===- kernel.cc ------------------------------------------------*- C++ -*-===//
//
// NaN/Inf-input sweep capture kernel (GENERATED by tools/gen_nan_inf_sweep.py).
// bf16 elementwise vector sub (aie::sub) over a 256-element operand-class
// matrix. Single op, repeated across the matrix -- no pipeline-adjacency
// confound. Inputs/outputs are staged as raw bit patterns (uint16_t); the
// kernel signature uses the real element type (bfloat16*) so the DMA moves
// bytes verbatim and the host compare is bit-exact (NaN!=NaN safe).
//
//===----------------------------------------------------------------------===//

#include <stdint.h>

#include <aie_api/aie.hpp>

#define SWEEP_N 256

using V = aie::vector<bfloat16, 32>;
__attribute__((noinline)) static V vop(V a, V b) { return aie::sub(a, b); }

extern "C" {

void sub_bf16(bfloat16 *restrict a, bfloat16 *restrict b,
                     bfloat16 *restrict c) {
  event0();
  for (int i = 0; i < SWEEP_N; i += 32) {
    aie::vector<bfloat16, 32> va = aie::load_v<32>(a + i);
    aie::vector<bfloat16, 32> vb = aie::load_v<32>(b + i);
  aie::vector<bfloat16, 32> vc = vop(va, vb);
    aie::store_v(c + i, vc);
  }
  event1();
}

} // extern "C"
