//===- test.cpp -------------------------------------------------*- C++ -*-===//
//
// Host harness for the NaN/Inf bf16 elementwise sub sweep (GENERATED by
// tools/gen_nan_inf_sweep.py). Stages the operand-class matrix as raw bit
// patterns, launches, and DUMPS per-lane {A_bits, B_bits, hw_out_bits} to
// out.txt for silicon capture. The baked EMU[] column is the CURRENT emulator
// expectation (host IEEE add/sub then raw bf16 truncate / plain fp32) -- it is
// NOT a golden; the run "PASSES" iff hw==emu, and a real silicon run is EXPECTED
// to diverge on special-operand lanes. The divergence is the finding.
//
//===----------------------------------------------------------------------===//

#include <algorithm>
#include <cstdint>
#include <cstring>
#include <fstream>
#include <iostream>
#include <vector>

#include "xrt/xrt_bo.h"
#include "xrt/xrt_device.h"
#include "xrt/xrt_kernel.h"

#include "test_utils.h"

static constexpr int N = 256;

static const uint16_t INA[256] = {
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 32768,
    32768, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    32769, 32769, 32769, 32769, 32769, 32769, 32769, 32769, 32769, 32769, 32769, 32769,
    32769, 32769, 32769, 32769, 14464, 14464, 14464, 14464, 14464, 14464, 14464, 14464,
    14464, 14464, 14464, 14464, 14464, 14464, 14464, 14464, 47232, 47232, 47232, 47232,
    47232, 47232, 47232, 47232, 47232, 47232, 47232, 47232, 47232, 47232, 47232, 47232,
    32512, 32512, 32512, 32512, 32512, 32512, 32512, 32512, 32512, 32512, 32512, 32512,
    32512, 32512, 32512, 32512, 65280, 65280, 65280, 65280, 65280, 65280, 65280, 65280,
    65280, 65280, 65280, 65280, 65280, 65280, 65280, 65280, 32640, 32640, 32640, 32640,
    32640, 32640, 32640, 32640, 32640, 32640, 32640, 32640, 32640, 32640, 32640, 32640,
    65408, 65408, 65408, 65408, 65408, 65408, 65408, 65408, 65408, 65408, 65408, 65408,
    65408, 65408, 65408, 65408, 32704, 32704, 32704, 32704, 32704, 32704, 32704, 32704,
    32704, 32704, 32704, 32704, 32704, 32704, 32704, 32704, 65472, 65472, 65472, 65472,
    65472, 65472, 65472, 65472, 65472, 65472, 65472, 65472, 65472, 65472, 65472, 65472,
    32672, 32672, 32672, 32672, 32672, 32672, 32672, 32672, 32672, 32672, 32672, 32672,
    32672, 32672, 32672, 32672, 65440, 65440, 65440, 65440, 65440, 65440, 65440, 65440,
    65440, 65440, 65440, 65440, 65440, 65440, 65440, 65440, 32725, 32725, 32725, 32725,
    32725, 32725, 32725, 32725, 32725, 32725, 32725, 32725, 32725, 32725, 32725, 32725,
    65493, 65493, 65493, 65493, 65493, 65493, 65493, 65493, 65493, 65493, 65493, 65493,
    65493, 65493, 65493, 65493,
};
static const uint16_t INB[256] = {
    0, 32768, 1, 32769, 14464, 47232, 32512, 65280, 32640, 65408, 32704, 65472,
    32672, 65440, 32725, 65493, 0, 32768, 1, 32769, 14464, 47232, 32512, 65280,
    32640, 65408, 32704, 65472, 32672, 65440, 32725, 65493, 0, 32768, 1, 32769,
    14464, 47232, 32512, 65280, 32640, 65408, 32704, 65472, 32672, 65440, 32725, 65493,
    0, 32768, 1, 32769, 14464, 47232, 32512, 65280, 32640, 65408, 32704, 65472,
    32672, 65440, 32725, 65493, 0, 32768, 1, 32769, 14464, 47232, 32512, 65280,
    32640, 65408, 32704, 65472, 32672, 65440, 32725, 65493, 0, 32768, 1, 32769,
    14464, 47232, 32512, 65280, 32640, 65408, 32704, 65472, 32672, 65440, 32725, 65493,
    0, 32768, 1, 32769, 14464, 47232, 32512, 65280, 32640, 65408, 32704, 65472,
    32672, 65440, 32725, 65493, 0, 32768, 1, 32769, 14464, 47232, 32512, 65280,
    32640, 65408, 32704, 65472, 32672, 65440, 32725, 65493, 0, 32768, 1, 32769,
    14464, 47232, 32512, 65280, 32640, 65408, 32704, 65472, 32672, 65440, 32725, 65493,
    0, 32768, 1, 32769, 14464, 47232, 32512, 65280, 32640, 65408, 32704, 65472,
    32672, 65440, 32725, 65493, 0, 32768, 1, 32769, 14464, 47232, 32512, 65280,
    32640, 65408, 32704, 65472, 32672, 65440, 32725, 65493, 0, 32768, 1, 32769,
    14464, 47232, 32512, 65280, 32640, 65408, 32704, 65472, 32672, 65440, 32725, 65493,
    0, 32768, 1, 32769, 14464, 47232, 32512, 65280, 32640, 65408, 32704, 65472,
    32672, 65440, 32725, 65493, 0, 32768, 1, 32769, 14464, 47232, 32512, 65280,
    32640, 65408, 32704, 65472, 32672, 65440, 32725, 65493, 0, 32768, 1, 32769,
    14464, 47232, 32512, 65280, 32640, 65408, 32704, 65472, 32672, 65440, 32725, 65493,
    0, 32768, 1, 32769, 14464, 47232, 32512, 65280, 32640, 65408, 32704, 65472,
    32672, 65440, 32725, 65493,
};
static const uint16_t EMU[256] = {
    0, 0, 32769, 1, 47232, 14464, 65280, 32512, 65408, 32640, 32704, 65472,
    32736, 65504, 32725, 65493, 32768, 0, 32769, 1, 47232, 14464, 65280, 32512,
    65408, 32640, 32704, 65472, 32736, 65504, 32725, 65493, 1, 1, 0, 2,
    47232, 14464, 65280, 32512, 65408, 32640, 32704, 65472, 32736, 65504, 32725, 65493,
    32769, 32769, 32770, 0, 47232, 14464, 65280, 32512, 65408, 32640, 32704, 65472,
    32736, 65504, 32725, 65493, 14464, 14464, 14464, 14464, 0, 14592, 65280, 32512,
    65408, 32640, 32704, 65472, 32736, 65504, 32725, 65493, 47232, 47232, 47232, 47232,
    47360, 0, 65280, 32512, 65408, 32640, 32704, 65472, 32736, 65504, 32725, 65493,
    32512, 32512, 32512, 32512, 32512, 32512, 0, 32640, 65408, 32640, 32704, 65472,
    32736, 65504, 32725, 65493, 65280, 65280, 65280, 65280, 65280, 65280, 65408, 0,
    65408, 32640, 32704, 65472, 32736, 65504, 32725, 65493, 32640, 32640, 32640, 32640,
    32640, 32640, 32640, 32640, 65472, 32640, 32704, 65472, 32736, 65504, 32725, 65493,
    65408, 65408, 65408, 65408, 65408, 65408, 65408, 65408, 65408, 65472, 32704, 65472,
    32736, 65504, 32725, 65493, 32704, 32704, 32704, 32704, 32704, 32704, 32704, 32704,
    32704, 32704, 32704, 32704, 32704, 32704, 32704, 32704, 65472, 65472, 65472, 65472,
    65472, 65472, 65472, 65472, 65472, 65472, 65472, 65472, 65472, 65472, 65472, 65472,
    32736, 32736, 32736, 32736, 32736, 32736, 32736, 32736, 32736, 32736, 32736, 32736,
    32736, 32736, 32736, 32736, 65504, 65504, 65504, 65504, 65504, 65504, 65504, 65504,
    65504, 65504, 65504, 65504, 65504, 65504, 65504, 65504, 32725, 32725, 32725, 32725,
    32725, 32725, 32725, 32725, 32725, 32725, 32725, 32725, 32725, 32725, 32725, 32725,
    65493, 65493, 65493, 65493, 65493, 65493, 65493, 65493, 65493, 65493, 65493, 65493,
    65493, 65493, 65493, 65493,
};

int main(int argc, const char *argv[]) {
  std::vector<uint32_t> instr_v = test_utils::load_instr_binary("insts.bin");

  unsigned int device_index = 0;
  auto device = xrt::device(device_index);

  std::string xclbin_name = "aie.xclbin";
  xrt::xclbin xclbin(xclbin_name);
  std::string Node = "MLIR_AIE";

  auto xkernels = xclbin.get_kernels();
  auto xkernel = *std::find_if(xkernels.begin(), xkernels.end(),
                               [Node](xrt::xclbin::kernel &k) {
                                 return k.get_name().rfind(Node, 0) == 0;
                               });
  auto kernelName = xkernel.get_name();

  device.register_xclbin(xclbin);
  xrt::hw_context context(device, xclbin.get_uuid());
  auto kernel = xrt::kernel(context, kernelName);

  auto bo_instr = xrt::bo(device, instr_v.size() * sizeof(int),
                          XCL_BO_FLAGS_CACHEABLE, kernel.group_id(1));
  auto bo_a = xrt::bo(device, N * sizeof(uint16_t), XRT_BO_FLAGS_HOST_ONLY, kernel.group_id(3));
  auto bo_b = xrt::bo(device, N * sizeof(uint16_t), XRT_BO_FLAGS_HOST_ONLY, kernel.group_id(4));
  auto bo_c = xrt::bo(device, N * sizeof(uint16_t), XRT_BO_FLAGS_HOST_ONLY, kernel.group_id(5));

  uint16_t *bufA = bo_a.map<uint16_t *>();
  uint16_t *bufB = bo_b.map<uint16_t *>();
  uint16_t *bufC = bo_c.map<uint16_t *>();

  std::memcpy(bufA, INA, N * sizeof(uint16_t));
  std::memcpy(bufB, INB, N * sizeof(uint16_t));
  std::memset(bufC, 0, N * sizeof(uint16_t));

  void *bufInstr = bo_instr.map<void *>();
  std::memcpy(bufInstr, instr_v.data(), instr_v.size() * sizeof(int));

  bo_instr.sync(XCL_BO_SYNC_BO_TO_DEVICE);
  bo_a.sync(XCL_BO_SYNC_BO_TO_DEVICE);
  bo_b.sync(XCL_BO_SYNC_BO_TO_DEVICE);
  bo_c.sync(XCL_BO_SYNC_BO_TO_DEVICE);

  unsigned int opcode = 3;
  auto run = kernel(opcode, bo_instr, instr_v.size(), bo_a, bo_b, bo_c);
  ert_cmd_state r = run.wait();
  if (r != ERT_CMD_STATE_COMPLETED) {
    std::cout << "Kernel did not complete. Status: " << r << "\n";
    return 1;
  }

  bo_c.sync(XCL_BO_SYNC_BO_FROM_DEVICE);

  // Per-lane silicon dump: A_bits B_bits hw_out_bits (decimal). This is the
  // ground-truth artifact -- one line per (A_class, B_class) pair.
  {
    std::ofstream dump("out.txt");
    for (int i = 0; i < N; i++)
      dump << (uint32_t)bufA[i] << " "
           << (uint32_t)bufB[i] << " "
           << (uint32_t)bufC[i] << "\n";
  }

  int diffs = 0;
  for (int i = 0; i < N; i++) {
    if (bufC[i] != EMU[i]) {
      if (diffs < 16)
        std::cout << "Diff [" << i << "]: a=0x" << std::hex << (uint32_t)bufA[i]
                  << " b=0x" << (uint32_t)bufB[i] << " hw=0x" << (uint32_t)bufC[i]
                  << " emu=0x" << (uint32_t)EMU[i] << std::dec << "\n";
      diffs++;
    }
  }

  std::cout << "\n" << diffs << " lane(s) diverge from current emulator (out of "
            << N << ").\n";
  if (!diffs) {
    std::cout << "\nPASS!\n\n";
    return 0;
  }
  // A nonzero diff count is the EXPECTED, INFORMATIVE outcome on real silicon.
  // out.txt holds the ground truth; the model update is read off from it.
  std::cout << "\n(divergence is expected on silicon; see out.txt)\n\n";
  return 1;
}
