//! NPU instruction parser and executor.
//!
//! This module handles the host-to-NPU communication protocol used by XRT.
//! The NPU instructions are generated by mlir-aie and sent to the NPU via
//! the XRT runtime. They configure shim DMA, patch addresses, and trigger
//! data transfers.
//!
//! # Instruction Format
//!
//! NPU instructions use an optimized binary format:
//! - 4-byte operation header (opcode byte + 3 padding bytes)
//! - Operation-specific payload (varies by opcode)
//!
//! # Opcodes
//!
//! - `WRITE32` (0): Write single 32-bit value to register
//! - `BLOCKWRITE` (1): Write block of 32-bit values
//! - `BLOCKSET` (2): Fill region with repeated value
//! - `MASKWRITE` (3): Write with mask (read-modify-write)
//! - `MASKPOLL` (4): Poll until masked value matches
//! - `CONFIG_SHIMDMA_BD` (5): Configure shim DMA buffer descriptor
//! - `CONFIG_SHIMDMA_DMABUF_BD` (6): Configure shim DMA with DMA buffer
//! - `DDR_PATCH` (129): Patch address with host buffer address

mod parser;
mod executor;

pub use parser::{NpuInstruction, NpuInstructionStream};
pub use executor::NpuExecutor;

/// NPU instruction opcodes.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum NpuOpcode {
    /// Write single 32-bit value to register.
    Write32 = 0,
    /// Write block of 32-bit values starting at address.
    BlockWrite = 1,
    /// Fill region with repeated 32-bit value.
    BlockSet = 2,
    /// Write with mask (read-modify-write).
    MaskWrite = 3,
    /// Poll until (reg & mask) == value.
    MaskPoll = 4,
    /// Configure shim DMA buffer descriptor.
    ConfigShimDmaBd = 5,
    /// Configure shim DMA with DMA buffer.
    ConfigShimDmaDmaBufBd = 6,
    /// Custom operation: Transaction Control Token (Sync/Wait).
    /// This is XAIE_IO_CUSTOM_OP_TCT = XAIE_IO_CUSTOM_OP_BEGIN = 128.
    Tct = 128,
    /// Custom operation: DDR address patch.
    DdrPatch = 129,
    /// Unknown opcode.
    Unknown = 255,
}

impl From<u8> for NpuOpcode {
    fn from(value: u8) -> Self {
        match value {
            0 => NpuOpcode::Write32,
            1 => NpuOpcode::BlockWrite,
            2 => NpuOpcode::BlockSet,
            3 => NpuOpcode::MaskWrite,
            4 => NpuOpcode::MaskPoll,
            5 => NpuOpcode::ConfigShimDmaBd,
            6 => NpuOpcode::ConfigShimDmaDmaBufBd,
            128 => NpuOpcode::Tct,
            129 => NpuOpcode::DdrPatch,
            _ => NpuOpcode::Unknown,
        }
    }
}
