//! LLVM decoder table bytecode interpreter.
//!
//! This module implements a Rust interpreter for the bytecode decision trees
//! generated by `llvm-tblgen -gen-disassembler`. These tables encode the
//! same disambiguation logic LLVM uses in its disassembler, resolving
//! ambiguous instruction encodings (like MOV vs VGE in the MV slot) via
//! definition order and operand validation rather than heuristics.
//!
//! The bytecode tables are extracted at build time (see `build_helpers/bytecode.rs`)
//! and embedded in `gen_tablegen.rs`. This module contains only the runtime
//! interpreter -- no parsing, no subprocess.
//!
//! # Bytecode Format
//!
//! The table is a flat `Vec<u8>` interpreted as a sequence of opcodes:
//!
//! | Opcode (byte value) | Name | Arguments |
//! |---------------------|------|-----------|
//! | 1 | ExtractField | uleb128(start), u8(len) |
//! | 2 | FilterValue | uleb128(val), u24_le(skip) |
//! | 3 | CheckField | uleb128(start), u8(len), uleb128(val), u24_le(skip) |
//! | 4 | CheckPredicate | uleb128(pidx), u24_le(skip) |
//! | 5 | Decode | uleb128(opcode), uleb128(decoder_idx) |
//! | 6 | TryDecode | uleb128(opcode), uleb128(decoder_idx), u24_le(skip) |
//! | 7 | SoftFail | uleb128(pos_mask), uleb128(neg_mask) |
//! | 8 | Fail | (none) |

use std::collections::HashMap;

/// LLVM decoder bytecode opcodes (from MCDecoderOps.h).
mod opc {
    pub const EXTRACT_FIELD: u8 = 1;
    pub const FILTER_VALUE: u8 = 2;
    pub const CHECK_FIELD: u8 = 3;
    pub const CHECK_PREDICATE: u8 = 4;
    pub const DECODE: u8 = 5;
    pub const TRY_DECODE: u8 = 6;
    pub const SOFT_FAIL: u8 = 7;
    pub const FAIL: u8 = 8;
}

/// A decoder table containing bytecode and opcode name mapping.
///
/// Contains the raw bytecode and a mapping from LLVM opcode IDs to
/// instruction definition names (e.g., 693 -> "MOV_mv_cg").
#[derive(Debug, Clone)]
pub struct DecoderTable {
    /// Raw bytecode from the DecoderTableXxx array.
    bytes: Vec<u8>,
    /// LLVM opcode ID -> instruction name.
    opcode_names: HashMap<u32, String>,
}

impl DecoderTable {
    /// Create a new decoder table from raw bytecode and opcode name mapping.
    pub fn new(bytes: Vec<u8>, opcode_names: HashMap<u32, String>) -> Self {
        Self { bytes, opcode_names }
    }

    /// Decode an instruction word using the LLVM bytecode decision tree.
    ///
    /// Returns the instruction name (e.g., "MOV_mv_cg") if a match is found,
    /// or None if the bytecode reaches OPC_Fail.
    pub fn decode(&self, insn_bits: u64) -> Option<&str> {
        let bytes = &self.bytes;
        let len = bytes.len();
        let mut ptr: usize = 0;
        let mut cur_field_value: u64 = 0;

        while ptr < len {
            let opcode = bytes[ptr];
            ptr += 1;

            match opcode {
                opc::EXTRACT_FIELD => {
                    let start = read_uleb128(bytes, &mut ptr);
                    let field_len = bytes[ptr] as u32;
                    ptr += 1;
                    cur_field_value = field_from_instruction(insn_bits, start, field_len);
                }

                opc::FILTER_VALUE => {
                    let val = read_uleb128(bytes, &mut ptr) as u64;
                    let num_to_skip = read_u24_le(bytes, &mut ptr);
                    if val != cur_field_value {
                        ptr += num_to_skip as usize;
                    }
                }

                opc::CHECK_FIELD => {
                    let start = read_uleb128(bytes, &mut ptr);
                    let field_len = bytes[ptr] as u32;
                    ptr += 1;
                    let field_value = field_from_instruction(insn_bits, start, field_len);
                    let expected = read_uleb128(bytes, &mut ptr) as u64;
                    let num_to_skip = read_u24_le(bytes, &mut ptr);
                    if expected != field_value {
                        ptr += num_to_skip as usize;
                    }
                }

                opc::CHECK_PREDICATE => {
                    let _pidx = read_uleb128(bytes, &mut ptr);
                    let _num_to_skip = read_u24_le(bytes, &mut ptr);
                }

                opc::DECODE => {
                    let opcode_id = read_uleb128(bytes, &mut ptr);
                    let _decoder_idx = read_uleb128(bytes, &mut ptr);
                    return self.opcode_names.get(&opcode_id).map(|s| s.as_str());
                }

                opc::TRY_DECODE => {
                    let opcode_id = read_uleb128(bytes, &mut ptr);
                    let _decoder_idx = read_uleb128(bytes, &mut ptr);
                    let num_to_skip = read_u24_le(bytes, &mut ptr);

                    if self.opcode_names.contains_key(&opcode_id) {
                        return self.opcode_names.get(&opcode_id).map(|s| s.as_str());
                    }
                    ptr += num_to_skip as usize;
                }

                opc::SOFT_FAIL => {
                    let _pos_mask = read_uleb128(bytes, &mut ptr);
                    let _neg_mask = read_uleb128(bytes, &mut ptr);
                }

                opc::FAIL => {
                    return None;
                }

                _ => {
                    log::warn!(
                        "Unknown decoder bytecode opcode {} at offset {}",
                        opcode,
                        ptr - 1
                    );
                    return None;
                }
            }
        }

        None
    }

    /// Get the number of bytes in the bytecode table.
    pub fn byte_count(&self) -> usize {
        self.bytes.len()
    }

    /// Get the number of opcode name entries.
    pub fn opcode_count(&self) -> usize {
        self.opcode_names.len()
    }
}

/// Extract a bit field from an instruction word.
#[inline]
fn field_from_instruction(insn: u64, start_bit: u32, num_bits: u32) -> u64 {
    if num_bits == 64 {
        insn
    } else {
        let mask = (1u64 << num_bits) - 1;
        (insn >> start_bit) & mask
    }
}

/// Read a ULEB128-encoded value from a byte slice, advancing the pointer.
#[inline]
fn read_uleb128(bytes: &[u8], ptr: &mut usize) -> u32 {
    let mut result: u32 = 0;
    let mut shift: u32 = 0;
    loop {
        let byte = bytes[*ptr];
        *ptr += 1;
        result |= ((byte & 0x7F) as u32) << shift;
        if byte & 0x80 == 0 {
            break;
        }
        shift += 7;
    }
    result
}

/// Read a 24-bit little-endian integer from a byte slice.
#[inline]
fn read_u24_le(bytes: &[u8], ptr: &mut usize) -> u32 {
    let b0 = bytes[*ptr] as u32;
    let b1 = bytes[*ptr + 1] as u32;
    let b2 = bytes[*ptr + 2] as u32;
    *ptr += 3;
    b0 | (b1 << 8) | (b2 << 16)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_uleb128() {
        let bytes = [0x00];
        let mut ptr = 0;
        assert_eq!(read_uleb128(&bytes, &mut ptr), 0);
        assert_eq!(ptr, 1);

        let bytes = [0x7F];
        ptr = 0;
        assert_eq!(read_uleb128(&bytes, &mut ptr), 127);

        let bytes = [0x80, 0x01];
        ptr = 0;
        assert_eq!(read_uleb128(&bytes, &mut ptr), 128);
        assert_eq!(ptr, 2);

        let bytes = [0xBC, 0x05];
        ptr = 0;
        assert_eq!(read_uleb128(&bytes, &mut ptr), 700);
    }

    #[test]
    fn test_u24_le() {
        let bytes = [0x04, 0x01, 0x00];
        let mut ptr = 0;
        assert_eq!(read_u24_le(&bytes, &mut ptr), 260);
        assert_eq!(ptr, 3);
    }

    #[test]
    fn test_field_from_instruction() {
        assert_eq!(field_from_instruction(0b101, 0, 3), 5);
        assert_eq!(field_from_instruction(0b11000, 3, 2), 3);
        assert_eq!(field_from_instruction(0b110, 0, 1), 0);
    }

    #[test]
    fn test_simple_decode() {
        let bytes = vec![
            opc::EXTRACT_FIELD, 0, 2,
            opc::FILTER_VALUE, 1, 4, 0, 0,
            opc::DECODE, 42, 0,
            opc::FAIL,
        ];

        let mut names = HashMap::new();
        names.insert(42, "TEST_INSTR".to_string());
        let table = DecoderTable::new(bytes, names);

        assert_eq!(table.decode(0b01), Some("TEST_INSTR"));
        assert_eq!(table.decode(0b00), None);
        assert_eq!(table.decode(0b10), None);
    }

    #[test]
    fn test_try_decode_fallthrough() {
        let bytes = vec![
            opc::TRY_DECODE, 42, 0, 0, 0, 0,
            opc::DECODE, 99, 0,
            opc::FAIL,
        ];

        let mut names = HashMap::new();
        names.insert(99, "FALLBACK".to_string());
        let table = DecoderTable::new(bytes, names);

        assert_eq!(table.decode(0), Some("FALLBACK"));
    }

    #[test]
    fn test_check_field() {
        let bytes = vec![
            opc::CHECK_FIELD, 4, 2, 3, 4, 0, 0,
            opc::DECODE, 10, 0,
            opc::FAIL,
        ];

        let mut names = HashMap::new();
        names.insert(10, "MATCHED".to_string());
        let table = DecoderTable::new(bytes, names);

        assert_eq!(table.decode(0b110000), Some("MATCHED"));
        assert_eq!(table.decode(0b010000), None);
    }

    /// Integration test: verify MOV vs VGE disambiguation using generated tables.
    #[test]
    fn test_real_mv_slot_decode() {
        let output = crate::tablegen::load_from_generated();
        let mv_table = output.decoder_tables.get("mv")
            .expect("Should have mv decoder table");

        let mv_bits: u64 = 0x00713c;
        let result = mv_table.decode(mv_bits);

        if let Some(name) = result {
            assert!(
                !name.starts_with("VGE"),
                "MV bits 0x{:06x} decoded as '{}' but should be MOV variant",
                mv_bits, name,
            );
            assert!(
                name.contains("MOV") || name.contains("mov"),
                "MV bits 0x{:06x} decoded as '{}', expected a MOV instruction",
                mv_bits, name,
            );
        } else {
            panic!("MV bits 0x{:06x} failed to decode", mv_bits);
        }
    }
}
