#!/usr/bin/env python3
"""Generate Rust routing table source from extracted JSON.

Reads the routing_tables.json produced by extract_routing.py and generates
a Rust module with const arrays in CSR (compressed sparse row) format.

Output format uses parallel arrays for zero-allocation lookup:
  OUT_START[513]: entry range for output i = [OUT_START[i]..OUT_START[i+1])
  INPUT[N]:       input element index per entry
  BIT_START[N+1]: bit range for entry j = [BIT_START[j]..BIT_START[j+1])
  BITS[M]:        flat array of all control bit indices
"""

import json
import sys
from pathlib import Path


def gen_array(name: str, ty: str, values: list, per_line: int = 16) -> str:
    """Generate a Rust static array declaration."""
    lines = [f"static {name}: [{ty}; {len(values)}] = ["]
    for i in range(0, len(values), per_line):
        chunk = values[i:i+per_line]
        line = ", ".join(str(v) for v in chunk)
        lines.append(f"    {line},")
    lines.append("];")
    return "\n".join(lines)


def gen_routing_table(prefix: str, routes: dict, num_outputs: int, bit_type: str) -> str:
    """Generate CSR-format routing tables for one routing function.

    Each entry now has a negation flag: when negated, the selection fires
    when NONE of the listed bits are set (default/fallback routing).
    """
    out_start = []
    all_input = []
    all_negated = []  # 0 = normal (any bit set), 1 = negated (no bit set)
    bit_start = []
    all_bits = []

    entry_idx = 0
    for i in range(num_outputs):
        out_start.append(entry_idx)
        entries = routes.get(str(i), [])
        for entry in entries:
            if len(entry) == 3:
                input_idx, bits, negated = entry
            else:
                input_idx, bits = entry
                negated = False
            all_input.append(input_idx)
            all_negated.append(1 if negated else 0)
            bit_start.append(len(all_bits))
            all_bits.extend(bits)
            entry_idx += 1
    out_start.append(entry_idx)
    bit_start.append(len(all_bits))

    code = []
    code.append(f"/// Number of entries in {prefix} routing table")
    code.append(f"const {prefix}_NUM_ENTRIES: usize = {len(all_input)};")
    code.append(f"/// Number of control bits referenced in {prefix} routing table")
    code.append(f"const {prefix}_NUM_BITS: usize = {len(all_bits)};")
    code.append("")
    code.append(f"/// Entry range for output i: [{prefix}_OUT_START[i]..{prefix}_OUT_START[i+1])")
    code.append(gen_array(f"{prefix}_OUT_START", "u16", out_start, 20))
    code.append("")
    code.append(f"/// Input element index for each entry")
    code.append(gen_array(f"{prefix}_INPUT", "u8", all_input, 24))
    code.append("")
    code.append(f"/// Bit index range for entry j: [{prefix}_BIT_START[j]..{prefix}_BIT_START[j+1])")
    code.append(gen_array(f"{prefix}_BIT_START", "u16", bit_start, 20))
    code.append("")
    code.append(f"/// Flat array of control bit indices")
    code.append(gen_array(f"{prefix}_BITS", bit_type, all_bits, 20))
    code.append("")
    code.append(f"/// Negation flag per entry: 0 = normal (any bit set), 1 = negated (no bit set)")
    code.append(gen_array(f"{prefix}_NEG", "u8", all_negated, 32))

    return "\n".join(code)


def main():
    json_path = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("/tmp/claude-1000/routing_tables.json")
    with open(json_path) as f:
        data = json.load(f)

    code = []
    code.append("// Auto-generated routing tables for vmac crossbar (prmx) and Y-perm (prmy).")
    code.append("//")
    code.append("// Generated by tools/vmac-oracle/gen_rust_routing.py from vmac_functions.inc.")
    code.append("// DO NOT EDIT MANUALLY.")
    code.append("//")
    code.append("// CSR (compressed sparse row) format:")
    code.append("//   For output i: entries at indices [OUT_START[i]..OUT_START[i+1])")
    code.append("//   For entry j:  input = INPUT[j], control bits at [BIT_START[j]..BIT_START[j+1])")
    code.append("//   Evaluation:   output[i] = OR of (input[INPUT[j]] if any(m[BITS[k]]))")
    code.append("")

    code.append("// ---- Crossbar (prmx_hw): 128 input bytes -> 512 output bytes ----")
    code.append("// Control word: 789 bits = concat(smode[768], pmode[0:20])")
    code.append("")
    code.append(gen_routing_table("PRMX", data["prmx"]["routes"], 512, "u16"))

    code.append("")
    code.append("// ---- Y-Perm (prmy_hw): 128 input nibbles -> 512 output nibbles ----")
    code.append("// Control word: 26 bits = pmode[0:25]")
    code.append("")
    code.append(gen_routing_table("PRMY", data["prmy"]["routes"], 512, "u8"))

    code.append("")
    code.append("#[inline]")
    code.append("fn check_sel_u16(m: &[u64], bstart: usize, bend: usize, bits: &[u16], neg: bool) -> bool {")
    code.append("    let mut any_set = false;")
    code.append("    for k in bstart..bend {")
    code.append("        let bit = bits[k] as usize;")
    code.append("        if (m[bit / 64] >> (bit % 64)) & 1 != 0 { any_set = true; break; }")
    code.append("    }")
    code.append("    if neg { !any_set } else { any_set }")
    code.append("}")
    code.append("")
    code.append("#[inline]")
    code.append("fn check_sel_u8(m: &[u64], bstart: usize, bend: usize, bits: &[u8], neg: bool) -> bool {")
    code.append("    let mut any_set = false;")
    code.append("    for k in bstart..bend {")
    code.append("        let bit = bits[k] as usize;")
    code.append("        if (m[bit / 64] >> (bit % 64)) & 1 != 0 { any_set = true; break; }")
    code.append("    }")
    code.append("    if neg { !any_set } else { any_set }")
    code.append("}")
    code.append("")
    code.append("/// Evaluate prmx crossbar routing.")
    code.append("pub fn eval_prmx(a: &[u8; 128], m: &[u64; 13]) -> [u8; 512] {")
    code.append("    let mut r = [0u8; 512];")
    code.append("    for i in 0..512 {")
    code.append("        let start = PRMX_OUT_START[i] as usize;")
    code.append("        let end = PRMX_OUT_START[i + 1] as usize;")
    code.append("        for j in start..end {")
    code.append("            let bstart = PRMX_BIT_START[j] as usize;")
    code.append("            let bend = PRMX_BIT_START[j + 1] as usize;")
    code.append("            let neg = PRMX_NEG[j] != 0;")
    code.append("            if check_sel_u16(&m[..], bstart, bend, &PRMX_BITS, neg) {")
    code.append("                r[i] |= a[PRMX_INPUT[j] as usize];")
    code.append("            }")
    code.append("        }")
    code.append("    }")
    code.append("    r")
    code.append("}")
    code.append("")
    code.append("/// Evaluate prmy Y-perm routing.")
    code.append("pub fn eval_prmy(a_nibbles: &[u8; 128], pmode: u32) -> [u8; 512] {")
    code.append("    let m: [u64; 1] = [pmode as u64];")
    code.append("    let mut r = [0u8; 512];")
    code.append("    r[0] = a_nibbles[0]; // output 0 = unconditional passthrough")
    code.append("    for i in 1..512 {")
    code.append("        let start = PRMY_OUT_START[i] as usize;")
    code.append("        let end = PRMY_OUT_START[i + 1] as usize;")
    code.append("        for j in start..end {")
    code.append("            let bstart = PRMY_BIT_START[j] as usize;")
    code.append("            let bend = PRMY_BIT_START[j + 1] as usize;")
    code.append("            let neg = PRMY_NEG[j] != 0;")
    code.append("            if check_sel_u8(&m[..], bstart, bend, &PRMY_BITS, neg) {")
    code.append("                r[i] |= a_nibbles[PRMY_INPUT[j] as usize];")
    code.append("            }")
    code.append("        }")
    code.append("    }")
    code.append("    r")
    code.append("}")

    print("\n".join(code))


if __name__ == "__main__":
    main()
