//! Build script for xdna-archspec.
//!
//! Drives all AIE2 arch-data code generation from the validated
//! ArchModel (device-model + AM025 JSON, cross-validated via
//! Confirmed<T>). Output files land in $OUT_DIR and are included
//! by modules under `src/aie2/`.
//!
//! Because this script lives inside the crate it is generating for,
//! it cannot declare `xdna-archspec` as a build-dep. Module source
//! files are `#[path]`-included so the same types and parsers used
//! at runtime are available at build time.

#[path = "src/types.rs"]
mod types;
#[path = "src/regdb.rs"]
mod regdb;
#[path = "src/device_model.rs"]
mod device_model;
#[path = "src/regdb_extractor.rs"]
mod regdb_extractor;
#[path = "src/tablegen.rs"]
mod tablegen;
#[path = "src/model_builder.rs"]
mod model_builder;

use std::collections::HashMap;
use std::env;
use std::fmt::Write as FmtWrite;
use std::fs;
use std::path::{Path, PathBuf};

// ============================================================================
// Port type constants -- mirrors arch::port_type for codegen output
// ============================================================================
// These are our encoding convention, not hardware-defined. The generated code
// references `port_type::*` which is defined in the same module scope.

const PT_CORE: u8 = 0;
const PT_FIFO: u8 = 1;
const PT_TRACE: u8 = 2;
const PT_CTRL: u8 = 3;
const PT_NORTH_BASE: u8 = 10;
const PT_SOUTH_BASE: u8 = 20;
const PT_EAST_BASE: u8 = 30;
const PT_WEST_BASE: u8 = 40;
const PT_DMA_BASE: u8 = 50;

// ============================================================================
// Entry point
// ============================================================================

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    // Workspace root = crate's parent's parent (crates/xdna-archspec -> crates -> root).
    let workspace_root = manifest_dir
        .parent()
        .and_then(|p| p.parent())
        .expect("xdna-archspec manifest has no grandparent (expected <workspace-root>/crates/xdna-archspec)");

    // Resolve AM025 JSON: MLIR_AIE_PATH env var or sibling dir.
    let mlir_aie = env::var("MLIR_AIE_PATH").unwrap_or_else(|_| {
        workspace_root
            .parent()
            .expect("workspace root has no parent -- set MLIR_AIE_PATH to override")
            .join("mlir-aie")
            .to_string_lossy()
            .to_string()
    });
    let am025_path = Path::new(&mlir_aie).join("lib/Dialect/AIE/Util/aie_registers_aie2.json");

    // Device model is in the workspace root.
    let device_model_path = workspace_root.join("tools/aie-device-models.json");

    // Rebuild triggers.
    println!("cargo:rerun-if-changed={}", am025_path.display());
    println!("cargo:rerun-if-changed={}", device_model_path.display());
    println!("cargo:rerun-if-env-changed=MLIR_AIE_PATH");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-env-changed=AIE_RT_PATH");

    // Build the validated ArchModel (cross-validated against aie-rt via extract_aiert).
    let regdb = regdb::RegisterDb::from_file(&am025_path).unwrap_or_else(|e| {
        panic!(
            "Cannot load AM025 register database at {}:\n  {}",
            am025_path.display(),
            e
        )
    });
    let mut arch_model =
        model_builder::build_arch_model(&device_model_path, &regdb, "npu1")
            .unwrap_or_else(|e| panic!("Failed to build ArchModel: {}", e));

    // Cross-validate subsystem ranges and generate aie-rt extracted files.
    // Must run before gen_arch so the model's Confirmed<T> sources reflect
    // both AM025 and aie-rt when code is generated.
    extract_aiert(workspace_root, &out_dir, &mut arch_model);

    // Generate architecture constants from the validated model.
    gen_arch(&arch_model, &out_dir);
}

// ============================================================================
// Helpers
// ============================================================================

/// File header comment for generated source.
fn gen_header(source_desc: &str) -> String {
    format!(
        "// Auto-generated by build.rs from {}.\n\
         // Do not edit manually.\n\n",
        source_desc
    )
}

// ============================================================================
// gen_arch: Comprehensive architecture constants from ArchModel
// ============================================================================

fn gen_arch(model: &crate::types::ArchModel, out_dir: &Path) {
    use crate::types::TileKind;

    let mut out = gen_header("ArchModel (device model + AM025, cross-validated)");

    // Device-level constants
    if let Some(ref dc) = model.device_constants {
        writeln!(out, "/// Maximum lock counter value.").unwrap();
        writeln!(out, "pub const MAX_LOCK_VALUE: i32 = {};", dc.max_lock_value).unwrap();
        writeln!(out).unwrap();
        writeln!(out, "/// Minimum lock counter value.").unwrap();
        writeln!(out, "pub const MIN_LOCK_VALUE: i32 = {};", dc.min_lock_value).unwrap();
        writeln!(out).unwrap();
    }

    // Array topology
    if let Some(ref topo) = model.array_topology {
        writeln!(out, "/// Number of columns in the NPU array.").unwrap();
        writeln!(out, "pub const COLUMNS: u8 = {};", topo.columns).unwrap();
        writeln!(out).unwrap();
        writeln!(out, "/// Number of rows in the NPU array (including shim row).").unwrap();
        writeln!(out, "pub const ROWS: u8 = {};", topo.rows).unwrap();
        writeln!(out).unwrap();
        writeln!(out, "/// Number of memory tile rows (row 1 through row N are mem tiles).").unwrap();
        writeln!(out, "pub const NUM_MEM_TILE_ROWS: u8 = {};", topo.num_mem_tile_rows).unwrap();
        writeln!(out).unwrap();

        // Tile address encoding (AM020 Ch2)
        writeln!(out, "/// Column shift for tile address encoding (bits 31:25).").unwrap();
        writeln!(out, "pub const TILE_COL_SHIFT: u32 = {};", topo.column_shift).unwrap();
        writeln!(out).unwrap();
        writeln!(out, "/// Row shift for tile address encoding (bits 24:20).").unwrap();
        writeln!(out, "pub const TILE_ROW_SHIFT: u32 = {};", topo.row_shift).unwrap();
        writeln!(out).unwrap();

        // Derived from shifts
        let offset_bits = topo.row_shift;
        let row_bits = topo.column_shift - topo.row_shift;
        let col_bits = 32 - topo.column_shift;
        let offset_mask = (1u32 << offset_bits) - 1;
        writeln!(out, "/// Offset mask for tile-local addresses (bits {}:0).", offset_bits - 1).unwrap();
        writeln!(out, "pub const TILE_OFFSET_MASK: u32 = 0x{:X};", offset_mask).unwrap();
        writeln!(out).unwrap();
        writeln!(out, "/// Row bits in tile address.").unwrap();
        writeln!(out, "pub const TILE_ROW_BITS: u32 = {};", row_bits).unwrap();
        writeln!(out).unwrap();
        writeln!(out, "/// Column bits in tile address.").unwrap();
        writeln!(out, "pub const TILE_COL_BITS: u32 = {};", col_bits).unwrap();
        writeln!(out).unwrap();

        // Row indices (derived from topology)
        writeln!(out, "/// Shim tile row index.").unwrap();
        writeln!(out, "pub const SHIM_ROW: u8 = 0;").unwrap();
        writeln!(out).unwrap();
        writeln!(out, "/// First compute tile row index.").unwrap();
        writeln!(out, "pub const COMPUTE_ROW_START: u8 = {} + 1;", topo.num_mem_tile_rows).unwrap();
        writeln!(out).unwrap();
    }

    // Per-tile-type modules
    let tile_types: &[(&str, TileKind)] = &[
        ("compute", TileKind::Compute),
        ("memtile", TileKind::Mem),
        ("shim", TileKind::ShimNoc),
    ];

    for &(mod_name, kind) in tile_types {
        let tile = model.tile_types.iter().find(|t| t.kind == kind);
        let tile = match tile {
            Some(t) => t,
            None => continue,
        };

        writeln!(out, "/// {} tile constants.", tile.name).unwrap();
        writeln!(out, "pub mod {} {{", mod_name).unwrap();

        // Memory model
        if let Some(ref mem) = tile.memory {
            writeln!(out, "    /// Total data memory size in bytes.").unwrap();
            writeln!(out, "    pub const MEMORY_SIZE: u64 = {};", mem.size_bytes).unwrap();
            writeln!(out, "    /// Logical bank count (programmer/compiler view).").unwrap();
            writeln!(out, "    pub const LOGICAL_BANKS: u8 = {};", mem.logical.num_banks).unwrap();
            writeln!(out, "    /// Logical bank size in bytes.").unwrap();
            writeln!(out, "    pub const LOGICAL_BANK_SIZE: u64 = {};", mem.logical.bank_size).unwrap();
            if let Some(ref phys) = mem.physical {
                writeln!(out, "    /// Physical bank count (SRAM arrays, for conflict detection).").unwrap();
                writeln!(out, "    pub const PHYSICAL_BANKS: u8 = {};", phys.num_banks).unwrap();
                writeln!(out, "    /// Physical bank size in bytes.").unwrap();
                writeln!(out, "    pub const PHYSICAL_BANK_SIZE: u64 = {};", phys.bank_size).unwrap();
                writeln!(out, "    /// Physical bank width in bits (SRAM word width).").unwrap();
                writeln!(out, "    pub const PHYSICAL_BANK_WIDTH_BITS: u16 = {};", phys.bank_width_bits).unwrap();
            }
            if let Some(pmem) = mem.program_memory_bytes {
                writeln!(out, "    /// Program (instruction) memory size in bytes.").unwrap();
                writeln!(out, "    pub const PROGRAM_MEMORY_SIZE: u64 = {};", pmem).unwrap();
            }
        }

        // Resource counts (from Confirmed<T> -- cross-validated)
        let inst = &tile.instances;
        writeln!(out).unwrap();
        writeln!(out, "    /// Number of locks (cross-validated).").unwrap();
        writeln!(out, "    pub const NUM_LOCKS: u8 = {};", inst.locks.value()).unwrap();
        writeln!(out, "    /// Number of buffer descriptors (cross-validated).").unwrap();
        writeln!(out, "    pub const NUM_BDS: u8 = {};", inst.bds.value()).unwrap();
        writeln!(out, "    /// Number of DMA channels per direction (cross-validated).").unwrap();
        writeln!(out, "    pub const NUM_DMA_CHANNELS: u8 = {};", inst.channels.value()).unwrap();

        // Core address map (compute tiles only)
        if let Some(ref cam) = tile.core_address_map {
            writeln!(out).unwrap();
            writeln!(out, "    /// Start of data memory in core address space.").unwrap();
            writeln!(out, "    /// Cardinal direction = address / MEMORY_SIZE.").unwrap();
            writeln!(out, "    /// Source: aie-rt AieMlCoreMod.DataMemAddr.").unwrap();
            writeln!(out, "    pub const DATA_MEM_ADDR: u32 = 0x{:X};", cam.data_mem_addr).unwrap();
            writeln!(out, "    /// Log2 of data memory size per quadrant (address shift).").unwrap();
            writeln!(out, "    /// Source: aie-rt AieMlCoreMod.DataMemShift.").unwrap();
            writeln!(out, "    pub const DATA_MEM_SHIFT: u8 = {};", cam.data_mem_shift).unwrap();
            writeln!(out, "    /// Whether memory modules alternate sides by row.").unwrap();
            writeln!(out, "    /// AIE1=true (checkerboard), AIE2=false (East always local).").unwrap();
            writeln!(out, "    pub const IS_CHECKERBOARD: bool = {};", cam.is_checkerboard).unwrap();
            writeln!(out, "    /// Program memory offset in host/CDO address space.").unwrap();
            writeln!(out, "    /// Source: aie-rt XAIEMLGBL_CORE_MODULE_PROGRAM_MEMORY.").unwrap();
            writeln!(out, "    pub const PROGRAM_MEM_HOST_OFFSET: u32 = 0x{:X};", cam.program_mem_host_offset).unwrap();
        }

        writeln!(out, "}}\n").unwrap();
    }

    // Cardinal direction constants for core data address space.
    // These are the quotient of (address / DataMemSize) as used by
    // aie-rt's _XAie_GetTargetTileLoc() for ELF loading and memory routing.
    writeln!(out, "/// Cardinal direction constants for core data memory addressing.").unwrap();
    writeln!(out, "///").unwrap();
    writeln!(out, "/// The core addresses data memory via `address / MEMORY_SIZE`,").unwrap();
    writeln!(out, "/// yielding a cardinal direction index 4-7.").unwrap();
    writeln!(out, "///").unwrap();
    writeln!(out, "/// Source: aie-rt `_XAie_GetTargetTileLoc()` (xaie_elfloader.c).").unwrap();
    writeln!(out, "pub mod cardinal {{").unwrap();
    writeln!(out, "    /// South neighbor (row - 1).").unwrap();
    writeln!(out, "    pub const SOUTH: u8 = 4;").unwrap();
    writeln!(out, "    /// West neighbor (col - 1 for non-checkerboard, or row-dependent).").unwrap();
    writeln!(out, "    pub const WEST: u8 = 5;").unwrap();
    writeln!(out, "    /// North neighbor (row + 1).").unwrap();
    writeln!(out, "    pub const NORTH: u8 = 6;").unwrap();
    writeln!(out, "    /// East / local (same tile for non-checkerboard, or row-dependent).").unwrap();
    writeln!(out, "    pub const EAST: u8 = 7;").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // Data memory host offset (always 0 for all tile types -- data memory
    // is at the start of the tile register space in the host/CDO view).
    writeln!(out, "/// Data memory offset in host/CDO address space (always 0).").unwrap();
    writeln!(out, "pub const DATA_MEM_HOST_OFFSET: u32 = 0;").unwrap();
    writeln!(out).unwrap();

    // -- Timing model --
    if let Some(ref t) = model.timing {
        writeln!(out, "/// Timing constants (AM020 prose + hardware observation).").unwrap();
        writeln!(out, "pub mod timing {{").unwrap();

        writeln!(out, "    // Lock timing").unwrap();
        writeln!(out, "    pub const LOCK_ACQUIRE_LATENCY: u8 = {};", t.lock.acquire_latency).unwrap();
        writeln!(out, "    pub const LOCK_RELEASE_LATENCY: u8 = {};", t.lock.release_latency).unwrap();
        writeln!(out, "    pub const LOCK_RETRY_INTERVAL: u8 = {};", t.lock.retry_interval).unwrap();
        writeln!(out).unwrap();

        writeln!(out, "    // Instruction timing").unwrap();
        writeln!(out, "    /// Data memory access pipeline depth.").unwrap();
        writeln!(out, "    pub const DATA_MEMORY_LATENCY: u8 = {};", t.instruction.data_memory_latency).unwrap();
        writeln!(out, "    /// Branch penalty: cycles lost on taken branch.").unwrap();
        writeln!(out, "    pub const BRANCH_PENALTY: u8 = {};", t.instruction.branch_penalty).unwrap();
        writeln!(out).unwrap();

        writeln!(out, "    // DMA timing").unwrap();
        writeln!(out, "    pub const DMA_BD_SETUP_CYCLES: u8 = {};", t.dma.bd_setup_cycles).unwrap();
        writeln!(out, "    pub const DMA_CHANNEL_START_CYCLES: u8 = {};", t.dma.channel_start_cycles).unwrap();
        writeln!(out, "    pub const DMA_WORDS_PER_CYCLE: u8 = {};", t.dma.words_per_cycle).unwrap();
        writeln!(out, "    pub const DMA_MEMORY_LATENCY_CYCLES: u8 = {};", t.dma.memory_latency_cycles).unwrap();
        writeln!(out, "    pub const DMA_LOCK_ACQUIRE_CYCLES: u8 = {};", t.dma.lock_acquire_cycles).unwrap();
        writeln!(out, "    pub const DMA_LOCK_RELEASE_CYCLES: u8 = {};", t.dma.lock_release_cycles).unwrap();
        writeln!(out, "    pub const DMA_BD_CHAIN_CYCLES: u8 = {};", t.dma.bd_chain_cycles).unwrap();
        writeln!(out, "    pub const DMA_HOST_MEMORY_LATENCY_CYCLES: u16 = {};", t.dma.host_memory_latency_cycles).unwrap();
        writeln!(out).unwrap();

        writeln!(out, "    // Stream switch timing").unwrap();
        writeln!(out, "    pub const STREAM_LOCAL_SLAVE_FIFO_DEPTH: u8 = {};", t.stream_switch.local_slave_fifo_depth).unwrap();
        writeln!(out, "    pub const STREAM_LOCAL_MASTER_FIFO_DEPTH: u8 = {};", t.stream_switch.local_master_fifo_depth).unwrap();
        writeln!(out, "    pub const STREAM_LOCAL_TO_LOCAL_LATENCY: u8 = {};", t.stream_switch.local_to_local_latency).unwrap();
        writeln!(out, "    pub const STREAM_LOCAL_TO_EXTERNAL_LATENCY: u8 = {};", t.stream_switch.local_to_external_latency).unwrap();
        writeln!(out, "    pub const STREAM_EXTERNAL_TO_EXTERNAL_LATENCY: u8 = {};", t.stream_switch.external_to_external_latency).unwrap();
        writeln!(out, "    pub const STREAM_EXTERNAL_TO_LOCAL_LATENCY: u8 = {};", t.stream_switch.external_to_local_latency).unwrap();
        writeln!(out, "    pub const PACKET_ARBITRATION_OVERHEAD: u8 = {};", t.stream_switch.packet_arbitration_overhead).unwrap();
        writeln!(out).unwrap();

        writeln!(out, "    // Route latency (derived from stream switch timing)").unwrap();
        writeln!(out, "    pub const ROUTE_LOCAL_TO_LOCAL: u8 = STREAM_LOCAL_TO_LOCAL_LATENCY;").unwrap();
        writeln!(out, "    pub const ROUTE_LOCAL_TO_EXTERNAL: u8 = STREAM_LOCAL_TO_EXTERNAL_LATENCY;").unwrap();
        writeln!(out, "    pub const ROUTE_EXTERNAL_TO_LOCAL: u8 = STREAM_EXTERNAL_TO_LOCAL_LATENCY;").unwrap();
        writeln!(out, "    pub const ROUTE_EXTERNAL_TO_EXTERNAL: u8 = STREAM_EXTERNAL_TO_EXTERNAL_LATENCY;").unwrap();
        writeln!(out, "    pub const ROUTE_PER_HOP: u8 = ROUTE_EXTERNAL_TO_EXTERNAL;").unwrap();

        writeln!(out, "}}\n").unwrap();
    }

    // -- Packet format --
    if let Some(ref p) = model.packet {
        writeln!(out, "/// Stream packet header bit layout (AM020 Table 2).").unwrap();
        writeln!(out, "pub mod packet {{").unwrap();
        writeln!(out, "    pub const STREAM_ID_MASK: u32 = {:#X};", p.stream.stream_id_mask).unwrap();
        writeln!(out, "    pub const TYPE_SHIFT: u8 = {};", p.stream.packet_type_shift).unwrap();
        writeln!(out, "    pub const TYPE_MASK: u32 = {:#X};", p.stream.packet_type_mask).unwrap();
        writeln!(out, "    pub const SRC_ROW_SHIFT: u8 = {};", p.stream.src_row_shift).unwrap();
        writeln!(out, "    pub const SRC_ROW_MASK: u32 = {:#X};", p.stream.src_row_mask).unwrap();
        writeln!(out, "    pub const SRC_COL_SHIFT: u8 = {};", p.stream.src_col_shift).unwrap();
        writeln!(out, "    pub const SRC_COL_MASK: u32 = {:#X};", p.stream.src_col_mask).unwrap();
        writeln!(out, "    pub const PARITY_SHIFT: u8 = {};", p.stream.parity_shift).unwrap();
        writeln!(out, "}}\n").unwrap();

        writeln!(out, "/// Control packet header format and operation codes (AM020 Table 3).").unwrap();
        writeln!(out, "pub mod ctrl_packet {{").unwrap();
        writeln!(out, "    pub const ADDRESS_MASK: u32 = {:#010X};", p.control.address_mask).unwrap();
        writeln!(out, "    pub const LENGTH_SHIFT: u8 = {};", p.control.length_shift).unwrap();
        writeln!(out, "    pub const LENGTH_MASK: u32 = {:#X};", p.control.length_mask).unwrap();
        writeln!(out, "    pub const OPERATION_SHIFT: u8 = {};", p.control.operation_shift).unwrap();
        writeln!(out, "    pub const OPERATION_MASK: u32 = {:#X};", p.control.operation_mask).unwrap();
        writeln!(out, "    pub const RESPONSE_ID_SHIFT: u8 = {};", p.control.response_id_shift).unwrap();
        writeln!(out, "    pub const RESPONSE_ID_MASK: u32 = {:#X};", p.control.response_id_mask).unwrap();
        writeln!(out, "    pub const PARITY_BIT: u8 = {};", p.control.parity_bit).unwrap();
        writeln!(out).unwrap();
        writeln!(out, "    pub const OP_WRITE: u8 = {};", p.control.op_write).unwrap();
        writeln!(out, "    pub const OP_READ: u8 = {};", p.control.op_read).unwrap();
        writeln!(out, "    pub const OP_WRITE_INCR: u8 = {};", p.control.op_write_incr).unwrap();
        writeln!(out, "    pub const OP_BLOCK_WRITE: u8 = {};", p.control.op_block_write).unwrap();
        writeln!(out, "}}\n").unwrap();

        writeln!(out, "/// DMA Finish-on-TLAST mode values (AM025 + aie-rt).").unwrap();
        writeln!(out, "pub mod fot {{").unwrap();
        writeln!(out, "    pub const DISABLED: u8 = {};", p.fot.disabled).unwrap();
        writeln!(out, "    pub const NO_COUNTS: u8 = {};", p.fot.no_counts).unwrap();
        writeln!(out, "    pub const COUNTS_WITH_TOKENS: u8 = {};", p.fot.counts_with_tokens).unwrap();
        writeln!(out, "    pub const COUNTS_FROM_REGISTER: u8 = {};", p.fot.counts_from_register).unwrap();
        writeln!(out, "}}\n").unwrap();
    }

    // -- Processor model (VLIW, registers, pipeline) --
    if let Some(ref proc) = model.processor {
        writeln!(out, "/// VLIW processor model (slot widths, register sizes, pipeline).").unwrap();
        writeln!(out, "pub mod processor {{").unwrap();

        // Per-slot width constants
        writeln!(out, "    // VLIW slot widths in bits (from llvm-aie AIE2Slots.td)").unwrap();
        for (name, width) in &proc.slot_widths {
            writeln!(out, "    pub const {}_WIDTH: u8 = {};", name.to_ascii_uppercase(), width).unwrap();
        }
        writeln!(out).unwrap();

        // Register widths
        writeln!(out, "    // Register widths in bits (from llvm-aie AIE2GenRegisterInfo.td)").unwrap();
        writeln!(out, "    pub const VECTOR_REGISTER_BITS: u16 = {};", proc.vector_register_bits).unwrap();
        writeln!(out, "    pub const VECTOR_PAIR_BITS: u16 = {};", proc.vector_pair_bits).unwrap();
        writeln!(out, "    pub const ACCUMULATOR_BITS: u16 = {};", proc.accumulator_bits).unwrap();
        writeln!(out).unwrap();

        // Derived byte sizes (commonly needed)
        writeln!(out, "    // Derived byte sizes").unwrap();
        writeln!(out, "    pub const VECTOR_REGISTER_BYTES: usize = {} / 8;", proc.vector_register_bits).unwrap();
        writeln!(out, "    pub const VECTOR_PAIR_BYTES: usize = {} / 8;", proc.vector_pair_bits).unwrap();
        writeln!(out).unwrap();

        // Pipeline constants
        writeln!(out, "    // Pipeline constants").unwrap();
        writeln!(out, "    pub const BRANCH_DELAY_SLOTS: u8 = {};", proc.branch_delay_slots).unwrap();
        writeln!(out, "    pub const PARTIAL_STORE_DATA_LATENCY: u8 = {};", proc.partial_store_data_latency).unwrap();
        writeln!(out, "    pub const SRS_SHIFT_BIAS: u8 = {};", proc.srs_shift_bias).unwrap();
        writeln!(out, "}}\n").unwrap();
    }

    fs::write(out_dir.join("gen_arch.rs"), out).unwrap();
}

// ============================================================================
// extract_aiert: aie-rt header extraction (DMA, Lock, Stream Switch)
// ============================================================================

/// Top-level: locate aie-rt, run gcc -E, parse, generate all 3 files,
/// and cross-validate subsystem address ranges in the ArchModel.
fn extract_aiert(
    workspace_root: &Path,
    out_dir: &Path,
    arch_model: &mut crate::types::ArchModel,
) {
    use crate::types::{
        ModuleKind, Source, SourceAttribution, SubsystemKind, TileKind,
    };

    // Rebuild trigger already set in main() above.

    let aiert_dir = env::var("AIE_RT_PATH")
        .map(PathBuf::from)
        .unwrap_or_else(|_| {
            workspace_root
                .parent()
                .expect("workspace root has no parent directory -- set AIE_RT_PATH to override")
                .join("aie-rt/driver/src")
        });

    let reginit_path = aiert_dir.join("global/xaiemlgbl_reginit.c");
    if reginit_path.exists() {
        println!("cargo:rerun-if-changed={}", reginit_path.display());
    }

    let preprocessed = match run_aiert_preprocessor(&aiert_dir) {
        Some(text) => text,
        None => {
            write_aiert_stubs(out_dir);
            return;
        }
    };

    let dma_modules = parse_dma_modules(&preprocessed);
    let lock_modules = parse_lock_modules(&preprocessed);
    let port_maps = parse_port_maps(&preprocessed);

    // Cross-validate subsystem offset_start values against aie-rt.
    // DMA BaseAddr is the BD base offset, matching the DMA subsystem's
    // offset_start from AM025 register grouping.
    // Lock LockSetValBase is the lock value register base, matching the
    // Lock subsystem's offset_start from AM025 register grouping.
    let mut confirmations = Vec::new();

    // Map aie-rt DMA module names to (TileKind, ModuleKind)
    for m in &dma_modules {
        let (tile_kind, mod_kind) = if m.name.contains("MemTile") {
            (TileKind::Mem, ModuleKind::MemTile)
        } else if m.name.contains("Shim") {
            (TileKind::ShimNoc, ModuleKind::Shim)
        } else {
            (TileKind::Compute, ModuleKind::Memory)
        };

        let base_addr = get_field(&m.fields, "BaseAddr", &m.name);
        let source = SourceAttribution {
            origin: Source::AieRt,
            file: "xaiemlgbl_reginit.c".into(),
            detail: format!("{}.BaseAddr", m.name),
        };
        confirmations.push((tile_kind, mod_kind, SubsystemKind::Dma, base_addr, source));
    }

    // Map aie-rt Lock module names to (TileKind, ModuleKind)
    for m in &lock_modules {
        let (tile_kind, mod_kind) = if m.name.contains("MemTile") {
            (TileKind::Mem, ModuleKind::MemTile)
        } else if m.name.contains("Shim") {
            (TileKind::ShimNoc, ModuleKind::Shim)
        } else {
            (TileKind::Compute, ModuleKind::Memory)
        };

        let set_val_base = get_field(&m.fields, "LockSetValBase", &m.name);
        let source = SourceAttribution {
            origin: Source::AieRt,
            file: "xaiemlgbl_reginit.c".into(),
            detail: format!("{}.LockSetValBase", m.name),
        };
        confirmations.push((tile_kind, mod_kind, SubsystemKind::Lock, set_val_base, source));
    }

    crate::model_builder::confirm_subsystem_ranges(arch_model, &confirmations);

    gen_aiert_dma(&dma_modules, out_dir);
    gen_aiert_locks(&lock_modules, out_dir);
    gen_aiert_ports(&port_maps, out_dir);
}

/// Run gcc -E on xaiemlgbl_reginit.c with all aie-rt include paths.
fn run_aiert_preprocessor(aiert_dir: &Path) -> Option<String> {
    use std::process::Command;

    let reginit = aiert_dir.join("global/xaiemlgbl_reginit.c");
    if !reginit.exists() {
        eprintln!(
            "cargo:warning=aie-rt not found at {}, skipping aie-rt extraction",
            aiert_dir.display()
        );
        return None;
    }

    // All subdirectories that contain headers
    let subdirs = [
        "", "common", "core", "device", "dma", "events", "global",
        "interrupt", "io_backend", "lite", "locks", "memory", "npi",
        "perfcnt", "pl", "pm", "routing", "stream_switch", "timer",
        "trace", "util",
    ];

    let mut cmd = Command::new("gcc");
    cmd.arg("-E");
    for subdir in &subdirs {
        let inc = if subdir.is_empty() {
            aiert_dir.to_path_buf()
        } else {
            aiert_dir.join(subdir)
        };
        cmd.arg("-I").arg(&inc);
    }
    cmd.arg(&reginit);

    let output = match cmd.output() {
        Ok(o) if o.status.success() => o,
        Ok(o) => {
            let stderr = String::from_utf8_lossy(&o.stderr);
            eprintln!(
                "cargo:warning=gcc -E failed ({}): {}, skipping aie-rt extraction",
                o.status, stderr
            );
            return None;
        }
        Err(e) => {
            eprintln!(
                "cargo:warning=Cannot run gcc ({}), skipping aie-rt extraction",
                e
            );
            return None;
        }
    };

    Some(String::from_utf8_lossy(&output.stdout).to_string())
}

// -- Data structures for parsed aie-rt structs --

struct DmaModData {
    name: String,
    fields: HashMap<String, String>,
}

struct LockModData {
    name: String,
    fields: HashMap<String, String>,
}

struct PortMapData {
    name: String,
    entries: Vec<(String, u8)>, // (PortType name, PortNum)
}

/// Parse all XAie_DmaMod struct initializers from preprocessed text.
fn parse_dma_modules(text: &str) -> Vec<DmaModData> {
    parse_struct_initializers(text, "XAie_DmaMod")
        .into_iter()
        .map(|(name, fields)| DmaModData { name, fields })
        .collect()
}

/// Parse all XAie_LockMod struct initializers from preprocessed text.
fn parse_lock_modules(text: &str) -> Vec<LockModData> {
    parse_struct_initializers(text, "XAie_LockMod")
        .into_iter()
        .map(|(name, fields)| LockModData { name, fields })
        .collect()
}

/// Parse all XAie_StrmSwPortMap array initializers from preprocessed text.
fn parse_port_maps(text: &str) -> Vec<PortMapData> {
    let mut results = Vec::new();
    let lines: Vec<&str> = text.lines().collect();
    let mut i = 0;

    while i < lines.len() {
        let line = lines[i].trim();
        // Look for: static const XAie_StrmSwPortMap <name>[] =
        if line.contains("XAie_StrmSwPortMap") && line.contains("[]") {
            // Extract the array name
            let name = extract_identifier(line, "XAie_StrmSwPortMap");
            if let Some(name) = name {
                let mut entries = Vec::new();
                let mut depth = 0;
                let mut current_port_type: Option<String> = None;
                let mut current_port_num: Option<u8> = None;

                // Advance to opening brace
                while i < lines.len() && !lines[i].contains('{') {
                    i += 1;
                }
                if i < lines.len() {
                    depth = 1;
                    i += 1;
                }

                while i < lines.len() && depth > 0 {
                    let l = lines[i].trim();
                    for ch in l.chars() {
                        match ch {
                            '{' => depth += 1,
                            '}' => {
                                depth -= 1;
                                if depth == 1 {
                                    // End of one entry
                                    if let (Some(pt), Some(pn)) =
                                        (current_port_type.take(), current_port_num.take())
                                    {
                                        entries.push((pt, pn));
                                    }
                                }
                            }
                            _ => {}
                        }
                    }

                    if let Some(val) = extract_field_value(l, "PortType") {
                        current_port_type = Some(val);
                    }
                    if let Some(val) = extract_field_value(l, "PortNum") {
                        current_port_num = parse_numeric_value(&val).map(|v| v as u8);
                    }

                    i += 1;
                }

                results.push(PortMapData { name, entries });
            }
        }
        i += 1;
    }

    results
}

/// Generic parser for C struct initializers of a given type name.
/// Returns Vec of (instance_name, field_map).
fn parse_struct_initializers(
    text: &str,
    type_name: &str,
) -> Vec<(String, HashMap<String, String>)> {
    let mut results = Vec::new();
    let lines: Vec<&str> = text.lines().collect();
    let mut i = 0;

    while i < lines.len() {
        let line = lines[i].trim();
        // Look for: static const <type_name> <name> =
        if line.contains(type_name) && line.contains('=') && !line.contains("[]") && !line.contains('(') {
            let name = extract_identifier(line, type_name);
            if let Some(name) = name {
                let mut fields = HashMap::new();
                let mut depth = 0;

                // Advance to opening brace
                while i < lines.len() && !lines[i].contains('{') {
                    i += 1;
                }
                if i < lines.len() {
                    depth = 1;
                    i += 1;
                }

                // Only parse top-level fields (depth == 1)
                while i < lines.len() && depth > 0 {
                    let l = lines[i].trim();
                    for ch in l.chars() {
                        match ch {
                            '{' => depth += 1,
                            '}' => depth -= 1,
                            _ => {}
                        }
                    }

                    // Only extract fields at depth 1 (top-level struct fields)
                    if depth == 1 && l.starts_with('.') {
                        if let Some((field_name, value)) = parse_field_assignment(l) {
                            fields.insert(field_name, value);
                        }
                    }

                    i += 1;
                }

                results.push((name, fields));
            }
        }
        i += 1;
    }

    results
}

/// Extract identifier name after the type name in a declaration line.
fn extract_identifier(line: &str, type_name: &str) -> Option<String> {
    let idx = line.find(type_name)? + type_name.len();
    let rest = line[idx..].trim();
    let ident: String = rest
        .chars()
        .take_while(|c| c.is_ascii_alphanumeric() || *c == '_')
        .collect();
    if ident.is_empty() {
        None
    } else {
        Some(ident)
    }
}

/// Parse ".FieldName = value," from a line.
fn parse_field_assignment(line: &str) -> Option<(String, String)> {
    let line = line.trim();
    if !line.starts_with('.') {
        return None;
    }
    let eq_idx = line.find('=')?;
    let field_name = line[1..eq_idx].trim().to_string();

    // Skip sub-field assignments like ".NxtBd.Idx = ..."
    if field_name.contains('.') {
        return None;
    }

    let value_part = line[eq_idx + 1..].trim();
    // Strip trailing comma and any trailing comment
    let value = value_part
        .trim_end_matches(',')
        .trim()
        .to_string();

    // Skip function pointer values
    if value.starts_with('&') || value.contains("((void *)0)") {
        return None;
    }

    Some((field_name, value))
}

/// Extract a field value from a line like ".FieldName = value,"
fn extract_field_value(line: &str, field: &str) -> Option<String> {
    let pattern = format!(".{} =", field);
    if let Some(idx) = line.find(&pattern) {
        let after = line[idx + pattern.len()..].trim();
        let value: String = after
            .chars()
            .take_while(|c| *c != ',' && *c != '}')
            .collect();
        Some(value.trim().to_string())
    } else {
        None
    }
}

/// Parse a numeric value string (hex or decimal, optional U suffix).
fn parse_numeric_value(s: &str) -> Option<u32> {
    let s = s.trim().trim_end_matches('U').trim_end_matches('u');
    if s.starts_with("0x") || s.starts_with("0X") {
        u32::from_str_radix(&s[2..], 16).ok()
    } else if s.starts_with('-') {
        // Handle negative values (e.g., LockValLowerBound = -64)
        s.parse::<i32>().ok().map(|v| v as u32)
    } else {
        s.parse::<u32>().ok()
    }
}

/// Get a u32 field from a DmaModData or LockModData field map.
fn get_field(fields: &HashMap<String, String>, name: &str, struct_name: &str) -> u32 {
    let val_str = fields
        .get(name)
        .unwrap_or_else(|| panic!("Field '{}' not found in {}", name, struct_name));
    parse_numeric_value(val_str)
        .unwrap_or_else(|| panic!("Cannot parse '{}' = '{}' in {}", name, val_str, struct_name))
}

/// Map an aie-rt struct instance name to a Rust module name.
fn dma_mod_name(name: &str) -> &str {
    if name.contains("MemTile") {
        "memtile_dma"
    } else if name.contains("Shim") {
        "shim_dma"
    } else {
        "compute_dma"
    }
}

fn lock_mod_name(name: &str) -> &str {
    if name.contains("MemTile") {
        "memtile_locks"
    } else if name.contains("Shim") {
        "shim_locks"
    } else {
        "compute_locks"
    }
}

fn port_map_rust_name(name: &str) -> &str {
    if name.contains("MemTile") && name.contains("Master") {
        "MEMTILE_MASTER_PORTS"
    } else if name.contains("MemTile") && name.contains("Slave") {
        "MEMTILE_SLAVE_PORTS"
    } else if name.contains("Shim") && name.contains("Master") {
        "SHIM_MASTER_PORTS"
    } else if name.contains("Shim") && name.contains("Slave") {
        "SHIM_SLAVE_PORTS"
    } else if name.contains("Master") {
        "COMPUTE_MASTER_PORTS"
    } else {
        "COMPUTE_SLAVE_PORTS"
    }
}

// -- Code generation functions --

fn gen_aiert_dma(modules: &[DmaModData], out_dir: &Path) {
    let mut out = gen_header("aie-rt xaiemlgbl_reginit.c DMA modules");

    for m in modules {
        let mod_name = dma_mod_name(&m.name);
        writeln!(out, "/// DMA constants from aie-rt {} ({})", m.name, mod_name).unwrap();
        writeln!(out, "pub mod {} {{", mod_name).unwrap();
        writeln!(out, "    pub const BD_BASE: u32 = {:#010X};", get_field(&m.fields, "BaseAddr", &m.name)).unwrap();
        writeln!(out, "    pub const BD_STRIDE: u32 = {:#06X};", get_field(&m.fields, "IdxOffset", &m.name)).unwrap();
        writeln!(out, "    pub const NUM_BDS: usize = {};", get_field(&m.fields, "NumBds", &m.name)).unwrap();
        writeln!(out, "    pub const NUM_LOCKS: usize = {};", get_field(&m.fields, "NumLocks", &m.name)).unwrap();
        writeln!(out, "    pub const START_QUEUE_BASE: u32 = {:#010X};", get_field(&m.fields, "StartQueueBase", &m.name)).unwrap();
        writeln!(out, "    pub const CH_CTRL_BASE: u32 = {:#010X};", get_field(&m.fields, "ChCtrlBase", &m.name)).unwrap();
        writeln!(out, "    pub const NUM_CHANNELS: usize = {};", get_field(&m.fields, "NumChannels", &m.name)).unwrap();
        writeln!(out, "    pub const CH_STRIDE: u32 = {:#06X};", get_field(&m.fields, "ChIdxOffset", &m.name)).unwrap();
        writeln!(out, "    pub const CH_STATUS_BASE: u32 = {:#010X};", get_field(&m.fields, "ChStatusBase", &m.name)).unwrap();
        writeln!(out, "    pub const CH_STATUS_STRIDE: u32 = {:#06X};", get_field(&m.fields, "ChStatusOffset", &m.name)).unwrap();
        writeln!(out, "    pub const NUM_ADDR_DIM: usize = {};", get_field(&m.fields, "NumAddrDim", &m.name)).unwrap();
        writeln!(out, "}}\n").unwrap();
    }

    fs::write(out_dir.join("gen_aiert_dma.rs"), out).unwrap();
}

fn gen_aiert_locks(modules: &[LockModData], out_dir: &Path) {
    let mut out = gen_header("aie-rt xaiemlgbl_reginit.c Lock modules");

    for m in modules {
        let mod_name = lock_mod_name(&m.name);
        writeln!(out, "/// Lock constants from aie-rt {} ({})", m.name, mod_name).unwrap();
        writeln!(out, "pub mod {} {{", mod_name).unwrap();
        writeln!(out, "    pub const BASE: u32 = {:#010X};", get_field(&m.fields, "BaseAddr", &m.name)).unwrap();
        writeln!(out, "    pub const NUM_LOCKS: usize = {};", get_field(&m.fields, "NumLocks", &m.name)).unwrap();
        writeln!(out, "    pub const LOCK_ID_STRIDE: u32 = {:#06X};", get_field(&m.fields, "LockIdOff", &m.name)).unwrap();
        writeln!(out, "    pub const REL_ACQ_OFFSET: u32 = {:#06X};", get_field(&m.fields, "RelAcqOff", &m.name)).unwrap();
        writeln!(out, "    pub const LOCK_VAL_OFFSET: u32 = {:#06X};", get_field(&m.fields, "LockValOff", &m.name)).unwrap();
        writeln!(out, "    pub const VAL_UPPER_BOUND: i32 = {};", get_field(&m.fields, "LockValUpperBound", &m.name) as i32).unwrap();
        writeln!(out, "    pub const VAL_LOWER_BOUND: i32 = {};", get_field(&m.fields, "LockValLowerBound", &m.name) as i32).unwrap();
        writeln!(out, "    pub const SET_VAL_BASE: u32 = {:#010X};", get_field(&m.fields, "LockSetValBase", &m.name)).unwrap();
        writeln!(out, "    pub const SET_VAL_STRIDE: u32 = {:#06X};", get_field(&m.fields, "LockSetValOff", &m.name)).unwrap();
        writeln!(out, "}}\n").unwrap();
    }

    fs::write(out_dir.join("gen_aiert_locks.rs"), out).unwrap();
}

fn gen_aiert_ports(port_maps: &[PortMapData], out_dir: &Path) {
    let mut out = gen_header("aie-rt xaiemlgbl_reginit.c stream switch port maps");

    // Port type enum
    writeln!(out, "/// Port type enum matching aie-rt XAie_StrmSwPortType.").unwrap();
    writeln!(out, "#[derive(Debug, Clone, Copy, PartialEq, Eq)]").unwrap();
    writeln!(out, "#[repr(u8)]").unwrap();
    writeln!(out, "pub enum AieRtPortType {{").unwrap();
    writeln!(out, "    Core = 0, Dma = 1, Ctrl = 2, Fifo = 3,").unwrap();
    writeln!(out, "    South = 4, West = 5, North = 6, East = 7, Trace = 8,").unwrap();
    writeln!(out, "}}\n").unwrap();

    for pm in port_maps {
        let const_name = port_map_rust_name(&pm.name);
        writeln!(out, "/// {} (from aie-rt {})", const_name, pm.name).unwrap();
        writeln!(
            out,
            "pub const {}: &[(AieRtPortType, u8)] = &[",
            const_name
        )
        .unwrap();

        for (i, (port_type, port_num)) in pm.entries.iter().enumerate() {
            let rust_variant = match port_type.as_str() {
                "CORE" => "Core",
                "DMA" => "Dma",
                "CTRL" => "Ctrl",
                "FIFO" => "Fifo",
                "SOUTH" => "South",
                "WEST" => "West",
                "NORTH" => "North",
                "EAST" => "East",
                "TRACE" => "Trace",
                other => panic!("Unknown port type '{}' in {}", other, pm.name),
            };
            writeln!(
                out,
                "    (AieRtPortType::{}, {}), // {}",
                rust_variant, port_num, i
            )
            .unwrap();
        }

        writeln!(out, "];\n").unwrap();
    }

    fs::write(out_dir.join("gen_aiert_ports.rs"), out).unwrap();
}

/// Write stub files when aie-rt is not available.
fn write_aiert_stubs(out_dir: &Path) {
    let dma_stub = "\
// aie-rt not available -- stub file.
pub mod memtile_dma {
    pub const BD_BASE: u32 = 0x000A0000;
    pub const BD_STRIDE: u32 = 0x0020;
    pub const NUM_BDS: usize = 48;
    pub const NUM_LOCKS: usize = 192;
    pub const START_QUEUE_BASE: u32 = 0x000A0604;
    pub const CH_CTRL_BASE: u32 = 0x000A0600;
    pub const NUM_CHANNELS: usize = 6;
    pub const CH_STRIDE: u32 = 0x0008;
    pub const CH_STATUS_BASE: u32 = 0x000A0660;
    pub const CH_STATUS_STRIDE: u32 = 0x0020;
    pub const NUM_ADDR_DIM: usize = 4;
}
pub mod compute_dma {
    pub const BD_BASE: u32 = 0x0001D000;
    pub const BD_STRIDE: u32 = 0x0020;
    pub const NUM_BDS: usize = 16;
    pub const NUM_LOCKS: usize = 16;
    pub const START_QUEUE_BASE: u32 = 0x0001DE04;
    pub const CH_CTRL_BASE: u32 = 0x0001DE00;
    pub const NUM_CHANNELS: usize = 2;
    pub const CH_STRIDE: u32 = 0x0008;
    pub const CH_STATUS_BASE: u32 = 0x0001DF00;
    pub const CH_STATUS_STRIDE: u32 = 0x0010;
    pub const NUM_ADDR_DIM: usize = 3;
}
pub mod shim_dma {
    pub const BD_BASE: u32 = 0x0001D000;
    pub const BD_STRIDE: u32 = 0x0020;
    pub const NUM_BDS: usize = 16;
    pub const NUM_LOCKS: usize = 16;
    pub const START_QUEUE_BASE: u32 = 0x0001D204;
    pub const CH_CTRL_BASE: u32 = 0x0001D200;
    pub const NUM_CHANNELS: usize = 2;
    pub const CH_STRIDE: u32 = 0x0008;
    pub const CH_STATUS_BASE: u32 = 0x0001D220;
    pub const CH_STATUS_STRIDE: u32 = 0x0008;
    pub const NUM_ADDR_DIM: usize = 3;
}
";

    let locks_stub = "\
// aie-rt not available -- stub file.
pub mod compute_locks {
    pub const BASE: u32 = 0x00040000;
    pub const NUM_LOCKS: usize = 16;
    pub const LOCK_ID_STRIDE: u32 = 0x0400;
    pub const REL_ACQ_OFFSET: u32 = 0x0200;
    pub const LOCK_VAL_OFFSET: u32 = 0x0004;
    pub const VAL_UPPER_BOUND: i32 = 63;
    pub const VAL_LOWER_BOUND: i32 = -64;
    pub const SET_VAL_BASE: u32 = 0x0001F000;
    pub const SET_VAL_STRIDE: u32 = 0x0010;
}
pub mod shim_locks {
    pub const BASE: u32 = 0x00040000;
    pub const NUM_LOCKS: usize = 16;
    pub const LOCK_ID_STRIDE: u32 = 0x0400;
    pub const REL_ACQ_OFFSET: u32 = 0x0200;
    pub const LOCK_VAL_OFFSET: u32 = 0x0004;
    pub const VAL_UPPER_BOUND: i32 = 63;
    pub const VAL_LOWER_BOUND: i32 = -64;
    pub const SET_VAL_BASE: u32 = 0x00014000;
    pub const SET_VAL_STRIDE: u32 = 0x0010;
}
pub mod memtile_locks {
    pub const BASE: u32 = 0x000D0000;
    pub const NUM_LOCKS: usize = 64;
    pub const LOCK_ID_STRIDE: u32 = 0x0400;
    pub const REL_ACQ_OFFSET: u32 = 0x0200;
    pub const LOCK_VAL_OFFSET: u32 = 0x0004;
    pub const VAL_UPPER_BOUND: i32 = 63;
    pub const VAL_LOWER_BOUND: i32 = -64;
    pub const SET_VAL_BASE: u32 = 0x000C0000;
    pub const SET_VAL_STRIDE: u32 = 0x0010;
}
";

    // Stub for ports is more involved but still needed for compilation
    let ports_stub = "\
// aie-rt not available -- stub file.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum AieRtPortType {
    Core = 0, Dma = 1, Ctrl = 2, Fifo = 3,
    South = 4, West = 5, North = 6, East = 7, Trace = 8,
}

pub const COMPUTE_MASTER_PORTS: &[(AieRtPortType, u8)] = &[];
pub const COMPUTE_SLAVE_PORTS: &[(AieRtPortType, u8)] = &[];
pub const SHIM_MASTER_PORTS: &[(AieRtPortType, u8)] = &[];
pub const SHIM_SLAVE_PORTS: &[(AieRtPortType, u8)] = &[];
pub const MEMTILE_MASTER_PORTS: &[(AieRtPortType, u8)] = &[];
pub const MEMTILE_SLAVE_PORTS: &[(AieRtPortType, u8)] = &[];
";

    fs::write(out_dir.join("gen_aiert_dma.rs"), dma_stub).unwrap();
    fs::write(out_dir.join("gen_aiert_locks.rs"), locks_stub).unwrap();
    fs::write(out_dir.join("gen_aiert_ports.rs"), ports_stub).unwrap();
}
