//! Architecture configuration trait and data-driven implementations.
//!
//! This module provides a trait-based abstraction for NPU architecture parameters.
//! The primary implementation, `ModelConfig`, derives its values from mlir-aie's
//! `AIETargetModel` (parsed from `aie-device-models.json` at build time by the
//! `xdna-archspec` crate, and at runtime for non-primary devices like npu2).
//!
//! Stream switch port layouts and ranges (AM025 register-level data not modeled
//! by mlir-aie) are sourced from `crate::arch` (generated by build.rs).
//!
//! # Example
//!
//! ```ignore
//! use xdna_emu::device::arch_config::{ArchConfig, ModelConfig};
//! use std::sync::Arc;
//!
//! let arch: Arc<dyn ArchConfig> = ModelConfig::npu1();
//! assert_eq!(arch.columns(), 5);
//! assert_eq!(arch.rows(), 6);
//! assert!(arch.is_shim_tile(0, 0));
//! assert!(arch.is_mem_tile(0, 1));
//! assert!(arch.is_compute_tile(0, 2));
//! ```

use super::tile::TileType;
use std::sync::{Arc, LazyLock};

/// Architecture configuration trait for NPU variants.
///
/// Implementations of this trait encapsulate all architecture-specific parameters:
/// - Array dimensions (columns, rows)
/// - Tile type classification (which coordinates are shim/memtile/compute)
/// - Memory sizes per tile type
/// - DMA configuration (channels, buffer descriptors)
/// - Stream switch port layouts
///
/// This enables the emulator to support multiple NPU architectures without
/// hardcoded checks like `row == 0` scattered throughout the code.
pub trait ArchConfig: Send + Sync + std::fmt::Debug {
    // ========================================================================
    // Array Dimensions
    // ========================================================================

    /// Get the number of columns in the tile array.
    fn columns(&self) -> u8;

    /// Get the number of rows in the tile array.
    fn rows(&self) -> u8;

    // ========================================================================
    // Tile Type Classification
    // ========================================================================

    /// Get the tile type at the given coordinates.
    fn tile_type(&self, col: u8, row: u8) -> TileType;

    /// Check if a tile position is valid.
    fn is_valid_tile(&self, col: u8, row: u8) -> bool {
        col < self.columns() && row < self.rows()
    }

    /// Check if a tile is a shim tile (DDR interface).
    fn is_shim_tile(&self, col: u8, row: u8) -> bool {
        self.tile_type(col, row) == TileType::Shim
    }

    /// Check if a tile is a memory tile (large shared memory).
    fn is_mem_tile(&self, col: u8, row: u8) -> bool {
        self.tile_type(col, row) == TileType::MemTile
    }

    /// Check if a tile is a compute tile (has AIE core).
    fn is_compute_tile(&self, col: u8, row: u8) -> bool {
        self.tile_type(col, row) == TileType::Compute
    }

    // ========================================================================
    // Memory Configuration
    // ========================================================================

    /// Get the data memory size for a tile type.
    fn data_memory_size(&self, tile_type: TileType) -> usize;

    /// Get the program memory size for a tile type.
    /// Only compute tiles have program memory; returns 0 for others.
    fn program_memory_size(&self, tile_type: TileType) -> usize;

    /// Get the number of locks for a tile type.
    fn lock_count(&self, tile_type: TileType) -> usize;

    /// Get the maximum value storable in a lock register.
    /// For AIE2 this is 63 (6-bit unsigned state).
    fn max_lock_value(&self) -> u32;

    // ========================================================================
    // DMA Configuration
    // ========================================================================

    /// Get the number of S2MM (stream-to-memory) DMA channels.
    fn dma_s2mm_channels(&self, tile_type: TileType) -> usize;

    /// Get the number of MM2S (memory-to-stream) DMA channels.
    fn dma_mm2s_channels(&self, tile_type: TileType) -> usize;

    /// Get the total number of DMA channels.
    fn dma_total_channels(&self, tile_type: TileType) -> usize {
        self.dma_s2mm_channels(tile_type) + self.dma_mm2s_channels(tile_type)
    }

    /// Get the number of DMA buffer descriptors.
    fn dma_bd_count(&self, tile_type: TileType) -> usize;

    // ========================================================================
    // Stream Switch Port Layouts
    // ========================================================================

    /// Get the master port layout for a tile type.
    /// Returns an array of port type identifiers.
    fn master_ports(&self, tile_type: TileType) -> &'static [u8];

    /// Get the slave port layout for a tile type.
    fn slave_ports(&self, tile_type: TileType) -> &'static [u8];

    /// Get the range of north-facing master ports (start, end inclusive).
    fn north_master_range(&self, tile_type: TileType) -> (u8, u8);

    /// Get the range of south-facing master ports (start, end inclusive).
    fn south_master_range(&self, tile_type: TileType) -> (u8, u8);

    /// Get the range of north-facing slave ports (start, end inclusive).
    fn north_slave_range(&self, tile_type: TileType) -> (u8, u8);

    /// Get the range of south-facing slave ports (start, end inclusive).
    fn south_slave_range(&self, tile_type: TileType) -> (u8, u8);

    // ========================================================================
    // Architecture Name
    // ========================================================================

    /// Get the architecture name for display.
    fn name(&self) -> &'static str;
}

// ============================================================================
// Data-driven configuration from mlir-aie DeviceModel
// ============================================================================

/// Cached device model data, pre-extracted into per-tile-type lookup tables
/// for fast access during emulation. This avoids HashMap lookups on every
/// ArchConfig method call.
#[derive(Debug, Clone)]
struct TileTypeParams {
    /// Data memory size in bytes.
    data_memory_size: usize,
    /// Number of locks.
    num_locks: usize,
    /// Number of DMA buffer descriptors.
    num_bds: usize,
    /// Number of DMA S2MM (slave/inbound) channels.
    dma_s2mm: usize,
    /// Number of DMA MM2S (master/outbound) channels.
    dma_mm2s: usize,
}

/// Architecture configuration backed by mlir-aie's `DeviceModel`.
///
/// All device-configuration values (dimensions, memory sizes, lock/BD counts,
/// DMA channels) come from the parsed model. Stream switch port layouts and
/// ranges (AM025 register-level data) come from `crate::arch` (generated by
/// build.rs from AM025 JSON) since mlir-aie does not model per-port-index assignments.
///
/// `ModelConfig` replaces the previous `Aie2Config` and `Aie2pConfig` structs.
/// Use `ModelConfig::npu1()` or `ModelConfig::npu2()` for convenience.
#[derive(Debug, Clone)]
pub struct ModelConfig {
    /// Number of tile columns (from model, includes +1 for the emulator's
    /// column 0 convention if needed).
    columns: u8,
    /// Number of tile rows.
    rows: u8,
    /// Number of memory tile rows (determines which rows are mem tiles).
    num_mem_tile_rows: u32,
    /// Maximum lock value (from model, e.g. 63 for AIE2).
    max_lock_value: u32,
    /// Per-tile-type parameters, pre-extracted from the model.
    core_params: TileTypeParams,
    mem_tile_params: TileTypeParams,
    shim_params: TileTypeParams,
    /// Architecture name for display (leaked &'static str).
    arch_name: &'static str,
}

/// Pre-loaded device models from the archspec JSON, parsed once at first use.
///
/// Uses the same `xdna_archspec::device_model` parser that build.rs uses for
/// npu1 at compile time, so the JSON is only ever parsed by one code path.
/// Keyed by device name (e.g. "npu2").
pub(crate) static ARCHSPEC_MODELS: LazyLock<std::collections::HashMap<String, crate::archspec::ArchModel>> =
    LazyLock::new(|| {
        let json_path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("tools/aie-device-models.json");
        xdna_archspec::device_model::extract_device_models(&json_path)
            .unwrap_or_else(|e| panic!(
                "Failed to load device models from {}: {}. \
                 Run: python3 tools/aie-device-dump.py > tools/aie-device-models.json",
                json_path.display(), e
            ))
    });

impl ModelConfig {
    /// Create a ModelConfig from an `crate::archspec::ArchModel`.
    ///
    /// This is the single conversion path from the archspec JSON data (whether
    /// loaded at build time or runtime) into the emulator's `ArchConfig`.
    ///
    /// Adds 1 to the model's column count to match the emulator's convention
    /// where column 0 is the leftmost shim column. mlir-aie counts only
    /// "compute columns" (e.g. 4 for NPU1), while the emulator uses 5
    /// (columns 0-4).
    pub fn from_arch_model(model: &crate::archspec::ArchModel, arch_name: &'static str) -> Self {
        use crate::archspec::TileKind;

        // Helper: extract DMA slave/master counts from a tile's port list.
        // Shim tiles use shim_mux_ports; others use switchbox_ports.
        let dma_channels = |tile: &xdna_archspec::types::TileTypeModel| -> (usize, usize) {
            let ports = match tile.kind {
                TileKind::ShimNoc | TileKind::ShimPl => &tile.shim_mux_ports,
                _ => &tile.switchbox_ports,
            };
            ports.iter()
                .find(|p| p.bundle == "DMA")
                .map(|p| (p.slaves as usize, p.masters as usize))
                .unwrap_or((2, 2)) // conservative fallback
        };

        let compute = model.tile_types.iter().find(|t| t.kind == TileKind::Compute)
            .expect("core tile type missing from device model JSON; regenerate with aie-device-dump.py");
        let (compute_s2mm, compute_mm2s) = dma_channels(compute);
        let compute_mem_size = compute.memory.as_ref()
            .map(|m| m.size_bytes as usize)
            .unwrap_or(65536); // AIE2 default: 64KB
        let core_params = TileTypeParams {
            data_memory_size: compute_mem_size,
            num_locks: *compute.instances.locks.value() as usize,
            num_bds: *compute.instances.bds.value() as usize,
            dma_s2mm: compute_s2mm,
            dma_mm2s: compute_mm2s,
        };

        let memtile = model.tile_types.iter().find(|t| t.kind == TileKind::Mem)
            .expect("mem_tile tile type missing from device model JSON; regenerate with aie-device-dump.py");
        let (mem_s2mm, mem_mm2s) = dma_channels(memtile);
        let mem_tile_size = memtile.memory.as_ref()
            .map(|m| m.size_bytes as usize)
            .unwrap_or(524288); // AIE2 default: 512KB
        let mem_tile_params = TileTypeParams {
            data_memory_size: mem_tile_size,
            num_locks: *memtile.instances.locks.value() as usize,
            num_bds: *memtile.instances.bds.value() as usize,
            dma_s2mm: mem_s2mm,
            dma_mm2s: mem_mm2s,
        };

        let shim = model.tile_types.iter().find(|t| t.kind == TileKind::ShimNoc)
            .expect("shim_noc tile type missing from device model JSON; regenerate with aie-device-dump.py");
        let (shim_s2mm, shim_mm2s) = dma_channels(shim);
        let shim_params = TileTypeParams {
            // Shim tiles have no local data memory (the device model
            // reports address space size, not physical SRAM).
            data_memory_size: 0,
            num_locks: *shim.instances.locks.value() as usize,
            num_bds: *shim.instances.bds.value() as usize,
            dma_s2mm: shim_s2mm,
            dma_mm2s: shim_mm2s,
        };

        let topo = model.array_topology.as_ref()
            .expect("array topology missing from device model JSON");
        let max_lock_value = model.device_constants.as_ref()
            .map(|dc| dc.max_lock_value)
            .unwrap_or(63); // AIE2/AIE2P default

        Self {
            // The emulator adds 1 column to the model's count for the
            // column 0 convention used in CDO addressing.
            columns: topo.columns + 1,
            rows: topo.rows,
            num_mem_tile_rows: topo.num_mem_tile_rows as u32,
            max_lock_value,
            core_params,
            mem_tile_params,
            shim_params,
            arch_name,
        }
    }

    /// Get the parameters for a given tile type.
    fn params(&self, tile_type: TileType) -> &TileTypeParams {
        match tile_type {
            TileType::Shim => &self.shim_params,
            TileType::MemTile => &self.mem_tile_params,
            TileType::Compute => &self.core_params,
        }
    }

    /// Create the NPU1 (Phoenix/HawkPoint, AIE2) configuration.
    ///
    /// All values come from compile-time constants in `crate::arch::*`,
    /// generated by build.rs from the same device model JSON that was
    /// previously parsed at runtime. No JSON I/O needed.
    pub fn npu1() -> Arc<dyn ArchConfig> {
        use crate::arch;
        Arc::new(Self {
            // The emulator adds 1 to the device model's column count for
            // the column 0 convention used in CDO addressing.
            columns: arch::COLUMNS + 1,
            rows: arch::ROWS,
            num_mem_tile_rows: arch::NUM_MEM_TILE_ROWS as u32,
            max_lock_value: arch::MAX_LOCK_VALUE as u32,
            core_params: TileTypeParams {
                data_memory_size: arch::compute::MEMORY_SIZE as usize,
                num_locks: arch::compute::NUM_LOCKS as usize,
                num_bds: arch::compute::NUM_BDS as usize,
                dma_s2mm: arch::compute::NUM_DMA_CHANNELS as usize,
                dma_mm2s: arch::compute::NUM_DMA_CHANNELS as usize,
            },
            mem_tile_params: TileTypeParams {
                data_memory_size: arch::memtile::MEMORY_SIZE as usize,
                num_locks: arch::memtile::NUM_LOCKS as usize,
                num_bds: arch::memtile::NUM_BDS as usize,
                dma_s2mm: arch::memtile::NUM_DMA_CHANNELS as usize,
                dma_mm2s: arch::memtile::NUM_DMA_CHANNELS as usize,
            },
            shim_params: TileTypeParams {
                // Shim tiles have no local data memory (the device model
                // reports address space size, not physical SRAM).
                data_memory_size: 0,
                num_locks: arch::shim::NUM_LOCKS as usize,
                num_bds: arch::shim::NUM_BDS as usize,
                dma_s2mm: arch::shim::NUM_DMA_CHANNELS as usize,
                dma_mm2s: arch::shim::NUM_DMA_CHANNELS as usize,
            },
            arch_name: "AIE2 (NPU1 - Phoenix/HawkPoint)",
        })
    }

    /// Create the NPU2 (Strix Point, AIE2P) configuration.
    ///
    /// Loads from the pre-generated device model JSON via the archspec parser.
    pub fn npu2() -> Arc<dyn ArchConfig> {
        let model = ARCHSPEC_MODELS.get("npu2")
            .expect("npu2 device not found in device model JSON");
        Arc::new(Self::from_arch_model(model, "AIE2P (NPU2+ - Strix/Krackan)"))
    }

    /// Create the VC2802 (Versal AIE2) configuration for aiesimulator validation.
    ///
    /// VC2802 is the 38-column x 11-row AIE2 array that aiesimulator uses for
    /// all AIE2 targets. Same silicon as NPU1 tiles, just a larger array.
    pub fn xcve2802() -> Arc<dyn ArchConfig> {
        let model = ARCHSPEC_MODELS.get("xcve2802")
            .expect("xcve2802 device not found in device model JSON; add to tools/aie-device-models.json");
        Arc::new(Self::from_arch_model(model, "AIE2 (VC2802 - Versal, aiesim validation)"))
    }
}

impl ArchConfig for ModelConfig {
    fn columns(&self) -> u8 {
        self.columns
    }

    fn rows(&self) -> u8 {
        self.rows
    }

    fn tile_type(&self, _col: u8, row: u8) -> TileType {
        match row {
            0 => TileType::Shim,
            r if r <= self.num_mem_tile_rows as u8 => TileType::MemTile,
            _ => TileType::Compute,
        }
    }

    fn data_memory_size(&self, tile_type: TileType) -> usize {
        self.params(tile_type).data_memory_size
    }

    fn program_memory_size(&self, tile_type: TileType) -> usize {
        match tile_type {
            // Program memory size from the architecture spec (originally
            // from the mlir-aie device model, validated at compile time).
            TileType::Compute => crate::arch::compute::PROGRAM_MEMORY_SIZE as usize,
            _ => 0,
        }
    }

    fn lock_count(&self, tile_type: TileType) -> usize {
        self.params(tile_type).num_locks
    }

    fn max_lock_value(&self) -> u32 {
        self.max_lock_value
    }

    fn dma_s2mm_channels(&self, tile_type: TileType) -> usize {
        self.params(tile_type).dma_s2mm
    }

    fn dma_mm2s_channels(&self, tile_type: TileType) -> usize {
        self.params(tile_type).dma_mm2s
    }

    fn dma_bd_count(&self, tile_type: TileType) -> usize {
        self.params(tile_type).num_bds
    }

    // Stream switch port layouts are AM025 register-level data. mlir-aie
    // only provides port *counts* per bundle, not per-port-index type
    // assignments. These arrays are generated by build.rs into crate::arch.
    //
    // When AIE2P diverges in port layout, we'll add AIE2P-specific arrays
    // and select based on architecture.

    fn master_ports(&self, tile_type: TileType) -> &'static [u8] {
        match tile_type {
            TileType::Shim => crate::arch::SHIM_MASTER_PORTS,
            TileType::MemTile => crate::arch::MEMTILE_MASTER_PORTS,
            TileType::Compute => crate::arch::COMPUTE_MASTER_PORTS,
        }
    }

    fn slave_ports(&self, tile_type: TileType) -> &'static [u8] {
        match tile_type {
            TileType::Shim => crate::arch::SHIM_SLAVE_PORTS,
            TileType::MemTile => crate::arch::MEMTILE_SLAVE_PORTS,
            TileType::Compute => crate::arch::COMPUTE_SLAVE_PORTS,
        }
    }

    fn north_master_range(&self, tile_type: TileType) -> (u8, u8) {
        use crate::arch::stream_switch::*;
        match tile_type {
            TileType::Shim => (shim::NORTH_MASTER_START, shim::NORTH_MASTER_END),
            TileType::MemTile => (mem_tile::NORTH_MASTER_START, mem_tile::NORTH_MASTER_END),
            TileType::Compute => (compute::NORTH_MASTER_START, compute::NORTH_MASTER_END),
        }
    }

    fn south_master_range(&self, tile_type: TileType) -> (u8, u8) {
        use crate::arch::stream_switch::*;
        match tile_type {
            TileType::Shim => (0, 0),
            TileType::MemTile => (mem_tile::SOUTH_MASTER_START, mem_tile::SOUTH_MASTER_END),
            TileType::Compute => (compute::SOUTH_MASTER_START, compute::SOUTH_MASTER_END),
        }
    }

    fn north_slave_range(&self, tile_type: TileType) -> (u8, u8) {
        use crate::arch::stream_switch::*;
        match tile_type {
            TileType::Shim => (shim::NORTH_SLAVE_START, shim::NORTH_SLAVE_END),
            TileType::MemTile => (mem_tile::NORTH_SLAVE_START, mem_tile::NORTH_SLAVE_END),
            TileType::Compute => (compute::NORTH_SLAVE_START, compute::NORTH_SLAVE_END),
        }
    }

    fn south_slave_range(&self, tile_type: TileType) -> (u8, u8) {
        use crate::arch::stream_switch::*;
        match tile_type {
            TileType::Shim => (0, 0),
            TileType::MemTile => (mem_tile::SOUTH_SLAVE_START, mem_tile::SOUTH_SLAVE_END),
            TileType::Compute => (compute::SOUTH_SLAVE_START, compute::SOUTH_SLAVE_END),
        }
    }

    fn name(&self) -> &'static str {
        self.arch_name
    }
}

// ============================================================================
// Default Architecture
// ============================================================================

/// Get the default architecture configuration (NPU1 from mlir-aie model).
pub fn default_arch() -> Arc<dyn ArchConfig> {
    ModelConfig::npu1()
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    fn npu1_arch() -> Arc<dyn ArchConfig> {
        ModelConfig::npu1()
    }

    #[test]
    fn test_npu1_dimensions() {
        let arch = npu1_arch();
        assert_eq!(arch.columns(), 5);
        assert_eq!(arch.rows(), 6);
    }

    #[test]
    fn test_npu1_tile_classification() {
        let arch = npu1_arch();

        // Shim tiles (row 0)
        for col in 0..5 {
            assert!(arch.is_shim_tile(col, 0), "({}, 0) should be shim", col);
            assert_eq!(arch.tile_type(col, 0), TileType::Shim);
        }

        // Mem tiles (row 1)
        for col in 0..5 {
            assert!(arch.is_mem_tile(col, 1), "({}, 1) should be memtile", col);
            assert_eq!(arch.tile_type(col, 1), TileType::MemTile);
        }

        // Compute tiles (rows 2-5)
        for col in 0..5 {
            for row in 2..6 {
                assert!(
                    arch.is_compute_tile(col, row),
                    "({}, {}) should be compute",
                    col,
                    row
                );
                assert_eq!(arch.tile_type(col, row), TileType::Compute);
            }
        }
    }

    #[test]
    fn test_npu1_memory_sizes() {
        let arch = npu1_arch();

        assert_eq!(arch.data_memory_size(TileType::Shim), 0);
        assert_eq!(arch.data_memory_size(TileType::MemTile), 512 * 1024);
        assert_eq!(arch.data_memory_size(TileType::Compute), 64 * 1024);

        assert_eq!(arch.program_memory_size(TileType::Shim), 0);
        assert_eq!(arch.program_memory_size(TileType::MemTile), 0);
        assert_eq!(arch.program_memory_size(TileType::Compute), 16 * 1024);
    }

    #[test]
    fn test_npu1_lock_counts() {
        let arch = npu1_arch();

        assert_eq!(arch.lock_count(TileType::Shim), 16);
        assert_eq!(arch.lock_count(TileType::MemTile), 64);
        assert_eq!(arch.lock_count(TileType::Compute), 16);
    }

    #[test]
    fn test_npu1_dma_config() {
        let arch = npu1_arch();

        // Compute tile: 2 S2MM + 2 MM2S = 4 channels
        assert_eq!(arch.dma_s2mm_channels(TileType::Compute), 2);
        assert_eq!(arch.dma_mm2s_channels(TileType::Compute), 2);
        assert_eq!(arch.dma_total_channels(TileType::Compute), 4);
        assert_eq!(arch.dma_bd_count(TileType::Compute), 16);

        // Mem tile: 6 S2MM + 6 MM2S = 12 channels
        assert_eq!(arch.dma_s2mm_channels(TileType::MemTile), 6);
        assert_eq!(arch.dma_mm2s_channels(TileType::MemTile), 6);
        assert_eq!(arch.dma_total_channels(TileType::MemTile), 12);
        assert_eq!(arch.dma_bd_count(TileType::MemTile), 48);
    }

    #[test]
    fn test_npu1_port_layouts() {
        let arch = npu1_arch();

        // Verify port counts match spec
        assert_eq!(arch.master_ports(TileType::Shim).len(), 22);
        assert_eq!(arch.slave_ports(TileType::Shim).len(), 23);

        assert_eq!(arch.master_ports(TileType::MemTile).len(), 17);
        assert_eq!(arch.slave_ports(TileType::MemTile).len(), 18);

        assert_eq!(arch.master_ports(TileType::Compute).len(), 23);
        assert_eq!(arch.slave_ports(TileType::Compute).len(), 25);
    }

    #[test]
    fn test_npu1_port_ranges() {
        use crate::arch::stream_switch::{compute, mem_tile, shim};

        let arch = npu1_arch();

        // Shim north masters: 12-17 (6 ports)
        let (start, end) = arch.north_master_range(TileType::Shim);
        assert_eq!((start, end), (12, 17));
        assert_eq!(end - start + 1, 6);

        // MemTile south masters: 7-10 (4 ports)
        let (start, end) = arch.south_master_range(TileType::MemTile);
        assert_eq!((start, end), (7, 10));

        // MemTile north masters: 11-16 (6 ports)
        let (start, end) = arch.north_master_range(TileType::MemTile);
        assert_eq!((start, end), (11, 16));

        // Validate E/W generated constants match AM025 port arrays
        // Compute tile
        assert_eq!(compute::EAST_MASTER_START, 19);
        assert_eq!(compute::EAST_MASTER_END, 22);
        assert_eq!(compute::EAST_SLAVE_START, 19);
        assert_eq!(compute::EAST_SLAVE_END, 22);
        assert_eq!(compute::WEST_MASTER_START, 9);
        assert_eq!(compute::WEST_MASTER_END, 12);
        assert_eq!(compute::WEST_SLAVE_START, 11);
        assert_eq!(compute::WEST_SLAVE_END, 14);

        // Shim tile
        assert_eq!(shim::EAST_MASTER_START, 18);
        assert_eq!(shim::EAST_MASTER_END, 21);
        assert_eq!(shim::EAST_SLAVE_START, 18);
        assert_eq!(shim::EAST_SLAVE_END, 21);
        assert_eq!(shim::WEST_MASTER_START, 8);
        assert_eq!(shim::WEST_MASTER_END, 11);
        assert_eq!(shim::WEST_SLAVE_START, 10);
        assert_eq!(shim::WEST_SLAVE_END, 13);
        assert_eq!(shim::SOUTH_MASTER_START, 2);
        assert_eq!(shim::SOUTH_MASTER_END, 7);
        assert_eq!(shim::SOUTH_SLAVE_START, 2);
        assert_eq!(shim::SOUTH_SLAVE_END, 9);

        // Verify port counts are consistent (END - START + 1)
        assert_eq!(compute::EAST_MASTER_END - compute::EAST_MASTER_START + 1, 4);
        assert_eq!(compute::WEST_MASTER_END - compute::WEST_MASTER_START + 1, 4);
        assert_eq!(shim::EAST_MASTER_END - shim::EAST_MASTER_START + 1, 4);
        assert_eq!(shim::WEST_MASTER_END - shim::WEST_MASTER_START + 1, 4);
        assert_eq!(shim::SOUTH_MASTER_END - shim::SOUTH_MASTER_START + 1, 6);

        // Verify MemTile has no E/W ports (constants should not exist)
        // This is verified structurally: mem_tile module has no EAST_*/WEST_* constants
        assert_eq!(mem_tile::SOUTH_MASTER_START, 7);
        assert_eq!(mem_tile::NORTH_MASTER_START, 11);
    }

    #[test]
    fn test_valid_tile_check() {
        let arch = npu1_arch();

        // Valid positions
        assert!(arch.is_valid_tile(0, 0));
        assert!(arch.is_valid_tile(4, 5));

        // Invalid positions
        assert!(!arch.is_valid_tile(5, 0)); // col out of range
        assert!(!arch.is_valid_tile(0, 6)); // row out of range
        assert!(!arch.is_valid_tile(10, 10));
    }

    #[test]
    fn test_default_arch() {
        let arch = default_arch();
        assert_eq!(arch.columns(), 5);
        assert_eq!(arch.rows(), 6);
        assert_eq!(arch.name(), "AIE2 (NPU1 - Phoenix/HawkPoint)");
    }

    #[test]
    fn test_model_config_is_send_sync() {
        fn assert_send_sync<T: Send + Sync>() {}
        assert_send_sync::<ModelConfig>();
    }

    #[test]
    fn test_npu2_dimensions() {
        let arch = ModelConfig::npu2();
        // NPU2 base has 8 compute columns + 1 = 9 total
        assert_eq!(arch.columns(), 9);
        assert_eq!(arch.rows(), 6);
    }

    #[test]
    fn test_vc2802_dimensions() {
        let arch = ModelConfig::xcve2802();
        // VC2802: 37 + 1 = 38 columns, 11 rows
        assert_eq!(arch.columns(), 38);
        assert_eq!(arch.rows(), 11);
    }

    #[test]
    fn test_vc2802_tile_classification() {
        let arch = ModelConfig::xcve2802();
        // Row 0: shim
        assert!(matches!(arch.tile_type(0, 0), TileType::Shim));
        assert!(matches!(arch.tile_type(7, 0), TileType::Shim));
        // Rows 1-2: memtile
        assert!(matches!(arch.tile_type(7, 1), TileType::MemTile));
        assert!(matches!(arch.tile_type(7, 2), TileType::MemTile));
        // Rows 3-10: compute
        assert!(matches!(arch.tile_type(7, 3), TileType::Compute));
        assert!(matches!(arch.tile_type(7, 10), TileType::Compute));
    }

    #[test]
    fn test_vc2802_tile_params_match_npu1() {
        // Same AIE2 silicon -- tile params should be identical
        let vc = ModelConfig::xcve2802();
        let npu = ModelConfig::npu1();
        // Compute tile memory
        assert_eq!(
            vc.data_memory_size(TileType::Compute),
            npu.data_memory_size(TileType::Compute)
        );
        // Lock counts
        assert_eq!(
            vc.lock_count(TileType::Compute),
            npu.lock_count(TileType::Compute)
        );
        // DMA channels
        assert_eq!(
            vc.dma_s2mm_channels(TileType::Compute),
            npu.dma_s2mm_channels(TileType::Compute)
        );
    }
}
