//! Device model validation against compile-time architecture constants.
//!
//! This module provides a runtime validation function that cross-checks the
//! `aie-device-models.json` file against the compile-time `xdna_archspec::aie2::*`
//! constants generated by `build.rs`. If the JSON is regenerated and values
//! drift from the expected hardware specification, validation catches it.
//!
//! # Design note
//!
//! The JSON file is parsed at build time by the `xdna-archspec` crate (see
//! `build.rs`) to produce the compile-time constants in `xdna_archspec::aie2`. This
//! module does NOT duplicate that parsing -- it imports `xdna_archspec` types
//! directly and uses the same parser for its tests and validation function.
//!
//! Historically this module contained serde `#[derive(Deserialize)]` structs
//! for the same JSON. Those were removed because they duplicated the archspec
//! parser. All runtime consumers now use `xdna_archspec::runtime` directly or
//! the compile-time `xdna_archspec::aie2::*` constants.

use xdna_archspec::types::ArchModel;

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

/// Errors from validating the device model JSON against expected constants.
#[derive(Debug)]
pub enum DeviceModelError {
    /// I/O or parse error reading or parsing the model.
    Parse(String),
    /// Validation error: parsed model doesn't match expected constants.
    Validation(String),
}

impl std::fmt::Display for DeviceModelError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            DeviceModelError::Parse(msg) => write!(f, "parse error: {}", msg),
            DeviceModelError::Validation(msg) => write!(f, "validation error: {}", msg),
        }
    }
}

impl std::error::Error for DeviceModelError {}

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

/// Validate that the NPU1 `ArchModel` (parsed from `aie-device-models.json`)
/// matches the compile-time `xdna_archspec::aie2::*` constants.
///
/// These constants are generated by `build.rs` from the same JSON, so a
/// mismatch indicates either a stale JSON file or a code-generation bug.
/// Mismatches are collected and returned together rather than panicking on
/// the first one.
pub fn validate_against_spec(model: &ArchModel) -> Result<(), DeviceModelError> {
    use xdna_archspec::types::TileKind;
    let mut mismatches = Vec::new();

    // Compare as i64 to handle mixed integer widths from archspec types
    // (u8, u32, u64) vs arch constants (usize).
    macro_rules! check {
        ($name:expr, $model_val:expr, $expected:expr) => {
            let model_val = $model_val as i64;
            let expected = $expected as i64;
            if model_val != expected {
                mismatches.push(format!("{}: model={}, expected={}", $name, model_val, expected));
            }
        };
    }

    use xdna_archspec::aie2 as arch;

    // --- Device constants ---
    if let Some(ref dc) = model.device_constants {
        check!("max_lock_value", dc.max_lock_value as i32, arch::MAX_LOCK_VALUE);

        // Cross-validate against Lock::MAX_VALUE compile-time const.
        check!("Lock::MAX_VALUE vs model", crate::device::tile::Lock::MAX_VALUE as u32, dc.max_lock_value);

        // address_gen_granularity: 32-byte alignment (no arch const yet).
        check!("address_gen_granularity", dc.address_gen_granularity, 32_u32);

        // Memory base addresses.
        if let Some(&south) = dc.mem_base_addresses.get("south") {
            check!(
                "mem_base_south",
                south as u32,
                arch::cardinal::SOUTH as u32 * arch::compute::MEMORY_SIZE as u32
            );
        } else {
            mismatches.push("missing mem_base_addresses.south".to_string());
        }
        if let Some(&west) = dc.mem_base_addresses.get("west") {
            check!(
                "mem_base_west",
                west as u32,
                arch::cardinal::WEST as u32 * arch::compute::MEMORY_SIZE as u32
            );
        } else {
            mismatches.push("missing mem_base_addresses.west".to_string());
        }
        if let Some(&north) = dc.mem_base_addresses.get("north") {
            check!(
                "mem_base_north",
                north as u32,
                arch::cardinal::NORTH as u32 * arch::compute::MEMORY_SIZE as u32
            );
        } else {
            mismatches.push("missing mem_base_addresses.north".to_string());
        }
        if let Some(&east) = dc.mem_base_addresses.get("east") {
            check!(
                "mem_base_east",
                east as u32,
                arch::cardinal::EAST as u32 * arch::compute::MEMORY_SIZE as u32
            );
        } else {
            mismatches.push("missing mem_base_addresses.east".to_string());
        }
    } else {
        mismatches.push("missing device_constants".to_string());
    }

    // --- Array topology ---
    if let Some(ref topo) = model.array_topology {
        check!("column_shift", topo.column_shift as u32, arch::TILE_COL_SHIFT);
        check!("row_shift", topo.row_shift as u32, arch::TILE_ROW_SHIFT);
    } else {
        mismatches.push("missing array_topology".to_string());
    }

    // --- Tile types ---
    let compute = model.tile_types.iter().find(|t| t.kind == TileKind::Compute);
    if let Some(c) = compute {
        check!("core.num_locks", *c.instances.locks.value() as usize, arch::compute::NUM_LOCKS);
        check!("core.num_bds", *c.instances.bds.value() as usize, arch::compute::NUM_BDS);

        // Memory size.
        if let Some(ref mem) = c.memory {
            check!("local_memory_size", mem.size_bytes as usize, arch::compute::MEMORY_SIZE);
        } else {
            mismatches.push("core: missing memory model".to_string());
        }

        // DMA port counts.
        let dma = c.switchbox_ports.iter().find(|p| p.bundle == "DMA");
        if let Some(dma) = dma {
            check!("core.dma_mm2s_ports", dma.masters as usize, arch::compute::NUM_DMA_CHANNELS);
            check!("core.dma_s2mm_ports", dma.slaves as usize, arch::compute::NUM_DMA_CHANNELS);
        } else {
            mismatches.push("core: missing DMA switchbox_ports".to_string());
        }
    } else {
        mismatches.push("missing compute tile type".to_string());
    }

    let memtile = model.tile_types.iter().find(|t| t.kind == TileKind::Mem);
    if let Some(m) = memtile {
        check!("mem_tile.num_locks", *m.instances.locks.value() as usize, arch::memtile::NUM_LOCKS);
        check!("mem_tile.num_bds", *m.instances.bds.value() as usize, arch::memtile::NUM_BDS);

        if let Some(ref mem) = m.memory {
            check!("mem_tile_size", mem.size_bytes as usize, arch::memtile::MEMORY_SIZE);
        } else {
            mismatches.push("mem_tile: missing memory model".to_string());
        }

        let dma = m.switchbox_ports.iter().find(|p| p.bundle == "DMA");
        if let Some(dma) = dma {
            check!("mem_tile.dma_mm2s_ports", dma.masters as usize, arch::memtile::NUM_DMA_CHANNELS);
            check!("mem_tile.dma_s2mm_ports", dma.slaves as usize, arch::memtile::NUM_DMA_CHANNELS);
        } else {
            mismatches.push("mem_tile: missing DMA switchbox_ports".to_string());
        }
    } else {
        mismatches.push("missing mem_tile tile type".to_string());
    }

    let shim = model.tile_types.iter().find(|t| t.kind == TileKind::ShimNoc);
    if let Some(s) = shim {
        check!("shim_noc.num_locks", *s.instances.locks.value() as usize, arch::shim::NUM_LOCKS);
        check!("shim_noc.num_bds", *s.instances.bds.value() as usize, arch::shim::NUM_BDS);
    } else {
        mismatches.push("missing shim_noc tile type".to_string());
    }

    if mismatches.is_empty() {
        Ok(())
    } else {
        Err(DeviceModelError::Validation(format!(
            "{} mismatch(es):\n  {}",
            mismatches.len(),
            mismatches.join("\n  ")
        )))
    }
}

// ===========================================================================
// Tests
// ===========================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;
    use xdna_archspec::device_model::{extract_device_model, extract_device_models};

    /// Path to the pre-generated device model JSON.
    fn json_path() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tools/aie-device-models.json")
    }

    #[test]
    fn parse_device_model_json() {
        let models = extract_device_models(&json_path()).expect("parse failed");

        // Should have at least npu1 and npu2.
        assert!(models.contains_key("npu1"), "missing npu1 device");
        assert!(models.contains_key("npu2"), "missing npu2 device");
    }

    #[test]
    fn npu1_basic_parameters() {
        let model = extract_device_model(&json_path(), "npu1").expect("parse failed");

        assert_eq!(model.device_id, Some(4));
        assert!(model.is_npu);

        let topo = model.array_topology.as_ref().expect("missing topology");
        assert_eq!(topo.columns, 4);
        assert_eq!(topo.rows, 6);
        assert_eq!(topo.num_mem_tile_rows, 1);
        assert_eq!(topo.column_shift, 25);
        assert_eq!(topo.row_shift, 20);

        let dc = model.device_constants.as_ref().expect("missing constants");
        assert_eq!(dc.max_lock_value, 63);
        assert_eq!(dc.address_gen_granularity, 32);
    }

    #[test]
    fn npu1_tile_type_banks() {
        use xdna_archspec::types::TileKind;

        let model = extract_device_model(&json_path(), "npu1").expect("parse failed");

        let core = model.tile_types.iter().find(|t| t.kind == TileKind::Compute).expect("no core");
        let core_mem = core.memory.as_ref().expect("core should have memory");
        // The archspec extractor defaults num_banks to 4 when absent from JSON
        // (logical banking from mlir-aie -- bank groups, not physical banks).
        // AM020 says 8 physical banks per compute tile. Both are valid.
        assert!(
            core_mem.logical.num_banks == 4 || core_mem.logical.num_banks == 8,
            "unexpected core num_banks: {}",
            core_mem.logical.num_banks
        );

        let mem = model.tile_types.iter().find(|t| t.kind == TileKind::Mem).expect("no mem_tile");
        let mem_tile_mem = mem.memory.as_ref().expect("mem_tile should have memory");
        // MemTile: 8 logical banks (from mlir-aie or default) or 16 physical.
        assert!(
            mem_tile_mem.logical.num_banks == 8 || mem_tile_mem.logical.num_banks == 16,
            "unexpected memtile num_banks: {}",
            mem_tile_mem.logical.num_banks
        );
    }

    #[test]
    fn npu1_tile_types() {
        use xdna_archspec::types::TileKind;

        let model = extract_device_model(&json_path(), "npu1").expect("parse failed");

        let core = model.tile_types.iter().find(|t| t.kind == TileKind::Compute).expect("no core");
        assert_eq!(*core.instances.locks.value(), 16);
        assert_eq!(*core.instances.bds.value(), 16);

        let mem = model.tile_types.iter().find(|t| t.kind == TileKind::Mem).expect("no mem_tile");
        assert_eq!(*mem.instances.locks.value(), 64);
        assert_eq!(*mem.instances.bds.value(), 48);

        let shim = model
            .tile_types
            .iter()
            .find(|t| t.kind == TileKind::ShimNoc)
            .expect("no shim_noc");
        assert_eq!(*shim.instances.locks.value(), 16);
        assert_eq!(*shim.instances.bds.value(), 16);
    }

    #[test]
    fn npu1_tile_map_coverage() {
        let model = extract_device_model(&json_path(), "npu1").expect("parse failed");
        let topo = model.array_topology.as_ref().expect("missing topology");

        // Should have cols * rows tile map entries.
        let expected = (topo.columns as usize) * (topo.rows as usize);
        assert_eq!(topo.tile_map.len(), expected);

        // Verify classification matches expected layout.
        let find = |col: u8, row: u8| {
            topo.tile_map
                .iter()
                .find(|t| t.col == col && t.row == row)
                .map(|t| t.tile_type.as_str())
        };
        assert_eq!(find(0, 0), Some("shim_noc"));
        assert_eq!(find(0, 1), Some("mem_tile"));
        assert_eq!(find(0, 2), Some("core"));
        assert_eq!(find(0, 5), Some("core"));

        // Out-of-range returns None.
        assert_eq!(find(99, 99), None);
    }

    #[test]
    fn npu1_mem_base_addresses() {
        let model = extract_device_model(&json_path(), "npu1").expect("parse failed");
        let dc = model.device_constants.as_ref().expect("missing constants");

        assert_eq!(dc.mem_base_addresses.get("south").copied(), Some(0x40000));
        assert_eq!(dc.mem_base_addresses.get("west").copied(), Some(0x50000));
        assert_eq!(dc.mem_base_addresses.get("north").copied(), Some(0x60000));
        assert_eq!(dc.mem_base_addresses.get("east").copied(), Some(0x70000));
    }

    #[test]
    fn npu1_stream_switch_ports() {
        use xdna_archspec::types::TileKind;

        let model = extract_device_model(&json_path(), "npu1").expect("parse failed");

        let core = model.tile_types.iter().find(|t| t.kind == TileKind::Compute).expect("no core");
        let dma = core.switchbox_ports.iter().find(|p| p.bundle == "DMA").expect("DMA ports");
        assert_eq!(dma.masters, 2); // MM2S channels
        assert_eq!(dma.slaves, 2); // S2MM channels

        let mem = model.tile_types.iter().find(|t| t.kind == TileKind::Mem).expect("no mem_tile");
        let dma = mem.switchbox_ports.iter().find(|p| p.bundle == "DMA").expect("DMA ports");
        assert_eq!(dma.masters, 6);
        assert_eq!(dma.slaves, 6);
    }

    #[test]
    fn npu2_basic_parameters() {
        let model = extract_device_model(&json_path(), "npu2").expect("parse failed");

        assert_eq!(model.device_id, Some(8));
        assert!(model.is_npu);

        let topo = model.array_topology.as_ref().expect("missing topology");
        assert_eq!(topo.columns, 8);
        assert_eq!(topo.rows, 6);
    }

    #[test]
    fn npu1_column_variants() {
        let models = extract_device_models(&json_path()).expect("parse failed");

        for (name, expected_cols) in [("npu1_1col", 1u8), ("npu1_2col", 2), ("npu1_3col", 3), ("npu1", 4)] {
            let dev = models.get(name).unwrap_or_else(|| panic!("missing {}", name));
            let topo = dev.array_topology.as_ref().expect("missing topology");
            assert_eq!(topo.columns, expected_cols, "{} columns", name);
            assert_eq!(topo.rows, 6, "{} rows", name);

            // All variants share the same local memory size.
            use xdna_archspec::types::TileKind;
            let core = dev.tile_types.iter().find(|t| t.kind == TileKind::Compute).expect("no core");
            let mem_size = core.memory.as_ref().expect("no memory").size_bytes;
            assert_eq!(mem_size, 65536, "{} local memory", name);
        }
    }

    #[test]
    fn validate_npu1_reference_values() {
        let model = extract_device_model(&json_path(), "npu1").expect("parse failed");

        validate_against_spec(&model).unwrap_or_else(|e| {
            panic!("NPU1 model does not match expected reference values: {}", e);
        });
    }
}
