//! Runtime-side stream-switch port-layout extension trait for `ModelConfig`.
//!
//! Defines the `PortLayout` extension trait and its implementation for
//! `ModelConfig`. These methods must remain runtime-side because their data
//! comes from `crate::arch` (a build.rs-generated module containing AM025 port
//! arrays that is not accessible from the archspec workspace crate).
//!
//! When AIE2P diverges in port layout, add AIE2P-specific arrays and select
//! based on `ModelConfig::name()` or an architecture field. That addition
//! stays runtime-side until port generation is moved into the archspec crate.
//!
//! See `docs/arch/phase1a-audit.md` (Port Data Dependency section) for the
//! full rationale.

use xdna_archspec::runtime::ModelConfig;
use xdna_archspec::types::TileKind;

/// Stream-switch port-layout extension trait.
///
/// These six methods must live runtime-side because their data is generated by
/// the main crate's `build.rs` from AM025 register names (via
/// `gen_stream_ports()` and `gen_stream_ranges()`).  The archspec workspace
/// crate does not run the main crate's build.rs, so it cannot access
/// `crate::arch::*`.
///
/// When AIE2P diverges in port layout, add AIE2P-specific arrays and select
/// based on `ModelConfig::name()` or an architecture field.  That addition
/// stays runtime-side until Option B from the audit (moving port generation
/// into the archspec crate) is implemented in a dedicated pass.
pub trait PortLayout {
    /// Get the master port layout for a tile type.
    ///
    /// Returns an ordered slice of port-type identifiers (one element per
    /// stream-switch master port).  Generated by build.rs from
    /// `Stream_Switch_Master_Config_*` register names in the AM025 JSON.
    fn master_ports(&self, tile: TileKind) -> &'static [u8];

    /// Get the slave port layout for a tile type.
    ///
    /// Returns an ordered slice of port-type identifiers for stream-switch
    /// slave ports.
    fn slave_ports(&self, tile: TileKind) -> &'static [u8];

    /// Get the range of north-facing master ports `(start, end)` inclusive.
    fn north_master_range(&self, tile: TileKind) -> (u8, u8);

    /// Get the range of south-facing master ports `(start, end)` inclusive.
    ///
    /// Returns `(0, 0)` for tile types that have no south masters (e.g. shim).
    fn south_master_range(&self, tile: TileKind) -> (u8, u8);

    /// Get the range of north-facing slave ports `(start, end)` inclusive.
    fn north_slave_range(&self, tile: TileKind) -> (u8, u8);

    /// Get the range of south-facing slave ports `(start, end)` inclusive.
    ///
    /// Returns `(0, 0)` for tile types that have no south slaves (e.g. shim).
    fn south_slave_range(&self, tile: TileKind) -> (u8, u8);
}

impl PortLayout for ModelConfig {
    fn master_ports(&self, tile: TileKind) -> &'static [u8] {
        match tile {
            TileKind::ShimNoc | TileKind::ShimPl => crate::arch::SHIM_MASTER_PORTS,
            TileKind::Mem => crate::arch::MEMTILE_MASTER_PORTS,
            TileKind::Compute => crate::arch::COMPUTE_MASTER_PORTS,
        }
    }

    fn slave_ports(&self, tile: TileKind) -> &'static [u8] {
        match tile {
            TileKind::ShimNoc | TileKind::ShimPl => crate::arch::SHIM_SLAVE_PORTS,
            TileKind::Mem => crate::arch::MEMTILE_SLAVE_PORTS,
            TileKind::Compute => crate::arch::COMPUTE_SLAVE_PORTS,
        }
    }

    fn north_master_range(&self, tile: TileKind) -> (u8, u8) {
        use crate::arch::stream_switch::*;
        match tile {
            TileKind::ShimNoc | TileKind::ShimPl => (shim::NORTH_MASTER_START, shim::NORTH_MASTER_END),
            TileKind::Mem => (mem_tile::NORTH_MASTER_START, mem_tile::NORTH_MASTER_END),
            TileKind::Compute => (compute::NORTH_MASTER_START, compute::NORTH_MASTER_END),
        }
    }

    fn south_master_range(&self, tile: TileKind) -> (u8, u8) {
        use crate::arch::stream_switch::*;
        match tile {
            // Shim tiles have no south-facing masters (south is the external interface).
            TileKind::ShimNoc | TileKind::ShimPl => (0, 0),
            TileKind::Mem => (mem_tile::SOUTH_MASTER_START, mem_tile::SOUTH_MASTER_END),
            TileKind::Compute => (compute::SOUTH_MASTER_START, compute::SOUTH_MASTER_END),
        }
    }

    fn north_slave_range(&self, tile: TileKind) -> (u8, u8) {
        use crate::arch::stream_switch::*;
        match tile {
            TileKind::ShimNoc | TileKind::ShimPl => (shim::NORTH_SLAVE_START, shim::NORTH_SLAVE_END),
            TileKind::Mem => (mem_tile::NORTH_SLAVE_START, mem_tile::NORTH_SLAVE_END),
            TileKind::Compute => (compute::NORTH_SLAVE_START, compute::NORTH_SLAVE_END),
        }
    }

    fn south_slave_range(&self, tile: TileKind) -> (u8, u8) {
        use crate::arch::stream_switch::*;
        match tile {
            // Shim tiles have no south-facing slaves.
            TileKind::ShimNoc | TileKind::ShimPl => (0, 0),
            TileKind::Mem => (mem_tile::SOUTH_SLAVE_START, mem_tile::SOUTH_SLAVE_END),
            TileKind::Compute => (compute::SOUTH_SLAVE_START, compute::SOUTH_SLAVE_END),
        }
    }
}

// ============================================================================
// Tests
// ============================================================================
//
// Core ArchConfig tests (dimensions, tile classification, memory sizes, DMA
// config) are in `xdna_archspec::runtime::tests`.  Only port-layout tests
// live here, since PortLayout is runtime-side.

#[cfg(test)]
mod tests {
    use super::*;

    fn npu1_config() -> ModelConfig {
        // Extract the inner ModelConfig for PortLayout impl access.
        // npu1() returns Arc<dyn ArchConfig>; we need a concrete ModelConfig.
        // Re-derive it via from_arch_model so we have the concrete type.
        use xdna_archspec::runtime::ARCHSPEC_MODELS;
        let model = ARCHSPEC_MODELS.get("npu1").expect("npu1 in JSON");
        ModelConfig::from_arch_model(model, "test")
    }

    #[test]
    fn test_npu1_port_layouts() {
        let cfg = npu1_config();

        // Verify port counts match AM025 spec
        assert_eq!(cfg.master_ports(TileKind::ShimNoc).len(), 22);
        assert_eq!(cfg.slave_ports(TileKind::ShimNoc).len(), 23);

        assert_eq!(cfg.master_ports(TileKind::Mem).len(), 17);
        assert_eq!(cfg.slave_ports(TileKind::Mem).len(), 18);

        assert_eq!(cfg.master_ports(TileKind::Compute).len(), 23);
        assert_eq!(cfg.slave_ports(TileKind::Compute).len(), 25);
    }

    #[test]
    fn test_npu1_port_ranges() {
        use crate::arch::stream_switch::{compute, mem_tile, shim};

        let cfg = npu1_config();

        // Shim north masters: 12-17 (6 ports)
        let (start, end) = cfg.north_master_range(TileKind::ShimNoc);
        assert_eq!((start, end), (12, 17));
        assert_eq!(end - start + 1, 6);

        // MemTile south masters: 7-10 (4 ports)
        let (start, end) = cfg.south_master_range(TileKind::Mem);
        assert_eq!((start, end), (7, 10));

        // MemTile north masters: 11-16 (6 ports)
        let (start, end) = cfg.north_master_range(TileKind::Mem);
        assert_eq!((start, end), (11, 16));

        // Shim has no south masters or slaves
        assert_eq!(cfg.south_master_range(TileKind::ShimNoc), (0, 0));
        assert_eq!(cfg.south_slave_range(TileKind::ShimNoc), (0, 0));

        // Validate E/W generated constants match AM025 port arrays
        // Compute tile
        assert_eq!(compute::EAST_MASTER_START, 19);
        assert_eq!(compute::EAST_MASTER_END, 22);
        assert_eq!(compute::EAST_SLAVE_START, 19);
        assert_eq!(compute::EAST_SLAVE_END, 22);
        assert_eq!(compute::WEST_MASTER_START, 9);
        assert_eq!(compute::WEST_MASTER_END, 12);
        assert_eq!(compute::WEST_SLAVE_START, 11);
        assert_eq!(compute::WEST_SLAVE_END, 14);

        // Shim tile
        assert_eq!(shim::EAST_MASTER_START, 18);
        assert_eq!(shim::EAST_MASTER_END, 21);
        assert_eq!(shim::EAST_SLAVE_START, 18);
        assert_eq!(shim::EAST_SLAVE_END, 21);
        assert_eq!(shim::WEST_MASTER_START, 8);
        assert_eq!(shim::WEST_MASTER_END, 11);
        assert_eq!(shim::WEST_SLAVE_START, 10);
        assert_eq!(shim::WEST_SLAVE_END, 13);
        assert_eq!(shim::SOUTH_MASTER_START, 2);
        assert_eq!(shim::SOUTH_MASTER_END, 7);
        assert_eq!(shim::SOUTH_SLAVE_START, 2);
        assert_eq!(shim::SOUTH_SLAVE_END, 9);

        // Verify port counts are consistent (END - START + 1)
        assert_eq!(compute::EAST_MASTER_END - compute::EAST_MASTER_START + 1, 4);
        assert_eq!(compute::WEST_MASTER_END - compute::WEST_MASTER_START + 1, 4);
        assert_eq!(shim::EAST_MASTER_END - shim::EAST_MASTER_START + 1, 4);
        assert_eq!(shim::WEST_MASTER_END - shim::WEST_MASTER_START + 1, 4);
        assert_eq!(shim::SOUTH_MASTER_END - shim::SOUTH_MASTER_START + 1, 6);

        // Verify MemTile has no E/W port constants (structural check):
        // if it did, accessing them would be a compile error.
        assert_eq!(mem_tile::SOUTH_MASTER_START, 7);
        assert_eq!(mem_tile::NORTH_MASTER_START, 11);
    }

    #[test]
    fn test_shim_pl_same_as_shim_noc() {
        // ShimPl and ShimNoc should return the same port arrays.
        let cfg = npu1_config();
        assert_eq!(
            cfg.master_ports(TileKind::ShimNoc),
            cfg.master_ports(TileKind::ShimPl),
        );
        assert_eq!(
            cfg.slave_ports(TileKind::ShimNoc),
            cfg.slave_ports(TileKind::ShimPl),
        );
        assert_eq!(
            cfg.north_master_range(TileKind::ShimNoc),
            cfg.north_master_range(TileKind::ShimPl),
        );
    }
}
