//! AIE2 (NPU1 Phoenix / NPU2+ Strix) architecture constants.
//!
//! Every `pub const` that reflects AIE2 hardware data -- register
//! offsets, memory sizes, per-tile-type resource counts, stream switch
//! port layouts, timing constants, FoT values, and packet formats --
//! lives under this module. Additional slices (ISA encodings, decoder FFI)
//! land here in a later subsystem.
//! Multi-arch support is planned as sibling modules (e.g.,
//! `xdna_archspec::aie1`, `xdna_archspec::aie2p`) that would mirror
//! this namespace with different values.
//!
//! This module's submodules are either `include!()` of
//! build.rs-generated files in $OUT_DIR or hand-written constants that
//! the toolchain does not yet emit machine-readably.

// Generated by build.rs from gen_arch(). Provides:
//   - top-level consts: COLUMNS, ROWS, NUM_MEM_TILE_ROWS, MAX_LOCK_VALUE,
//     MIN_LOCK_VALUE, TILE_COL_SHIFT, TILE_ROW_SHIFT, TILE_OFFSET_MASK,
//     TILE_ROW_BITS, TILE_COL_BITS, SHIM_ROW, COMPUTE_ROW_START,
//     DATA_MEM_HOST_OFFSET.
//   - pub mod compute, memtile, shim: per-tile-type constants.
//   - pub mod cardinal: direction indices (4-7) for core data memory addressing.
//   - pub mod timing, packet, ctrl_packet, fot, processor.
include!(concat!(env!("OUT_DIR"), "/gen_arch.rs"));

// Port type arrays generated from AM025 Stream_Switch_*_Config registers.
// Defines COMPUTE_MASTER_PORTS, COMPUTE_SLAVE_PORTS, MEMTILE_MASTER_PORTS,
// MEMTILE_SLAVE_PORTS, SHIM_MASTER_PORTS, SHIM_SLAVE_PORTS.
include!(concat!(env!("OUT_DIR"), "/gen_stream_ports.rs"));

/// Number of u64 words in the AIE2 cascade link data payload.
///
/// The cascade link is 384 bits wide = 6 x u64. This is the physical
/// link width connecting adjacent compute tiles (SCD input, MCD output).
/// Source: aie-rt xaie_core.c:993-1046; AM020 cascade stream description.
/// Only valid when `ProcessorModel::has_cascade_link` is true.
pub const CASCADE_WORDS: usize = 6;

/// Per-tile-type subsystem address ranges (generated from ArchModel).
///
/// Submodules: compute, memtile, shim. Each contains `pub mod <subsystem>`
/// with `OFFSET_START` and `OFFSET_END` consts.
pub mod subsystems;

/// Core-module register offsets and lock-request bitfield constants.
///
/// Top level: core module offsets (CORE_CONTROL, CORE_STATUS, etc.) and
/// OFFSET_START / OFFSET_END. Submodules `memory` and `mem_tile` contain
/// Lock_Request address-encoding constants for each module type.
pub mod registers;

/// Stream switch port ranges and configuration bits (from AM025).
///
/// Submodules `compute`, `mem_tile`, `shim` each contain
/// `NORTH_MASTER_START/END`, `SOUTH_MASTER_START/END`, etc.
/// `ENABLE_BIT` and `SLAVE_SELECT_MASK` live at the module root.
pub mod stream_switch;

/// Trace event codes from the mlir-aie Python bridge.
///
/// Per-tile-module const tables (`core_events`, `mem_events`, `memtile_events`,
/// `shim_events`) and name-lookup functions (`core_event_name`, etc.).
/// Generated at build time by `build.rs` from `tools/mlir-aie-bridge.py trace-events`.
/// Falls back to stub functions returning "UNKNOWN" when mlir-aie is absent.
pub mod trace_events;

/// Derived memory-map constants (AIE_DATA_MEMORY_BASE, PROGRAM_MEMORY_BASE, etc.).
///
/// All values are computed from other `aie2` submodule constants so that
/// memory-map arithmetic has a single home inside `xdna-archspec`.
pub mod memory_map;

/// Instruction result-latency constants for the AIE2 core pipeline.
///
/// These latencies are the cycles from instruction issue to when the result
/// is visible to a subsequent instruction (i.e., forwarding/bypass delays
/// included). Values are derived from `AIE2Schedule.td` itinerary data
/// via the `II_*` classes and are cross-validated in xdna-emu's
/// `test_latency_cross_validation_against_itineraries` test.
///
/// The `timing` module (generated) holds device-level timing parameters
/// (DMA, stream-switch, lock, memory pipeline depth). This module holds
/// instruction-pipeline result latencies that come from the compiler's
/// scheduling model rather than the device architecture JSON.
pub mod instruction_latency {
    /// Scalar multiply (32×32) result latency: 2 cycles.
    ///
    /// Source: `AIE2Schedule.td` `II_MUL` itinerary, `operand_cycles[0] = 2`.
    pub const SCALAR_MUL: u8 = 2;

    /// Scalar division result latency: 6 cycles.
    ///
    /// AIE2 uses an iterative division algorithm. The 6-cycle value
    /// represents the throughput cost (hardware stalls for 6 cycles
    /// before the next instruction can issue). Source: AM020 Ch4 +
    /// hardware observation.
    pub const SCALAR_DIV: u8 = 6;

    /// Vector simple operation result latency (add, sub, compare): 2 cycles.
    ///
    /// Source: `AIE2Schedule.td` `II_VADD`, `II_VSUB` itineraries,
    /// `operand_cycles[0] = 2`.
    pub const VECTOR_SIMPLE: u8 = 2;

    /// Vector multiply result latency: 5 cycles.
    ///
    /// Source: `AIE2Schedule.td` `II_VMUL`, `II_VNEGMUL` itineraries,
    /// `operand_cycles[0] = 5`.
    pub const VECTOR_MUL: u8 = 5;

    /// Vector MAC (multiply-accumulate) result latency: 5 cycles.
    ///
    /// Source: `AIE2Schedule.td` `II_VMAC`, `II_VMSC`, `II_VNEGMAC`,
    /// `II_VACC` itineraries, `operand_cycles[0] = 5`.
    pub const VECTOR_MAC: u8 = 5;

    /// Vector shuffle/permute result latency: 2 cycles.
    ///
    /// Source: `AIE2Schedule.td` `II_VSHUFFLE` itinerary,
    /// `operand_cycles[0] = 2`.
    pub const VECTOR_SHUFFLE: u8 = 2;

    /// Vector pack/unpack result latency: 2 cycles.
    ///
    /// Source: `AIE2Schedule.td` `II_VPACK` itinerary,
    /// `operand_cycles[0] = 2`.
    pub const VECTOR_PACK: u8 = 2;
}

/// Stream switch port type identifier (xdna-emu convention, not hardware).
///
/// Each port index in the port arrays maps to one of these types. This
/// is a hand-written set of constants because it is an encoding
/// convention, not an AM025 register value.
pub mod port_type {
    pub const CORE: u8 = 0;
    pub const FIFO: u8 = 1;
    pub const TRACE: u8 = 2;
    /// Tile control port (configuration/debug).
    /// Per AM025: compute=port 3, memtile=port 6, shim=port 0.
    pub const CTRL: u8 = 3;
    pub const NORTH_BASE: u8 = 10;
    pub const SOUTH_BASE: u8 = 20;
    pub const EAST_BASE: u8 = 30;
    pub const WEST_BASE: u8 = 40;
    pub const DMA_BASE: u8 = 50;

    pub const fn north(n: u8) -> u8 { NORTH_BASE + n }
    pub const fn south(n: u8) -> u8 { SOUTH_BASE + n }
    pub const fn east(n: u8) -> u8 { EAST_BASE + n }
    pub const fn west(n: u8) -> u8 { WEST_BASE + n }
    pub const fn dma(n: u8) -> u8 { DMA_BASE + n }
}

/// aie-rt cross-validation data. Each submodule wraps a
/// build-time-generated file extracted from aie-rt headers via the C
/// preprocessor. Submodules: `dma`, `locks`, `ports`.
pub mod aiert;

/// AIE2-family tile topology impl (`Aie2Topology`). Subsystem 2 seam.
pub mod topology;

/// AIE2-family DMA model (`Aie2DmaModel` + `AIE2_DMA_MODEL` static). Subsystem 3 seam.
pub mod dma;

/// AIE2-family lock model (`Aie2LockModel` + `AIE2_LOCK_MODEL` static). Subsystem 4 seam.
pub mod locks;

/// AIE2-family stream switch model (`Aie2StreamSwitchModel` +
/// `AIE2_STREAM_SWITCH_MODEL` static). Subsystem 5 seam.
pub mod stream_switch_model;

/// AIE2-family ISA execute model (`Aie2IsaExecutor` +
/// `AIE2_ISA_EXECUTOR` static). Subsystem 7 seam.
pub mod isa_execute_model;

/// Hardware rounding modes for the SRS instruction and bf16 conversion.
///
/// Defines the 10-variant `RoundingMode` enum shared between the integer
/// SRS pipeline (`vector_srs.rs`) and the bf16 conversion path
/// (`vector_float.rs`). Both files previously carried identical local copies.
pub mod rounding;

/// Permute and shuffle data for the AIE2 vector unit.
///
/// `ShuffleMode` (48 hardware shuffle modes) + `SHUFFLE_ROUTING` (hardware-probed
/// byte-routing table, 48 x 64 bytes) drive the `vshuffle` instruction.
/// `MacPermuteMode` (26 modes) + `MacPermuteConfig` + `mac_permute_config()`
/// drive MAC permutation routing. All pure data; execution algorithms
/// (`shuffle_vectors`, `rc2i`) stay in xdna-emu.
pub mod permute;

/// Matrix multiply geometry tables for the AIE2 vector multiply array.
///
/// `DENSE_GEOMETRY_TABLE`, `SPARSE_GEOMETRY_TABLE`, and `CONFIG_GEOMETRY_TABLE`
/// encode the valid tile dimensions (rows, inner, cols) and accumulator modes
/// for each element type pair. Authoritative source for `vector_config.rs`.
pub mod matmul;

/// UPS (Upshift / type-widening) mode table for the AIE2 vector unit.
///
/// The four valid UPS modes: `UpsScale` x `UpsAccMode` -> `UpsMode`
/// (lanes, bits_in, bits_out). Authoritative source for `vector_ups.rs`.
pub mod ups;

/// VMAC crossbar routing data (PRMX + PRMY tables) for the AIE2
/// multiply-accumulate pipeline.
///
/// Pure hardware-probed data (789 active m-bits, 15808 route entries)
/// with two `pub fn` entry points, `eval_prmx` and `eval_prmy`, that
/// operate on the tables. Consumed by `src/interpreter/execute/vmac_hw.rs`
/// via `use xdna_archspec::aie2::vmac::{eval_prmx, eval_prmy};`.
pub mod vmac;

/// Instruction set architecture: decoder tables, runtime model, and
/// LLVM MCDisassembler FFI. Populated during Subsystem 6 Part A.
pub mod isa;

#[cfg(test)]
mod tests {
    use super::instruction_latency;

    /// Drift-detection test for the instruction_latency pipeline constants.
    ///
    /// These constants come from `AIE2Schedule.td` itinerary data and are
    /// cross-validated against xdna-emu's `test_latency_cross_validation_against_itineraries`
    /// test in `src/interpreter/timing/latency.rs`. This standalone archspec test
    /// catches drift without requiring the full emulator crate to compile.
    ///
    /// If any of these values change, verify the new value against
    /// `AIE2Schedule.td` `operand_cycles[0]` for the corresponding itinerary
    /// class before updating.
    #[test]
    fn instruction_latency_constants_match_aie2schedule_td() {
        // Scalar pipeline latencies
        assert_eq!(instruction_latency::SCALAR_MUL, 2,
            "II_MUL operand_cycles[0] = 2 per AIE2Schedule.td");
        assert_eq!(instruction_latency::SCALAR_DIV, 6,
            "6-cycle iterative division per AM020 Ch4 + hardware observation");

        // Vector pipeline latencies
        assert_eq!(instruction_latency::VECTOR_SIMPLE, 2,
            "II_VADD/II_VSUB operand_cycles[0] = 2 per AIE2Schedule.td");
        assert_eq!(instruction_latency::VECTOR_MUL, 5,
            "II_VMUL operand_cycles[0] = 5 per AIE2Schedule.td");
        assert_eq!(instruction_latency::VECTOR_MAC, 5,
            "II_VMAC operand_cycles[0] = 5 per AIE2Schedule.td");
        assert_eq!(instruction_latency::VECTOR_SHUFFLE, 2,
            "II_VSHUFFLE operand_cycles[0] = 2 per AIE2Schedule.td");
        assert_eq!(instruction_latency::VECTOR_PACK, 2,
            "II_VPACK operand_cycles[0] = 2 per AIE2Schedule.td");
    }
}
