//! AIE2 (NPU1 Phoenix / NPU2+ Strix) architecture constants.
//!
//! Every `pub const` that reflects AIE2 hardware data -- register
//! offsets, memory sizes, per-tile-type resource counts, stream switch
//! port layouts, timing constants, FoT values, and packet formats --
//! lives under this module. Additional slices (ISA encodings, trace
//! event IDs, register/memory-map helpers) land here in Tasks 6-9.
//! Multi-arch support is planned as sibling modules (e.g.,
//! `xdna_archspec::aie1`, `xdna_archspec::aie2p`) that would mirror
//! this namespace with different values.
//!
//! This module's submodules are either `include!()` of
//! build.rs-generated files in $OUT_DIR or hand-written constants that
//! the toolchain does not yet emit machine-readably.

// Generated by build.rs from gen_arch(). Provides:
//   - top-level consts: COLUMNS, ROWS, NUM_MEM_TILE_ROWS, MAX_LOCK_VALUE,
//     MIN_LOCK_VALUE, TILE_COL_SHIFT, TILE_ROW_SHIFT, TILE_OFFSET_MASK,
//     TILE_ROW_BITS, TILE_COL_BITS, SHIM_ROW, COMPUTE_ROW_START,
//     DATA_MEM_HOST_OFFSET.
//   - pub mod compute, memtile, shim: per-tile-type constants.
//   - pub mod cardinal: direction indices (4-7) for core data memory addressing.
//   - pub mod timing, packet, ctrl_packet, fot, processor.
include!(concat!(env!("OUT_DIR"), "/gen_arch.rs"));

/// Per-tile-type subsystem address ranges (generated from ArchModel).
///
/// Submodules: compute, memtile, shim. Each contains `pub mod <subsystem>`
/// with `OFFSET_START` and `OFFSET_END` consts.
pub mod subsystems;

/// Stream switch port type identifier (xdna-emu convention, not hardware).
///
/// Each port index in the port arrays maps to one of these types. This
/// is a hand-written set of constants because it is an encoding
/// convention, not an AM025 register value.
pub mod port_type {
    pub const CORE: u8 = 0;
    pub const FIFO: u8 = 1;
    pub const TRACE: u8 = 2;
    /// Tile control port (configuration/debug).
    /// Per AM025: compute=port 3, memtile=port 6, shim=port 0.
    pub const CTRL: u8 = 3;
    pub const NORTH_BASE: u8 = 10;
    pub const SOUTH_BASE: u8 = 20;
    pub const EAST_BASE: u8 = 30;
    pub const WEST_BASE: u8 = 40;
    pub const DMA_BASE: u8 = 50;

    pub const fn north(n: u8) -> u8 { NORTH_BASE + n }
    pub const fn south(n: u8) -> u8 { SOUTH_BASE + n }
    pub const fn east(n: u8) -> u8 { EAST_BASE + n }
    pub const fn west(n: u8) -> u8 { WEST_BASE + n }
    pub const fn dma(n: u8) -> u8 { DMA_BASE + n }
}
