//===- kernel.cc ------------------------------------------------*- C++ -*-===//
//
// DENSE fp32 special-value sub sweep capture kernel (GENERATED by
// tools/gen_special_value_dense.py). Single op (aie::sub) repeated across a
// dense Inf/NaN operand matrix -- no pipeline-adjacency confound. Inputs and
// outputs are staged as raw bit patterns; the signature uses the real element
// type so the DMA moves bytes verbatim (NaN!=NaN-safe bit-exact compare).
//
//===----------------------------------------------------------------------===//

#include <stdint.h>

#include <aie_api/aie.hpp>

#define SWEEP_N 2032

using V = aie::vector<float, 16>;
__attribute__((noinline)) static V vop(V a, V b) { return aie::sub(a, b); }

extern "C" {

void sub_fp32(float *restrict a, float *restrict b,
              float *restrict c) {
  event0();
  for (int i = 0; i < SWEEP_N; i += 16) {
    aie::vector<float, 16> va = aie::load_v<16>(a + i);
    aie::vector<float, 16> vb = aie::load_v<16>(b + i);
    aie::vector<float, 16> vc = vop(va, vb);
    aie::store_v(c + i, vc);
  }
  event1();
}

} // extern "C"
