#!/usr/bin/env python3
"""Generate MLIR for a single-tile fuzz kernel program.

Produces an aie.mlir file that routes data from the host through a memtile
to a compute tile, calls an external kernel function, and routes the result
back.  The MLIR uses the objectfifo dialect so that the compiler handles
all DMA, lock, and buffer lowering automatically.

Usage:
    python fuzz_template.py --kernel kernel.cc --size 64 --dtype i32 --outdir build/fuzz/seed_42

The generated aie.mlir is compilable via:
    aiecc.py --no-xchesscc --no-xbridge --no-aiesim \\
             --aie-generate-xclbin --aie-generate-npu-insts \\
             --no-compile-host --alloc-scheme=basic-sequential \\
             --xclbin-name=aie.xclbin --npu-insts-name=insts.bin \\
             aie.mlir

Reference patterns from mlir-aie/test/npu-xrt/add_one_objFifo/aie.mlir.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


# -- MLIR element types and byte widths ----------------------------------------

DTYPE_INFO: dict[str, tuple[str, int]] = {
    # dtype_str -> (mlir_type, bytes_per_element)
    "i32": ("i32", 4),
    "i16": ("i16", 2),
    "i8":  ("i8",  1),
}


# -- Buffer size calculations -------------------------------------------------

def _i32_words(n_elements: int, elem_bytes: int) -> int:
    """Number of 32-bit words needed to hold n_elements of elem_bytes each."""
    total_bytes = n_elements * elem_bytes
    # Round up to whole 32-bit words.
    return (total_bytes + 3) // 4


def _chunk_size(total_elements: int) -> tuple[int, int]:
    """Pick a tile-level chunk size and iteration count.

    Returns (chunk_elems, n_iters) where chunk_elems * n_iters == total.
    For simplicity, we keep the chunk equal to the full buffer so n_iters=1.
    If the total is large enough to warrant chunking, split into pieces that
    fit in the compute tile's 64 KB local memory (with headroom for two
    double-buffered input + output chunks).

    The constraint is:  2 * chunk_bytes * 2 (in+out) <= 48 KB (leaving 16 KB
    for code + stack).  So chunk_bytes <= 12288 -> chunk_i32 <= 3072.
    """
    max_chunk_bytes = 12288  # 12 KB per chunk, 4 chunks (2 in + 2 out) = 48 KB
    elem_bytes = 4  # Conservative; we check below if dtype is smaller.
    max_chunk_elems = max_chunk_bytes // elem_bytes

    if total_elements <= max_chunk_elems:
        return (total_elements, 1)

    # Find the largest divisor of total that is <= max_chunk_elems.
    for chunk in range(max_chunk_elems, 0, -1):
        if total_elements % chunk == 0:
            return (chunk, total_elements // chunk)

    # Fallback: single chunk (may not fit, but let the compiler complain).
    return (total_elements, 1)


# -- MLIR generation -----------------------------------------------------------

def generate_mlir(
    kernel_obj: str,
    total_elements: int,
    dtype_str: str,
    device: str = "NPUDEVICE",
) -> str:
    """Generate the full MLIR module text.

    Parameters
    ----------
    kernel_obj:
        Filename of the compiled kernel object (e.g. "fuzz_kernel.o").
    total_elements:
        Number of elements in the input and output buffers.
    dtype_str:
        Element data type: "i32", "i16", or "i8".
    device:
        AIE device target.  Use "NPUDEVICE" as a placeholder for
        sed-based architecture selection, or "npu1_1col" directly.
    """
    if dtype_str not in DTYPE_INFO:
        raise ValueError(f"Unsupported dtype: {dtype_str!r}; expected one of {list(DTYPE_INFO)}")
    if total_elements < 1:
        raise ValueError(f"Buffer size must be >= 1, got {total_elements}")

    mlir_type, elem_bytes = DTYPE_INFO[dtype_str]
    chunk_elems, n_iters = _chunk_size(total_elements)

    # Memtile-level chunk must be a multiple of tile chunk for the
    # objectfifo.link split/join to work.  A 2x ratio (pipelining) requires
    # n_iters to be even; with n_iters=1 the DMA would stall at half an
    # element.  Use 1:1 ratio for correctness at any iteration count.
    memtile_chunk = chunk_elems

    # Total transfer in 32-bit words (for runtime_sequence memrefs).
    total_i32 = _i32_words(total_elements, elem_bytes)

    # Memref type strings.
    tile_memref = f"memref<{chunk_elems}x{mlir_type}>"
    mt_memref = f"memref<{memtile_chunk}x{mlir_type}>"
    host_memref = f"memref<{total_i32}xi32>"

    lines: list[str] = []
    w = lines.append  # shorthand

    w(f"// Generated by fuzz_template.py -- do not edit")
    w(f"// dtype={dtype_str} size={total_elements} chunk={chunk_elems} iters={n_iters}")
    w(f"module {{")
    w(f"  aie.device({device}) {{")

    # External kernel declaration.
    w(f"    func.func private @fuzz_kernel({tile_memref}, {tile_memref})")
    w(f"")

    # Tiles.
    w(f"    %t00 = aie.tile(0, 0)")
    w(f"    %t01 = aie.tile(0, 1)")
    w(f"    %t02 = aie.tile(0, 2)")
    w(f"")

    # ObjectFIFOs: host(shim) -> memtile -> compute, and back.
    # Input path: shim -> memtile (in0), memtile -> compute (in1), linked.
    w(f"    aie.objectfifo @fuzz_in0(%t00, {{%t01}}, 2 : i32) : !aie.objectfifo<{mt_memref}>")
    w(f"    aie.objectfifo @fuzz_in1(%t01, {{%t02}}, 2 : i32) : !aie.objectfifo<{tile_memref}>")
    w(f"    aie.objectfifo.link [@fuzz_in0] -> [@fuzz_in1] ([] [])")
    w(f"")

    # Output path: compute -> memtile (out1), memtile -> shim (out0), linked.
    w(f"    aie.objectfifo @fuzz_out1(%t02, {{%t01}}, 2 : i32) : !aie.objectfifo<{tile_memref}>")
    w(f"    aie.objectfifo @fuzz_out0(%t01, {{%t00}}, 2 : i32) : !aie.objectfifo<{mt_memref}>")
    w(f"    aie.objectfifo.link [@fuzz_out1] -> [@fuzz_out0] ([] [])")
    w(f"")

    # Compute core.
    w(f"    aie.core(%t02) {{")
    w(f"      %c0 = arith.constant 0 : index")
    w(f"      %c1 = arith.constant 1 : index")
    w(f"      %c_n_iters = arith.constant {n_iters} : index")
    w(f"")
    w(f"      scf.for %iter = %c0 to %c_n_iters step %c1 {{")
    w(f"        %sv_in = aie.objectfifo.acquire @fuzz_in1(Consume, 1) : !aie.objectfifosubview<{tile_memref}>")
    w(f"        %buf_in = aie.objectfifo.subview.access %sv_in[0] : !aie.objectfifosubview<{tile_memref}> -> {tile_memref}")
    w(f"        %sv_out = aie.objectfifo.acquire @fuzz_out1(Produce, 1) : !aie.objectfifosubview<{tile_memref}>")
    w(f"        %buf_out = aie.objectfifo.subview.access %sv_out[0] : !aie.objectfifosubview<{tile_memref}> -> {tile_memref}")
    w(f"")
    w(f"        func.call @fuzz_kernel(%buf_in, %buf_out) : ({tile_memref}, {tile_memref}) -> ()")
    w(f"")
    w(f"        aie.objectfifo.release @fuzz_in1(Consume, 1)")
    w(f"        aie.objectfifo.release @fuzz_out1(Produce, 1)")
    w(f"      }}")
    w(f"      aie.end")
    w(f"    }} {{ link_with=\"{kernel_obj}\" }}")
    w(f"")

    # Runtime sequence: DMA transfers between host and device.
    # The runtime_sequence always uses i32 memrefs (shim DMA granularity).
    w(f"    aie.runtime_sequence(%in : {host_memref}, %buf : {host_memref}, %out : {host_memref}) {{")
    w(f"      %c0 = arith.constant 0 : i64")
    w(f"      %c1 = arith.constant 1 : i64")
    w(f"      %c_total = arith.constant {total_i32} : i64")
    w(f"")
    # Output DMA (S2MM): set up first so it is ready to receive.
    w(f"      aiex.npu.dma_memcpy_nd (%out[%c0,%c0,%c0,%c0][%c1,%c1,%c1,%c_total][%c0,%c0,%c0,%c1]) {{ metadata = @fuzz_out0, id = 1 : i64 }} : {host_memref}")
    # Input DMA (MM2S): issue_token so we can synchronize.
    w(f"      aiex.npu.dma_memcpy_nd (%in[%c0,%c0,%c0,%c0][%c1,%c1,%c1,%c_total][%c0,%c0,%c0,%c1]) {{ metadata = @fuzz_in0, id = 0 : i64, issue_token = true }} : {host_memref}")
    # Wait for output to complete.
    w(f"      aiex.npu.dma_wait {{ symbol = @fuzz_out0 }}")
    w(f"    }}")

    w(f"  }}")
    w(f"}}")

    return "\n".join(lines) + "\n"


# -- CLI -----------------------------------------------------------------------

def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Generate MLIR for a single-tile fuzz kernel.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument(
        "--kernel", required=True, type=Path,
        help="Path to the kernel source (.cc) or object (.o) file.",
    )
    p.add_argument(
        "--size", required=True, type=int,
        help="Number of elements in the input/output buffers.",
    )
    p.add_argument(
        "--dtype", required=True, choices=sorted(DTYPE_INFO),
        help="Element data type.",
    )
    p.add_argument(
        "--outdir", required=True, type=Path,
        help="Output directory for generated aie.mlir.",
    )
    p.add_argument(
        "--device", default="NPUDEVICE",
        help="AIE device target (default: NPUDEVICE placeholder for sed).",
    )
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)

    # Derive the kernel object filename from the source path.
    # If the user passes "fuzz_kernel.cc", the linked object is "fuzz_kernel.cc.o"
    # (aiecc.py compiles .cc to .cc.o when using --no-xchesscc).
    kernel_path: Path = args.kernel
    if kernel_path.suffix in (".cc", ".cpp", ".c"):
        kernel_obj = kernel_path.name + ".o"
    elif kernel_path.suffix == ".o":
        kernel_obj = kernel_path.name
    else:
        kernel_obj = kernel_path.stem + ".o"

    mlir_text = generate_mlir(
        kernel_obj=kernel_obj,
        total_elements=args.size,
        dtype_str=args.dtype,
        device=args.device,
    )

    # Write output.
    outdir: Path = args.outdir
    outdir.mkdir(parents=True, exist_ok=True)
    out_path = outdir / "aie.mlir"
    out_path.write_text(mlir_text)

    print(f"Wrote {out_path} ({len(mlir_text)} bytes)")
    print(f"  kernel_obj={kernel_obj} dtype={args.dtype} size={args.size}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
