#!/usr/bin/env python3
"""Isolated single-add probe: does h4's EXACT 32-lane (v3, p3) reproduce 0xFF8C?

Classifies the seed-6159 chained-NaN effect. The seed's h4 is aie::add(v3, p3)
and lane29 = add(0x7F80 +Inf, 0xFFC6 -NaN0x46) -> 0xFF8C on HW/aiesim, but the
SAME bf16 pair in the isolated dense sweep -> 0xFF81. This builds a minimal
single-add kernel fed h4's exact 32-lane input vectors with NO h0..h3 history:

  - lane29 -> 0xFF8C : trigger is CROSS-LANE vector content (the other lanes in
                       v3/p3 shape the NaN payload). Modelable from inputs.
  - lane29 -> 0xFF81 : trigger is PRECEDING-INSTRUCTION float-unit state. Needs
                       pipeline-state modeling.

v3 (operand a) is read from the captured seed output (slice3 = out u16[96..127]);
p3 (operand b) is read from the seed input pool (in u16[96..127]). Fully
data-driven -- no transcription.

OFFLINE authoring only. Emits tests/vector-verify/vec_h4_isolated_probe/.
"""

import os
import struct

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_TXT = os.path.join(REPO, "build/experiments/special-value-dense/seed6159_out.txt")
POOL_BIN = os.path.join(REPO, "build/experiments/bf16-nan-replay/pools/pool_seed_6159.bin")
OUT_DIR = os.path.join(REPO, "tests/vector-verify/vec_h4_isolated_probe")


def load_v3_from_outtxt():
    """slice3 = v3 = out u16[96..127]. out.txt is 256 decimal u16, one per line."""
    vals = [int(x) for x in open(OUT_TXT).read().split()]
    assert len(vals) >= 160, f"out.txt too short: {len(vals)}"
    return vals[96:128]


def load_p3_from_pool():
    p = open(POOL_BIN, "rb").read()
    p = p + bytes(512 - len(p))
    u16 = [struct.unpack_from("<H", p, i * 2)[0] for i in range(256)]
    return u16[96:128]


KERNEL_CC = """\
// Isolated single-add probe (GENERATED by tools/gen_h4_isolated_probe.py).
// out = aie::add(a, b) where a=v3, b=p3 are h4's exact input vectors, fed with
// NO preceding chain history. Classifies the chained-NaN effect.
#include <stdint.h>
#include <aie_api/aie.hpp>

extern "C" void h4_probe(int32_t *__restrict in, int32_t *__restrict out) {
  aie::vector<bfloat16, 32> a = aie::load_v<32>((bfloat16 *)(in + 0));   // v3
  aie::vector<bfloat16, 32> b = aie::load_v<32>((bfloat16 *)(in + 16));  // p3
  aie::vector<bfloat16, 32> r = aie::add(a, b);
  aie::store_v((bfloat16 *)(out + 0), r);
}
"""

AIE_MLIR = """\
//===- aie.mlir ------------------------------------------------*- MLIR -*-===//
// Isolated single-add probe (GENERATED). Direct shim<->core, one compute tile.
// in: [a(32 bf16) | b(32 bf16)] = 32 i32 ; out: r(32 bf16) = 16 i32.
//===----------------------------------------------------------------------===//

module {
  aie.device(npu1_1col) {
    func.func private @h4_probe(memref<32xi32>, memref<16xi32>)
        attributes {link_with = "kernel.o"}

    %shim = aie.tile(0, 0)
    %core = aie.tile(0, 2)

    aie.objectfifo @inF(%shim, {%core}, 2 : i32) : !aie.objectfifo<memref<32xi32>>
    aie.objectfifo @outF(%core, {%shim}, 2 : i32) : !aie.objectfifo<memref<16xi32>>

    %core_0_2 = aie.core(%core) {
      %si = aie.objectfifo.acquire @inF(Consume, 1) : !aie.objectfifosubview<memref<32xi32>>
      %i = aie.objectfifo.subview.access %si[0] : !aie.objectfifosubview<memref<32xi32>> -> memref<32xi32>
      %so = aie.objectfifo.acquire @outF(Produce, 1) : !aie.objectfifosubview<memref<16xi32>>
      %o = aie.objectfifo.subview.access %so[0] : !aie.objectfifosubview<memref<16xi32>> -> memref<16xi32>

      func.call @h4_probe(%i, %o) : (memref<32xi32>, memref<16xi32>) -> ()

      aie.objectfifo.release @inF(Consume, 1)
      aie.objectfifo.release @outF(Produce, 1)
      aie.end
    }

    aie.runtime_sequence @sequence(%in: memref<32xi32>, %out: memref<16xi32>) {
      aiex.npu.dma_memcpy_nd(%in[0, 0, 0, 0][1, 1, 1, 32][0, 0, 0, 1]) {id = 0 : i64, metadata = @inF} : memref<32xi32>
      aiex.npu.dma_memcpy_nd(%out[0, 0, 0, 0][1, 1, 1, 16][0, 0, 0, 1]) {id = 1 : i64, metadata = @outF} : memref<16xi32>
      aiex.npu.dma_wait {symbol = @outF}
    }
  }
}
"""

RUN_LIT = """\
// (c) Copyright 2026 -- xdna-emu h4-isolated chained-NaN classifier.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// REQUIRES: ryzen_ai_npu1, peano
//
// RUN: %PEANO_INSTALL_DIR/bin/clang++ --target=aie2-none-unknown-elf -O2 -std=c++20 -I %aietools/include -c %S/kernel.cc -o ./kernel.o
// RUN: aiecc --no-xchesscc --no-xbridge --aie-generate-xclbin --xclbin-name=aie.xclbin --aie-generate-npu-insts --npu-insts-name=insts.bin %S/aie.mlir
// RUN: clang %S/test.cpp -o test.exe -std=c++17 -Wall %xrt_flags -lrt -lstdc++ %test_utils_flags
// RUN: %run_on_npu1% ./test.exe -x aie.xclbin -k MLIR_AIE -i insts.bin
"""


def test_cpp(a_vec, b_vec):
    inp = a_vec + b_vec  # 64 u16
    arr = ", ".join(str(x) for x in inp)
    return f"""\
//===- test.cpp -------------------------------------------------*- C++ -*-===//
// Host harness for the isolated h4 single-add classifier (GENERATED). Feeds
// h4's exact (v3, p3) vectors; dumps output; flags lane29.
//===----------------------------------------------------------------------===//

#include <algorithm>
#include <cstdint>
#include <cstring>
#include <fstream>
#include <iostream>
#include <vector>

#include "xrt/xrt_bo.h"
#include "xrt/xrt_device.h"
#include "xrt/xrt_kernel.h"

#include "test_utils.h"

static constexpr int NIN = 64;   // 32 i32 input  (a|b)
static constexpr int NOUT = 32;  // 16 i32 output (r)
static const uint16_t INP[NIN] = {{ {arr} }};

int main(int argc, const char *argv[]) {{
  std::vector<uint32_t> instr_v = test_utils::load_instr_binary("insts.bin");
  unsigned int device_index = 0;
  auto device = xrt::device(device_index);
  std::string xclbin_name = "aie.xclbin";
  xrt::xclbin xclbin(xclbin_name);
  std::string Node = "MLIR_AIE";
  auto xkernels = xclbin.get_kernels();
  auto xkernel = *std::find_if(xkernels.begin(), xkernels.end(),
      [Node](xrt::xclbin::kernel &k) {{ return k.get_name().rfind(Node, 0) == 0; }});
  auto kernelName = xkernel.get_name();
  device.register_xclbin(xclbin);
  xrt::hw_context context(device, xclbin.get_uuid());
  auto kernel = xrt::kernel(context, kernelName);

  auto bo_instr = xrt::bo(device, instr_v.size() * sizeof(int), XCL_BO_FLAGS_CACHEABLE, kernel.group_id(1));
  auto bo_in = xrt::bo(device, NIN * sizeof(uint16_t), XRT_BO_FLAGS_HOST_ONLY, kernel.group_id(3));
  auto bo_out = xrt::bo(device, NOUT * sizeof(uint16_t), XRT_BO_FLAGS_HOST_ONLY, kernel.group_id(4));

  uint16_t *bufIn = bo_in.map<uint16_t *>();
  uint16_t *bufOut = bo_out.map<uint16_t *>();
  std::memcpy(bufIn, INP, NIN * sizeof(uint16_t));
  std::memset(bufOut, 0, NOUT * sizeof(uint16_t));
  std::memcpy(bo_instr.map<void *>(), instr_v.data(), instr_v.size() * sizeof(int));

  bo_instr.sync(XCL_BO_SYNC_BO_TO_DEVICE);
  bo_in.sync(XCL_BO_SYNC_BO_TO_DEVICE);
  bo_out.sync(XCL_BO_SYNC_BO_TO_DEVICE);

  unsigned int opcode = 3;
  auto run = kernel(opcode, bo_instr, instr_v.size(), bo_in, bo_out);
  if (run.wait() != ERT_CMD_STATE_COMPLETED) {{ std::cout << "Kernel did not complete\\n"; return 1; }}
  bo_out.sync(XCL_BO_SYNC_BO_FROM_DEVICE);

  uint16_t l29 = bufOut[29];
  std::ofstream dump("out.txt");
  for (int i = 0; i < NOUT; i++) dump << (uint32_t)bufOut[i] << "\\n";
  std::cout << "\\nh4-isolated: lane29 = 0x" << std::hex << l29 << std::dec << "\\n";
  std::cout << "  0xFF8C => cross-lane vector context;  0xFF81 => preceding-instruction state\\n";
  std::cout << "\\nPASS!\\n\\n";
  return 0;
}}
"""


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    a = load_v3_from_outtxt()
    b = load_p3_from_pool()
    assert a[29] == 0x7F80, f"v3[29] expected 0x7F80, got 0x{a[29]:04X}"
    assert b[29] == 0xFFC6, f"p3[29] expected 0xFFC6, got 0x{b[29]:04X}"
    with open(os.path.join(OUT_DIR, "kernel.cc"), "w") as f:
        f.write(KERNEL_CC)
    with open(os.path.join(OUT_DIR, "aie.mlir"), "w") as f:
        f.write(AIE_MLIR)
    with open(os.path.join(OUT_DIR, "run.lit"), "w") as f:
        f.write(RUN_LIT)
    with open(os.path.join(OUT_DIR, "test.cpp"), "w") as f:
        f.write(test_cpp(a, b))
    print(f"Wrote h4-isolated probe -> {OUT_DIR}")
    print(f"  a=v3[29]=0x{a[29]:04X}  b=p3[29]=0x{b[29]:04X}  (expect HW/aiesim lane29 = 0xFF8C if cross-lane)")


if __name__ == "__main__":
    main()
