#!/usr/bin/env python3
"""Chained-state isolation probe for the bf16 special-value add divergence.

Background
----------
The dense single-op sweep proves bf16 `aie::add(+Inf, -NaN(m))` collapses to
mantissa 1 on silicon for every payload m. Yet vector-fuzzer seed 6159 shows
the SAME operands, inside a chain, producing a COMPUTED significand
(+Inf + -NaN(0x46) -> -NaN(0x0C)). The chain stage was `add(add(+Inf,
0x7F7F), -NaN(m))` -- i.e. a `vadd.f` ran on the lane immediately before. This
probe isolates what about the preceding op flips collapse -> compute.

Kernel: out = aie::add(aie::add(a, c), b), three input operands per lane.

Blocks (m = 1..127), all with b = -NaN(m):
  1 inf_plus_max  : a=+Inf, c=0x7F7F(max normal)  -- reproduces seed 6159's h3.
  2 inf_plus_zero : a=+Inf, c=+0                   -- first op = clean +Inf.
  3 max_plus_max  : a=0x7F7F, c=0x7F7F             -- first op = finite overflow.
  4 inf_plus_inf  : a=+Inf, c=+Inf                 -- first op = Inf+Inf.

Compare each block's result to the dense single-op `add(+Inf, -NaN(m))`
(= collapse). Whichever blocks COMPUTE instead localize the trigger:
  - only 1 & 3 compute  -> overflow / "dirty Inf" sticky-bit effect;
  - 1,2,3,4 all compute -> any preceding vadd.f taints the next (pure state);
  - all collapse        -> the trigger needs more chain context than one op.

OFFLINE authoring only -- runs no hardware, touches no interpreter code.
"""

from __future__ import annotations

import os

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TESTS_DIR = os.path.join(REPO, "tests", "vector-verify")
EXP_DIR = os.path.join(REPO, "build", "experiments", "special-value-dense")
NAME = "vec_chain_state_probe"
LANES = 32

INF = 0x7F80
MAXNORM = 0x7F7F  # largest finite bf16


def nan(sign: int, m: int) -> int:
    return (sign << 15) | INF | (m & 0x7F)


def build():
    A, C, B = [], [], []

    def add(a, c, b):
        A.append(a)
        C.append(c)
        B.append(b)

    for m in range(1, 128):  # block 1: inf + max
        add(INF, MAXNORM, nan(1, m))
    for m in range(1, 128):  # block 2: inf + zero
        add(INF, 0x0000, nan(1, m))
    for m in range(1, 128):  # block 3: max + max (finite overflow)
        add(MAXNORM, MAXNORM, nan(1, m))
    for m in range(1, 128):  # block 4: inf + inf
        add(INF, INF, nan(1, m))

    while len(A) % LANES != 0:
        add(0, 0, 0)
    return A, C, B


BLOCKS = ["inf_plus_max", "inf_plus_zero", "max_plus_max", "inf_plus_inf"]


def fmt(name, vals):
    return f"static const uint16_t {name}[{len(vals)}] = {{\n    " + ", ".join(map(str, vals)) + ",\n};\n"


def kernel_cc(n):
    # Single concatenated input buffer [a | c | b] (3*n) -> the shim only has
    # two MM2S channels, so three separate input fifos overflow it.
    return f"""\
//===- kernel.cc ------------------------------------------------*- C++ -*-===//
// Chained-state isolation probe (GENERATED by tools/gen_chain_state_probe.py).
// out = aie::add(aie::add(a, c), b). Operands a,c,b are concatenated regions of
// one input buffer (in[0..N)=a, in[N..2N)=c, in[2N..3N)=b) to fit the shim's
// two MM2S DMA channels.
//===----------------------------------------------------------------------===//

#include <stdint.h>
#include <aie_api/aie.hpp>

#define SWEEP_N {n}

using V = aie::vector<bfloat16, 32>;
// Two SEPARATE noinline adds, matching the fuzzer chain's h3/h4 structure: the
// intermediate is narrowed to bf16 and re-widened across the call boundary
// (vconv.bf16.fp32 -> store/return -> vconv.fp32.bf16), rather than kept in an
// fp32 accumulator as a single inlined `add(add(...))` would.
__attribute__((noinline)) static V h_add(V a, V b) {{ return aie::add(a, b); }}

extern "C" {{

void chain_probe(bfloat16 *restrict in, bfloat16 *restrict o) {{
  event0();
  bfloat16 *a = in;
  bfloat16 *c = in + SWEEP_N;
  bfloat16 *b = in + 2 * SWEEP_N;
  for (int i = 0; i < SWEEP_N; i += 32) {{
    V va = aie::load_v<32>(a + i);
    V vc = aie::load_v<32>(c + i);
    V vb = aie::load_v<32>(b + i);
    V t = h_add(va, vc);
    aie::store_v(o + i, h_add(t, vb));
  }}
  event1();
}}

}} // extern "C"
"""


def aie_mlir(n):
    n3 = 3 * n
    mri = f"memref<{n3}xbf16>"
    mro = f"memref<{n}xbf16>"
    return f"""\
//===- aie.mlir ------------------------------------------------*- MLIR -*-===//
// Chained-state isolation probe (GENERATED). One {n3}-element bf16 input
// [a|c|b], one {n}-element output; out = add(add(a,c), b).
//===----------------------------------------------------------------------===//

module {{
  aie.device(npu1_1col) {{
    func.func private @chain_probe({mri}, {mro})
        attributes {{link_with = "kernel.o"}}

    %shim = aie.tile(0, 0)
    %core = aie.tile(0, 2)

    aie.objectfifo @inA(%shim, {{%core}}, 2 : i32) : !aie.objectfifo<{mri}>
    aie.objectfifo @outO(%core, {{%shim}}, 2 : i32) : !aie.objectfifo<{mro}>

    %core_0_2 = aie.core(%core) {{
      %sa = aie.objectfifo.acquire @inA(Consume, 1) : !aie.objectfifosubview<{mri}>
      %a = aie.objectfifo.subview.access %sa[0] : !aie.objectfifosubview<{mri}> -> {mri}
      %so = aie.objectfifo.acquire @outO(Produce, 1) : !aie.objectfifosubview<{mro}>
      %o = aie.objectfifo.subview.access %so[0] : !aie.objectfifosubview<{mro}> -> {mro}

      func.call @chain_probe(%a, %o) : ({mri}, {mro}) -> ()

      aie.objectfifo.release @inA(Consume, 1)
      aie.objectfifo.release @outO(Produce, 1)
      aie.end
    }}

    aie.runtime_sequence @sequence(%a: {mri}, %o: {mro}) {{
      aiex.npu.dma_memcpy_nd(%a[0, 0, 0, 0][1, 1, 1, {n3}][0, 0, 0, 1]) {{id = 0 : i64, metadata = @inA}} : {mri}
      aiex.npu.dma_memcpy_nd(%o[0, 0, 0, 0][1, 1, 1, {n}][0, 0, 0, 1]) {{id = 1 : i64, metadata = @outO}} : {mro}
      aiex.npu.dma_wait {{symbol = @outO}}
    }}
  }}
}}
"""


RUN_LIT = """\
// (c) Copyright 2026 -- xdna-emu chained-state special-value probe.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// REQUIRES: ryzen_ai_npu1, peano
//
// RUN: %PEANO_INSTALL_DIR/bin/clang++ --target=aie2-none-unknown-elf -O2 -std=c++20 -I %aietools/include -c %S/kernel.cc -o ./kernel.o
// RUN: aiecc --no-xchesscc --no-xbridge --aie-generate-xclbin --xclbin-name=aie.xclbin --aie-generate-npu-insts --npu-insts-name=insts.bin %S/aie.mlir
// RUN: clang %S/test.cpp -o test.exe -std=c++17 -Wall %xrt_flags -lrt -lstdc++ %test_utils_flags
// RUN: %run_on_npu1% ./test.exe -x aie.xclbin -k MLIR_AIE -i insts.bin
"""


def test_cpp(n, A, C, B):
    body = f"""\
//===- test.cpp -------------------------------------------------*- C++ -*-===//
// Host harness for the chained-state probe (GENERATED). Dumps per-lane
// (A_bits C_bits B_bits out_bits) to out.txt.
//===----------------------------------------------------------------------===//

#include <algorithm>
#include <cstdint>
#include <cstring>
#include <fstream>
#include <iostream>
#include <vector>

#include "xrt/xrt_bo.h"
#include "xrt/xrt_device.h"
#include "xrt/xrt_kernel.h"

#include "test_utils.h"

static constexpr int N = {n};
static constexpr int IN_N = 3 * {n};

__INALL__

int main(int argc, const char *argv[]) {{
  std::vector<uint32_t> instr_v = test_utils::load_instr_binary("insts.bin");
  unsigned int device_index = 0;
  auto device = xrt::device(device_index);
  std::string xclbin_name = "aie.xclbin";
  xrt::xclbin xclbin(xclbin_name);
  std::string Node = "MLIR_AIE";
  auto xkernels = xclbin.get_kernels();
  auto xkernel = *std::find_if(xkernels.begin(), xkernels.end(),
                               [Node](xrt::xclbin::kernel &k) {{
                                 return k.get_name().rfind(Node, 0) == 0;
                               }});
  auto kernelName = xkernel.get_name();
  device.register_xclbin(xclbin);
  xrt::hw_context context(device, xclbin.get_uuid());
  auto kernel = xrt::kernel(context, kernelName);

  auto bo_instr = xrt::bo(device, instr_v.size() * sizeof(int),
                          XCL_BO_FLAGS_CACHEABLE, kernel.group_id(1));
  auto bo_in = xrt::bo(device, IN_N * sizeof(uint16_t), XRT_BO_FLAGS_HOST_ONLY, kernel.group_id(3));
  auto bo_o = xrt::bo(device, N * sizeof(uint16_t), XRT_BO_FLAGS_HOST_ONLY, kernel.group_id(4));

  uint16_t *bufIn = bo_in.map<uint16_t *>();
  uint16_t *bufO = bo_o.map<uint16_t *>();

  std::memcpy(bufIn, INALL, IN_N * sizeof(uint16_t));
  std::memset(bufO, 0, N * sizeof(uint16_t));

  void *bufInstr = bo_instr.map<void *>();
  std::memcpy(bufInstr, instr_v.data(), instr_v.size() * sizeof(int));

  bo_instr.sync(XCL_BO_SYNC_BO_TO_DEVICE);
  bo_in.sync(XCL_BO_SYNC_BO_TO_DEVICE);
  bo_o.sync(XCL_BO_SYNC_BO_TO_DEVICE);

  unsigned int opcode = 3;
  auto run = kernel(opcode, bo_instr, instr_v.size(), bo_in, bo_o);
  ert_cmd_state r = run.wait();
  if (r != ERT_CMD_STATE_COMPLETED) {{
    std::cout << "Kernel did not complete. Status: " << r << "\\n";
    return 1;
  }}

  bo_o.sync(XCL_BO_SYNC_BO_FROM_DEVICE);

  {{
    std::ofstream dump("out.txt");
    for (int i = 0; i < N; i++)
      dump << (uint32_t)bufIn[i] << " " << (uint32_t)bufIn[N + i] << " "
           << (uint32_t)bufIn[2 * N + i] << " " << (uint32_t)bufO[i] << "\\n";
  }}

  std::cout << "\\nchain-state probe: " << N << " lanes dumped to out.txt.\\n\\nPASS!\\n\\n";
  return 0;
}}
"""
    return body.replace("__INALL__", fmt("INALL", A + C + B))


def main():
    A, C, B = build()
    n = len(A)
    out_dir = os.path.join(TESTS_DIR, NAME)
    os.makedirs(out_dir, exist_ok=True)
    os.makedirs(EXP_DIR, exist_ok=True)
    with open(os.path.join(out_dir, "kernel.cc"), "w") as f:
        f.write(kernel_cc(n))
    with open(os.path.join(out_dir, "aie.mlir"), "w") as f:
        f.write(aie_mlir(n))
    with open(os.path.join(out_dir, "run.lit"), "w") as f:
        f.write(RUN_LIT)
    with open(os.path.join(out_dir, "test.cpp"), "w") as f:
        f.write(test_cpp(n, A, C, B))
    with open(os.path.join(EXP_DIR, "probe_blocks.txt"), "w") as f:
        f.write(f"# {n} lanes, blocks of 127 (then pad). a c b per lane.\n")
        for i, (a, c, b) in enumerate(zip(A, C, B)):
            blk = BLOCKS[i // 127] if i // 127 < len(BLOCKS) else "pad"
            f.write(f"{i} {blk} {a} {c} {b}\n")
    print(f"Wrote {NAME}: {n} lanes -> {out_dir}")


if __name__ == "__main__":
    main()
