#!/usr/bin/env python3
"""Generate DENSE bf16/fp32 add/sub special-value sweeps for silicon capture.

Why this exists
---------------
The original 16-class sweep (tools/gen_nan_inf_sweep.py) used only three NaN
payloads (0x40, 0x20, 0x55) -- too sparse to pin the special-value datapath.
This tool emits, for each of the four (type, op) combos, a single-op
`aie::add`/`aie::sub` kernel over a dense operand matrix that samples the full
7-bit (bf16) / top-7-mantissa (fp32) NaN payload space across Inf+NaN (all
sign combos, both operand orders) and NaN+NaN (anchor payloads x all 127).

The single op is the SAME instruction the production chains compile to
(vconv -> vadd.f/vsub.f r0=0x1c -> vconv), so the genuine datapath rule reads
off the silicon dump. The emulator already matches bf16-add 2048/2048; these
sweeps bank that as exhaustive regression goldens and extend it to sub + fp32.

Capture flow
------------
  python3 tools/gen_special_value_dense.py     # emit four kernel dirs + matrices
  # stage each into mlir-aie/test/npu-xrt and run the bridge harness (HW),
  # then read out.txt (A_bits B_bits hw_out_bits per lane).

OFFLINE authoring only -- runs no hardware, touches no interpreter code.
"""

from __future__ import annotations

import os
from dataclasses import dataclass

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TESTS_DIR = os.path.join(REPO, "tests", "vector-verify")
EXP_DIR = os.path.join(REPO, "build", "experiments", "special-value-dense")


@dataclass(frozen=True)
class DType:
    name: str           # "bf16" / "fp32"
    ctype: str          # AIE element C type
    mlir: str           # MLIR element type
    lanes: int          # vector width (512-bit / element size)
    utype: str          # host staging integer type
    sign_bit: int       # sign-bit position
    inf_bits: int       # +Inf bit pattern
    payload_shift: int  # where a 7-bit payload lands in the mantissa


BF16 = DType("bf16", "bfloat16", "bf16", 32, "uint16_t", 15, 0x7F80, 0)
FP32 = DType("fp32", "float", "f32", 16, "uint32_t", 31, 0x7F800000, 16)


def inf(dt: DType, sign: int) -> int:
    return (sign << dt.sign_bit) | dt.inf_bits


def nan(dt: DType, sign: int, m: int) -> int:
    return (sign << dt.sign_bit) | dt.inf_bits | ((m & 0x7F) << dt.payload_shift)


def build_matrix(dt: DType) -> tuple[list[int], list[int]]:
    A: list[int] = []
    B: list[int] = []

    def add(a: int, b: int) -> None:
        A.append(a)
        B.append(b)

    # Block 1 -- Inf + NaN(m), every payload, all four sign combos.
    for m in range(1, 128):
        add(inf(dt, 0), nan(dt, 0, m))
        add(inf(dt, 0), nan(dt, 1, m))
        add(inf(dt, 1), nan(dt, 0, m))
        add(inf(dt, 1), nan(dt, 1, m))

    # Block 2 -- NaN(m) + Inf (operand order swapped), both NaN signs.
    for m in range(1, 128):
        add(nan(dt, 0, m), inf(dt, 0))
        add(nan(dt, 1, m), inf(dt, 0))

    # Block 3 -- NaN(m1) + NaN(m2): anchor payloads swept against all m2.
    for m1 in (0x01, 0x40, 0x46, 0x55, 0x7F):
        for m2 in range(1, 128):
            add(nan(dt, 0, m1), nan(dt, 1, m2))  # opposite sign
            add(nan(dt, 0, m1), nan(dt, 0, m2))  # same sign

    while len(A) % dt.lanes != 0:
        add(0, 0)
    return A, B


def fmt_array(name: str, utype: str, vals: list[int]) -> str:
    body = ", ".join(str(v) for v in vals)
    return f"static const {utype} {name}[{len(vals)}] = {{\n    {body},\n}};\n"


def kernel_cc(dt: DType, n: int, op: str) -> str:
    return f"""\
//===- kernel.cc ------------------------------------------------*- C++ -*-===//
//
// DENSE {dt.name} special-value {op} sweep capture kernel (GENERATED by
// tools/gen_special_value_dense.py). Single op (aie::{op}) repeated across a
// dense Inf/NaN operand matrix -- no pipeline-adjacency confound. Inputs and
// outputs are staged as raw bit patterns; the signature uses the real element
// type so the DMA moves bytes verbatim (NaN!=NaN-safe bit-exact compare).
//
//===----------------------------------------------------------------------===//

#include <stdint.h>

#include <aie_api/aie.hpp>

#define SWEEP_N {n}

using V = aie::vector<{dt.ctype}, {dt.lanes}>;
__attribute__((noinline)) static V vop(V a, V b) {{ return aie::{op}(a, b); }}

extern "C" {{

void {op}_{dt.name}({dt.ctype} *restrict a, {dt.ctype} *restrict b,
              {dt.ctype} *restrict c) {{
  event0();
  for (int i = 0; i < SWEEP_N; i += {dt.lanes}) {{
    aie::vector<{dt.ctype}, {dt.lanes}> va = aie::load_v<{dt.lanes}>(a + i);
    aie::vector<{dt.ctype}, {dt.lanes}> vb = aie::load_v<{dt.lanes}>(b + i);
    aie::vector<{dt.ctype}, {dt.lanes}> vc = vop(va, vb);
    aie::store_v(c + i, vc);
  }}
  event1();
}}

}} // extern "C"
"""


def aie_mlir(dt: DType, n: int, op: str) -> str:
    fn = f"{op}_{dt.name}"
    mr = f"memref<{n}x{dt.mlir}>"
    return f"""\
//===- aie.mlir ------------------------------------------------*- MLIR -*-===//
//
// DENSE {dt.name} special-value {op} sweep (GENERATED). Single compute tile
// (0,2) reads two {n}-element {dt.mlir} operand matrices from DDR via shim DMA,
// runs {fn}, writes the {n}-element result back.
//
//===----------------------------------------------------------------------===//

module {{
  aie.device(npu1_1col) {{
    func.func private @{fn}({mr}, {mr}, {mr})
        attributes {{link_with = "kernel.o"}}

    %shim = aie.tile(0, 0)
    %core = aie.tile(0, 2)

    aie.objectfifo @inA(%shim, {{%core}}, 2 : i32) : !aie.objectfifo<{mr}>
    aie.objectfifo @inB(%shim, {{%core}}, 2 : i32) : !aie.objectfifo<{mr}>
    aie.objectfifo @outC(%core, {{%shim}}, 2 : i32) : !aie.objectfifo<{mr}>

    %core_0_2 = aie.core(%core) {{
      %sa = aie.objectfifo.acquire @inA(Consume, 1) : !aie.objectfifosubview<{mr}>
      %a = aie.objectfifo.subview.access %sa[0] : !aie.objectfifosubview<{mr}> -> {mr}
      %sb = aie.objectfifo.acquire @inB(Consume, 1) : !aie.objectfifosubview<{mr}>
      %b = aie.objectfifo.subview.access %sb[0] : !aie.objectfifosubview<{mr}> -> {mr}
      %so = aie.objectfifo.acquire @outC(Produce, 1) : !aie.objectfifosubview<{mr}>
      %o = aie.objectfifo.subview.access %so[0] : !aie.objectfifosubview<{mr}> -> {mr}

      func.call @{fn}(%a, %b, %o) : ({mr}, {mr}, {mr}) -> ()

      aie.objectfifo.release @inA(Consume, 1)
      aie.objectfifo.release @inB(Consume, 1)
      aie.objectfifo.release @outC(Produce, 1)
      aie.end
    }}

    aie.runtime_sequence @sequence(%a: {mr}, %b: {mr}, %c: {mr}) {{
      aiex.npu.dma_memcpy_nd(%a[0, 0, 0, 0][1, 1, 1, {n}][0, 0, 0, 1]) {{id = 0 : i64, metadata = @inA}} : {mr}
      aiex.npu.dma_memcpy_nd(%b[0, 0, 0, 0][1, 1, 1, {n}][0, 0, 0, 1]) {{id = 1 : i64, metadata = @inB}} : {mr}
      aiex.npu.dma_memcpy_nd(%c[0, 0, 0, 0][1, 1, 1, {n}][0, 0, 0, 1]) {{id = 2 : i64, metadata = @outC}} : {mr}
      aiex.npu.dma_wait {{symbol = @outC}}
    }}
  }}
}}
"""


RUN_LIT = """\
// (c) Copyright 2026 -- xdna-emu special-value DENSE silicon sweep.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// REQUIRES: ryzen_ai_npu1, peano
//
// RUN: %PEANO_INSTALL_DIR/bin/clang++ --target=aie2-none-unknown-elf -O2 -std=c++20 -I %aietools/include -c %S/kernel.cc -o ./kernel.o
// RUN: aiecc --no-xchesscc --no-xbridge --aie-generate-xclbin --xclbin-name=aie.xclbin --aie-generate-npu-insts --npu-insts-name=insts.bin %S/aie.mlir
// RUN: clang %S/test.cpp -o test.exe -std=c++17 -Wall %xrt_flags -lrt -lstdc++ %test_utils_flags
// RUN: %run_on_npu1% ./test.exe -x aie.xclbin -k MLIR_AIE -i insts.bin
"""


def test_cpp(dt: DType, n: int, op: str, A: list[int], B: list[int]) -> str:
    body = f"""\
//===- test.cpp -------------------------------------------------*- C++ -*-===//
//
// Host harness for the DENSE {dt.name} special-value {op} sweep (GENERATED by
// tools/gen_special_value_dense.py). Stages the dense operand matrix as raw bit
// patterns, launches, and DUMPS per-lane (A_bits B_bits hw_out_bits) to
// out.txt -- the ground-truth artifact. No EMU golden (always "passes").
//
//===----------------------------------------------------------------------===//

#include <algorithm>
#include <cstdint>
#include <cstring>
#include <fstream>
#include <iostream>
#include <vector>

#include "xrt/xrt_bo.h"
#include "xrt/xrt_device.h"
#include "xrt/xrt_kernel.h"

#include "test_utils.h"

static constexpr int N = {n};

__INA__
__INB__

int main(int argc, const char *argv[]) {{
  std::vector<uint32_t> instr_v = test_utils::load_instr_binary("insts.bin");

  unsigned int device_index = 0;
  auto device = xrt::device(device_index);

  std::string xclbin_name = "aie.xclbin";
  xrt::xclbin xclbin(xclbin_name);
  std::string Node = "MLIR_AIE";

  auto xkernels = xclbin.get_kernels();
  auto xkernel = *std::find_if(xkernels.begin(), xkernels.end(),
                               [Node](xrt::xclbin::kernel &k) {{
                                 return k.get_name().rfind(Node, 0) == 0;
                               }});
  auto kernelName = xkernel.get_name();

  device.register_xclbin(xclbin);
  xrt::hw_context context(device, xclbin.get_uuid());
  auto kernel = xrt::kernel(context, kernelName);

  auto bo_instr = xrt::bo(device, instr_v.size() * sizeof(int),
                          XCL_BO_FLAGS_CACHEABLE, kernel.group_id(1));
  auto bo_a = xrt::bo(device, N * sizeof({dt.utype}), XRT_BO_FLAGS_HOST_ONLY, kernel.group_id(3));
  auto bo_b = xrt::bo(device, N * sizeof({dt.utype}), XRT_BO_FLAGS_HOST_ONLY, kernel.group_id(4));
  auto bo_c = xrt::bo(device, N * sizeof({dt.utype}), XRT_BO_FLAGS_HOST_ONLY, kernel.group_id(5));

  {dt.utype} *bufA = bo_a.map<{dt.utype} *>();
  {dt.utype} *bufB = bo_b.map<{dt.utype} *>();
  {dt.utype} *bufC = bo_c.map<{dt.utype} *>();

  std::memcpy(bufA, INA, N * sizeof({dt.utype}));
  std::memcpy(bufB, INB, N * sizeof({dt.utype}));
  std::memset(bufC, 0, N * sizeof({dt.utype}));

  void *bufInstr = bo_instr.map<void *>();
  std::memcpy(bufInstr, instr_v.data(), instr_v.size() * sizeof(int));

  bo_instr.sync(XCL_BO_SYNC_BO_TO_DEVICE);
  bo_a.sync(XCL_BO_SYNC_BO_TO_DEVICE);
  bo_b.sync(XCL_BO_SYNC_BO_TO_DEVICE);
  bo_c.sync(XCL_BO_SYNC_BO_TO_DEVICE);

  unsigned int opcode = 3;
  auto run = kernel(opcode, bo_instr, instr_v.size(), bo_a, bo_b, bo_c);
  ert_cmd_state r = run.wait();
  if (r != ERT_CMD_STATE_COMPLETED) {{
    std::cout << "Kernel did not complete. Status: " << r << "\\n";
    return 1;
  }}

  bo_c.sync(XCL_BO_SYNC_BO_FROM_DEVICE);

  {{
    std::ofstream dump("out.txt");
    for (int i = 0; i < N; i++)
      dump << (uint64_t)bufA[i] << " "
           << (uint64_t)bufB[i] << " "
           << (uint64_t)bufC[i] << "\\n";
  }}

  std::cout << "\\nDENSE {dt.name} special-value {op} sweep: " << N
            << " lanes dumped to out.txt.\\n\\nPASS!\\n\\n";
  return 0;
}}
"""
    return body.replace("__INA__", fmt_array("INA", dt.utype, A)).replace(
        "__INB__", fmt_array("INB", dt.utype, B)
    )


def emit(dt: DType, op: str) -> None:
    A, B = build_matrix(dt)
    n = len(A)
    name = f"vec_nan_{dt.name}_dense_{op}"
    out_dir = os.path.join(TESTS_DIR, name)
    os.makedirs(out_dir, exist_ok=True)
    os.makedirs(EXP_DIR, exist_ok=True)

    with open(os.path.join(out_dir, "kernel.cc"), "w") as f:
        f.write(kernel_cc(dt, n, op))
    with open(os.path.join(out_dir, "aie.mlir"), "w") as f:
        f.write(aie_mlir(dt, n, op))
    with open(os.path.join(out_dir, "run.lit"), "w") as f:
        f.write(RUN_LIT)
    with open(os.path.join(out_dir, "test.cpp"), "w") as f:
        f.write(test_cpp(dt, n, op, A, B))
    with open(os.path.join(EXP_DIR, f"matrix_{dt.name}_{op}.txt"), "w") as f:
        for a, b in zip(A, B):
            f.write(f"{a} {b}\n")
    print(f"Wrote {name}: {n} lanes ({dt.lanes}/vec) -> {out_dir}")


def main() -> None:
    for dt in (BF16, FP32):
        for op in ("add", "sub"):
            emit(dt, op)


if __name__ == "__main__":
    main()
