#!/usr/bin/env python3
"""Re-author vector-fuzzer seed 6159 as a CLEAN single-tile kernel for aiesim.

The banked seed's fuzzer-generated aie.mlir uses a memtile-relay objectfifo
topology whose CDO lock init isn't reproduced by the raw FFI path (it wedges
AcquiringLock at the placed column). The COMPUTE -- h0..h7, the exact bf16 op
chain whose stage-4 add diverges (HW 0xFF8C vs interpreter 0xFF81) -- lives
entirely on one compute core and is topology-independent. This re-authors that
same compute as a direct shim<->core kernel (the topology the dense probes use,
which runs cleanly through the FFI/plugin and thus through the aiesim bridge),
fed with the seed's exact input pool.

Emits tests/vector-verify/vec_seed6159_clean/. Compile+HW-verify via the bridge
harness; then run its aie.xclbin through the aiesim bridge to see whether AMD's
model reproduces 0xFF8C.

OFFLINE authoring only.
"""

import os
import struct

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SEED_DIR = "/home/triple/npu-work/experiments/phoenix-survival/vector/seed_6159"
POOL_BIN = os.path.join(REPO, "build/experiments/bf16-nan-replay/pools/pool_seed_6159.bin")
OUT_DIR = os.path.join(REPO, "tests/vector-verify/vec_seed6159_clean")

N_I32 = 128  # in/out buffer size in int32 (8 slices of 32 bf16)


def load_pool_u16():
    p = open(POOL_BIN, "rb").read()
    p = p + bytes(N_I32 * 4 - len(p))  # pad to 512 bytes
    return [struct.unpack_from("<H", p, i * 2)[0] for i in range(N_I32 * 2)]


def kernel_cc():
    # The seed's compute verbatim (entry fuzz_kernel(int32_t* in, int32_t* out)).
    body = open(os.path.join(SEED_DIR, "fuzz_kernel.cc")).read()
    return body


AIE_MLIR = """\
//===- aie.mlir ------------------------------------------------*- MLIR -*-===//
// CLEAN single-tile re-author of vfuzz seed 6159 (GENERATED by
// tools/gen_seed6159_clean.py). Direct shim<->core objectfifos, no memtile, no
// trace -- so the FFI/aiesim path runs it without the memtile-lock wedge.
//===----------------------------------------------------------------------===//

module {
  aie.device(npu1_1col) {
    func.func private @fuzz_kernel(memref<128xi32>, memref<128xi32>)
        attributes {link_with = "kernel.o"}

    %shim = aie.tile(0, 0)
    %core = aie.tile(0, 2)

    aie.objectfifo @inF(%shim, {%core}, 2 : i32) : !aie.objectfifo<memref<128xi32>>
    aie.objectfifo @outF(%core, {%shim}, 2 : i32) : !aie.objectfifo<memref<128xi32>>

    %core_0_2 = aie.core(%core) {
      %si = aie.objectfifo.acquire @inF(Consume, 1) : !aie.objectfifosubview<memref<128xi32>>
      %i = aie.objectfifo.subview.access %si[0] : !aie.objectfifosubview<memref<128xi32>> -> memref<128xi32>
      %so = aie.objectfifo.acquire @outF(Produce, 1) : !aie.objectfifosubview<memref<128xi32>>
      %o = aie.objectfifo.subview.access %so[0] : !aie.objectfifosubview<memref<128xi32>> -> memref<128xi32>

      func.call @fuzz_kernel(%i, %o) : (memref<128xi32>, memref<128xi32>) -> ()

      aie.objectfifo.release @inF(Consume, 1)
      aie.objectfifo.release @outF(Produce, 1)
      aie.end
    }

    aie.runtime_sequence @sequence(%in: memref<128xi32>, %out: memref<128xi32>) {
      aiex.npu.dma_memcpy_nd(%in[0, 0, 0, 0][1, 1, 1, 128][0, 0, 0, 1]) {id = 0 : i64, metadata = @inF} : memref<128xi32>
      aiex.npu.dma_memcpy_nd(%out[0, 0, 0, 0][1, 1, 1, 128][0, 0, 0, 1]) {id = 1 : i64, metadata = @outF} : memref<128xi32>
      aiex.npu.dma_wait {symbol = @outF}
    }
  }
}
"""

RUN_LIT = """\
// (c) Copyright 2026 -- xdna-emu seed-6159 clean single-tile re-author.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// REQUIRES: ryzen_ai_npu1, peano
//
// RUN: %PEANO_INSTALL_DIR/bin/clang++ --target=aie2-none-unknown-elf -O2 -std=c++20 -I %aietools/include -c %S/kernel.cc -o ./kernel.o
// RUN: aiecc --no-xchesscc --no-xbridge --aie-generate-xclbin --xclbin-name=aie.xclbin --aie-generate-npu-insts --npu-insts-name=insts.bin %S/aie.mlir
// RUN: clang %S/test.cpp -o test.exe -std=c++17 -Wall %xrt_flags -lrt -lstdc++ %test_utils_flags
// RUN: %run_on_npu1% ./test.exe -x aie.xclbin -k MLIR_AIE -i insts.bin
"""


def test_cpp(pool_u16):
    arr = ", ".join(str(x) for x in pool_u16)
    return f"""\
//===- test.cpp -------------------------------------------------*- C++ -*-===//
// Host harness for the clean seed-6159 re-author (GENERATED). Feeds the seed's
// input pool, runs, dumps per-lane output; flags lane29/slice4 (the divergent
// lane: HW 0xFF8C, interpreter 0xFF81).
//===----------------------------------------------------------------------===//

#include <algorithm>
#include <cstdint>
#include <cstring>
#include <fstream>
#include <iostream>
#include <vector>

#include "xrt/xrt_bo.h"
#include "xrt/xrt_device.h"
#include "xrt/xrt_kernel.h"

#include "test_utils.h"

static constexpr int NU16 = 256;  // 128 int32
static const uint16_t POOL[NU16] = {{ {arr} }};

int main(int argc, const char *argv[]) {{
  std::vector<uint32_t> instr_v = test_utils::load_instr_binary("insts.bin");
  unsigned int device_index = 0;
  auto device = xrt::device(device_index);
  std::string xclbin_name = "aie.xclbin";
  xrt::xclbin xclbin(xclbin_name);
  std::string Node = "MLIR_AIE";
  auto xkernels = xclbin.get_kernels();
  auto xkernel = *std::find_if(xkernels.begin(), xkernels.end(),
      [Node](xrt::xclbin::kernel &k) {{ return k.get_name().rfind(Node, 0) == 0; }});
  auto kernelName = xkernel.get_name();
  device.register_xclbin(xclbin);
  xrt::hw_context context(device, xclbin.get_uuid());
  auto kernel = xrt::kernel(context, kernelName);

  auto bo_instr = xrt::bo(device, instr_v.size() * sizeof(int), XCL_BO_FLAGS_CACHEABLE, kernel.group_id(1));
  auto bo_in = xrt::bo(device, NU16 * sizeof(uint16_t), XRT_BO_FLAGS_HOST_ONLY, kernel.group_id(3));
  auto bo_out = xrt::bo(device, NU16 * sizeof(uint16_t), XRT_BO_FLAGS_HOST_ONLY, kernel.group_id(4));

  uint16_t *bufIn = bo_in.map<uint16_t *>();
  uint16_t *bufOut = bo_out.map<uint16_t *>();
  std::memcpy(bufIn, POOL, NU16 * sizeof(uint16_t));
  std::memset(bufOut, 0, NU16 * sizeof(uint16_t));
  std::memcpy(bo_instr.map<void *>(), instr_v.data(), instr_v.size() * sizeof(int));

  bo_instr.sync(XCL_BO_SYNC_BO_TO_DEVICE);
  bo_in.sync(XCL_BO_SYNC_BO_TO_DEVICE);
  bo_out.sync(XCL_BO_SYNC_BO_TO_DEVICE);

  unsigned int opcode = 3;
  auto run = kernel(opcode, bo_instr, instr_v.size(), bo_in, bo_out);
  if (run.wait() != ERT_CMD_STATE_COMPLETED) {{ std::cout << "Kernel did not complete\\n"; return 1; }}
  bo_out.sync(XCL_BO_SYNC_BO_FROM_DEVICE);

  uint16_t l29s4 = bufOut[4 * 32 + 29];
  std::ofstream dump("out.txt");
  for (int i = 0; i < NU16; i++) dump << (uint32_t)bufOut[i] << "\\n";
  std::cout << "\\nseed6159 clean: slice4 lane29 = 0x" << std::hex << l29s4 << std::dec << "\\n";
  std::cout << "  (HW expect 0xFF8C; interpreter 0xFF81)\\n";
  std::cout << (l29s4 == 0xFF8C ? "REPRODUCES (0xFF8C)\\n" : "differs\\n");
  std::cout << "\\nPASS!\\n\\n";
  return 0;
}}
"""


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    pool = load_pool_u16()
    with open(os.path.join(OUT_DIR, "kernel.cc"), "w") as f:
        f.write(kernel_cc())
    with open(os.path.join(OUT_DIR, "aie.mlir"), "w") as f:
        f.write(AIE_MLIR)
    with open(os.path.join(OUT_DIR, "run.lit"), "w") as f:
        f.write(RUN_LIT)
    with open(os.path.join(OUT_DIR, "test.cpp"), "w") as f:
        f.write(test_cpp(pool))
    print(f"Wrote clean seed6159 kernel -> {OUT_DIR}")


if __name__ == "__main__":
    main()
