#!/usr/bin/env python3
"""Reusable single-add oracle harness for reverse-engineering the bf16 vadd.f
cross-lane NaN-payload function.

Emits tests/vector-verify/vec_add32_oracle/ -- a minimal one-tile kernel
out[0..31] = aie::add(a[0..31], b[0..31]) where a,b are two 32-lane bf16 vectors
read from a runtime input buffer. The host test.exe loads the input from a binary
file (default ./input.bin: 64 u16 LE = a||b) and dumps the 32-lane output to
./out.txt. Build the test.exe ONCE; then swap input.bin and rerun (HW, interpreter,
or aiesim) to probe how lane results depend on the full input vector.

OFFLINE authoring only.
"""

import os

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(REPO, "tests/vector-verify/vec_add32_oracle")

KERNEL_CC = """\
// Single-add oracle kernel (GENERATED by tools/gen_add32_oracle.py).
#include <stdint.h>
#include <aie_api/aie.hpp>

extern "C" void add32(int32_t *__restrict in, int32_t *__restrict out) {
  aie::vector<bfloat16, 32> a = aie::load_v<32>((bfloat16 *)(in + 0));   // lanes from in[0..15]
  aie::vector<bfloat16, 32> b = aie::load_v<32>((bfloat16 *)(in + 16));  // lanes from in[16..31]
  aie::vector<bfloat16, 32> r = aie::add(a, b);
  aie::store_v((bfloat16 *)(out + 0), r);
}
"""

AIE_MLIR = """\
//===- aie.mlir ---------------------------------------------*- MLIR -*-===//
// Single-add oracle (GENERATED). Direct shim<->core, one compute tile.
// in: [a(32 bf16) | b(32 bf16)] = 32 i32 ; out: r(32 bf16) = 16 i32.
//===--------------------------------------------------------------------===//

module {
  aie.device(npu1_1col) {
    func.func private @add32(memref<32xi32>, memref<16xi32>)
        attributes {link_with = "kernel.o"}

    %shim = aie.tile(0, 0)
    %core = aie.tile(0, 2)

    aie.objectfifo @inF(%shim, {%core}, 2 : i32) : !aie.objectfifo<memref<32xi32>>
    aie.objectfifo @outF(%core, {%shim}, 2 : i32) : !aie.objectfifo<memref<16xi32>>

    %core_0_2 = aie.core(%core) {
      %si = aie.objectfifo.acquire @inF(Consume, 1) : !aie.objectfifosubview<memref<32xi32>>
      %i = aie.objectfifo.subview.access %si[0] : !aie.objectfifosubview<memref<32xi32>> -> memref<32xi32>
      %so = aie.objectfifo.acquire @outF(Produce, 1) : !aie.objectfifosubview<memref<16xi32>>
      %o = aie.objectfifo.subview.access %so[0] : !aie.objectfifosubview<memref<16xi32>> -> memref<16xi32>

      func.call @add32(%i, %o) : (memref<32xi32>, memref<16xi32>) -> ()

      aie.objectfifo.release @inF(Consume, 1)
      aie.objectfifo.release @outF(Produce, 1)
      aie.end
    }

    aie.runtime_sequence @sequence(%in: memref<32xi32>, %out: memref<16xi32>) {
      aiex.npu.dma_memcpy_nd(%in[0, 0, 0, 0][1, 1, 1, 32][0, 0, 0, 1]) {id = 0 : i64, metadata = @inF} : memref<32xi32>
      aiex.npu.dma_memcpy_nd(%out[0, 0, 0, 0][1, 1, 1, 16][0, 0, 0, 1]) {id = 1 : i64, metadata = @outF} : memref<16xi32>
      aiex.npu.dma_wait {symbol = @outF}
    }
  }
}
"""

RUN_LIT = """\
// (c) Copyright 2026 -- xdna-emu single-add cross-lane oracle.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// REQUIRES: ryzen_ai_npu1, peano
//
// RUN: %PEANO_INSTALL_DIR/bin/clang++ --target=aie2-none-unknown-elf -O2 -std=c++20 -I %aietools/include -c %S/kernel.cc -o ./kernel.o
// RUN: aiecc --no-xchesscc --no-xbridge --aie-generate-xclbin --xclbin-name=aie.xclbin --aie-generate-npu-insts --npu-insts-name=insts.bin %S/aie.mlir
// RUN: clang %S/test.cpp -o test.exe -std=c++17 -Wall %xrt_flags -lrt -lstdc++ %test_utils_flags
// RUN: %run_on_npu1% ./test.exe -x aie.xclbin -k MLIR_AIE -i insts.bin
"""

TEST_CPP = """\
//===- test.cpp -------------------------------------------------*- C++ -*-===//
// Generic single-add oracle host (GENERATED). Reads 64 u16 (a||b) from a binary
// file (env ADD32_INPUT, default ./input.bin), runs, writes 32-lane output to
// ./out.txt. No baked data -- swap input.bin and rerun to probe the datapath.
//===----------------------------------------------------------------------===//

#include <algorithm>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <iostream>
#include <vector>

#include "xrt/xrt_bo.h"
#include "xrt/xrt_device.h"
#include "xrt/xrt_kernel.h"

#include "test_utils.h"

static constexpr int NIN = 64;   // 32 i32 input  (a|b)
static constexpr int NOUT = 32;  // 16 i32 output (r)

int main(int argc, const char *argv[]) {
  std::vector<uint32_t> instr_v = test_utils::load_instr_binary("insts.bin");

  // Load input vector (64 u16 LE).
  const char *inpath = std::getenv("ADD32_INPUT");
  std::string path = inpath ? inpath : "input.bin";
  std::vector<uint16_t> inbuf(NIN, 0);
  {
    std::ifstream f(path, std::ios::binary);
    if (!f) { std::cerr << "cannot open input " << path << "\\n"; return 2; }
    f.read(reinterpret_cast<char *>(inbuf.data()), NIN * sizeof(uint16_t));
  }

  unsigned int device_index = 0;
  auto device = xrt::device(device_index);
  std::string xclbin_name = "aie.xclbin";
  xrt::xclbin xclbin(xclbin_name);
  std::string Node = "MLIR_AIE";
  auto xkernels = xclbin.get_kernels();
  auto xkernel = *std::find_if(xkernels.begin(), xkernels.end(),
      [Node](xrt::xclbin::kernel &k) { return k.get_name().rfind(Node, 0) == 0; });
  auto kernelName = xkernel.get_name();
  device.register_xclbin(xclbin);
  xrt::hw_context context(device, xclbin.get_uuid());
  auto kernel = xrt::kernel(context, kernelName);

  auto bo_instr = xrt::bo(device, instr_v.size() * sizeof(int), XCL_BO_FLAGS_CACHEABLE, kernel.group_id(1));
  auto bo_in = xrt::bo(device, NIN * sizeof(uint16_t), XRT_BO_FLAGS_HOST_ONLY, kernel.group_id(3));
  auto bo_out = xrt::bo(device, NOUT * sizeof(uint16_t), XRT_BO_FLAGS_HOST_ONLY, kernel.group_id(4));

  uint16_t *bufIn = bo_in.map<uint16_t *>();
  uint16_t *bufOut = bo_out.map<uint16_t *>();
  std::memcpy(bufIn, inbuf.data(), NIN * sizeof(uint16_t));
  std::memset(bufOut, 0, NOUT * sizeof(uint16_t));
  std::memcpy(bo_instr.map<void *>(), instr_v.data(), instr_v.size() * sizeof(int));

  bo_instr.sync(XCL_BO_SYNC_BO_TO_DEVICE);
  bo_in.sync(XCL_BO_SYNC_BO_TO_DEVICE);
  bo_out.sync(XCL_BO_SYNC_BO_TO_DEVICE);

  unsigned int opcode = 3;
  auto run = kernel(opcode, bo_instr, instr_v.size(), bo_in, bo_out);
  if (run.wait() != ERT_CMD_STATE_COMPLETED) { std::cout << "Kernel did not complete\\n"; return 1; }
  bo_out.sync(XCL_BO_SYNC_BO_FROM_DEVICE);

  std::ofstream dump("out.txt");
  for (int i = 0; i < NOUT; i++) dump << (uint32_t)bufOut[i] << "\\n";
  std::cout << "add32 lane29 = 0x" << std::hex << bufOut[29] << std::dec << "\\n";
  std::cout << "PASS!\\n";
  return 0;
}
"""


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    for name, content in [
        ("kernel.cc", KERNEL_CC),
        ("aie.mlir", AIE_MLIR),
        ("run.lit", RUN_LIT),
        ("test.cpp", TEST_CPP),
    ]:
        with open(os.path.join(OUT_DIR, name), "w") as f:
            f.write(content)
    print(f"Wrote add32 oracle harness -> {OUT_DIR}")


if __name__ == "__main__":
    main()
