#!/usr/bin/env python3
"""Patch trace-event selection registers in a compiled insts.bin.

Background
----------
mlir-aie lowers `aie.trace` declarative ops through
AIEInlineTraceConfigPass (lib/Dialect/AIEX/Transforms/AIEInlineTraceConfig.cpp)
into a sequence of `aiex.npu.write32` ops in the `runtime_sequence`. Those
become Write32 entries in the compiled `insts.bin`.

For a given tile type, exactly two registers carry the 8-event selection
(one byte per event ID, four events per 32-bit register). This tool
patches the value field of those two writes in an existing insts.bin so
the same xclbin can trace different events without recompilation -- the
stream-switch routing, BD programming, and control wiring generated by
aiecc are invariant across event sets.

Register offsets (AM025 / aie-rt xaiemlgbl_params.h, verified against
compiled output):
  core      : Trace_Event0=0x340E0 Trace_Event1=0x340E4
  memmod    : Trace_Event0=0x140E0 Trace_Event1=0x140E4
  memtile   : Trace_Event0=0x940E0 Trace_Event1=0x940E4
  shim      : Trace_Event0=0x340E0 Trace_Event1=0x340E4

NPU address encoding in insts.bin:
  (col << 25) | (row << 20) | tile_offset

insts.bin format:
  [0..16]   16-byte header (starts with 0x00 0x01 0x03 0x06 ...)
  Then variable-length instructions. Each starts with a 4-byte opcode
  header (opcode_byte, 0, 0, 0) and a size field specific to the opcode.

  Write32   : 24 bytes total -- 4 opcode + 4 zero + 8 reg_off + 4 value + 4 size
  MaskWrite : 28 bytes total -- 4 opcode + 4 zero + 8 reg_off + 4 value + 4 mask + 4 size
  BlockWrite: variable     -- 4 opcode + 4 zero + 4 reg_off + 4 size + payload
  DmaBdWrite: variable     -- opcode >= 128, size field immediately after opcode

Instruction walking here handles the three fixed-size forms (Write32,
MaskWrite) plus custom ops (opcode >= 128) that carry their own size; for
other standard ops we skip by querying a size LUT. The parser intentionally
mirrors xdna-emu's src/npu/parser.rs -- divergence between the two would
produce silent misreads.

Event IDs
---------
Per-tile-type event IDs live in the upstream aie-rt header
  mlir-aie/build/include/xaienginecdo_static/xaiengine/xaie_events_aieml.h
and the declarative ops use the symbolic names in
  mlir-aie/include/aie/Dialect/AIE/IR/AIETraceOps.td
This tool takes integer IDs; the caller (typically trace-sweep.py) is
responsible for mapping names to IDs via the target model.

Usage
-----
  trace-patch-events.py INPUT --col C --row R --tile-type TYPE \
      --events E0,E1,E2,E3,E4,E5,E6,E7 --output PATCHED

  TYPE in {core, memmod, memtile, shim}. Events are 8 integer event IDs
  (0-255 each); missing trailing events default to 0 (TRUE / no-event).
"""
import argparse
import io
import json
import struct
import sys
from pathlib import Path
from typing import List, Tuple


# Per-tile-type (Trace_Event0, Trace_Event1) offsets. See module docstring
# for source references.
_TRACE_EVENT_REGS = {
    "core":    (0x340E0, 0x340E4),
    "memmod":  (0x140E0, 0x140E4),
    "memtile": (0x940E0, 0x940E4),
    "shim":    (0x340E0, 0x340E4),
}

# Trace_Control0 register offsets per tile-type. Layout (from
# xaiemlgbl_params.h):
#   bits [0:1]   MODE          0=event-time, 1=event-PC, 2=instr-exec
#   bits [16:22] TRACE_START   7-bit event id (8-bit on memtile)
#   bits [24:30] TRACE_STOP    7-bit event id (8-bit on memtile)
# mlir-aie's compiled output sets these to BROADCAST_15 / BROADCAST_14
# (122 / 121 on core), gated by host-issued shim control packets. We
# patch them to events that fire from inside the kernel itself, which
# eliminates the broadcast-latency component of entry/exit jitter.
_TRACE_CONTROL0_REGS = {
    "core":    0x340D0,
    "memmod":  0x140D0,
    "memtile": 0x940D0,
    "shim":    0x340D0,
}
# Event field width: memtile has 8-bit slots, others 7-bit.
_EVENT_FIELD_WIDTHS = {
    "core":    7,
    "memmod":  7,
    "memtile": 8,
    "shim":    7,
}

# Fixed-size standard-op byte lengths. Entries not here are either
# variable-length (resolved from an embedded size field) or custom
# (opcode >= 128; size at offset +4). Numbers derived from the cursor-read
# patterns in xdna-emu/src/npu/parser.rs; keep both sides in sync or
# insts.bin walking will silently desynchronise.
_STANDARD_OP_SIZES = {
    0x00: 24,   # Write32    : 8 hdr + 8 reg + 4 value + 4 size
    0x03: 28,   # MaskWrite  : 8 hdr + 8 reg + 4 value + 4 mask + 4 size
    0x04: 28,   # MaskPoll   : same shape as MaskWrite
    0x05: 8,    # Noop       : 4-byte opcode header + 4 bytes zero
    0x06: 16,   # Preempt    : opcode + 4 zero + 8 conservative (parser)
    0x08: 16,   # LoadPdi    : firmware-level; same skip shape as Preempt
    0x09: 16,   # LoadPmStart
    0x0A: 16,   # CreateScratchpad
    0x0B: 16,   # UpdateStateTable
    0x0C: 16,   # UpdateReg
    0x0D: 16,   # UpdateScratch
    0xC8: 16,   # LoadPmEndInternal (= 200)
    # BlockWrite (0x01): size field at +12 carries total length
    # BlockSet (0x02), ConfigShimDmaBd (0x0E/0x0F): not handled here --
    #   the patcher panics so a sweep doesn't silently mis-walk past
    #   them.  Add when a test needs them.
}

_INSTS_HEADER_LEN = 16


def _instruction_length(buf: bytes, off: int) -> int:
    """Return the total byte length of the instruction starting at `off`.

    Handles: Write32, MaskWrite, BlockWrite, and custom ops (opcode >= 128
    where the size field sits at offset+4). Raises ValueError on an
    unrecognised standard opcode so we don't silently misparse.
    """
    if off + 8 > len(buf):
        raise ValueError(f"truncated instruction at {off:#x}")
    opcode = buf[off]
    if opcode >= 128:
        # Custom op: [opcode:u8][pad:u24][size:u32][payload...]
        size = struct.unpack_from("<I", buf, off + 4)[0]
        return max(size, 8)
    if opcode == 0x01:
        # BlockWrite: [hdr:u32=opcode+pad][reg_off:u32][size:u32][payload...]
        size = struct.unpack_from("<I", buf, off + 12)[0]
        return max(size, 16)
    length = _STANDARD_OP_SIZES.get(opcode)
    if length is None:
        raise ValueError(
            f"unknown standard opcode {opcode:#04x} at {off:#x} -- "
            f"add to _STANDARD_OP_SIZES or extend parser"
        )
    return length


def _walk_write32(buf: bytes) -> List[Tuple[int, int, int]]:
    """Iterate insts.bin; yield (record_offset, reg_off, value) for every
    Write32 in stream order. record_offset is the byte offset of the
    instruction start (so value sits at record_offset+16).
    """
    results: List[Tuple[int, int, int]] = []
    off = _INSTS_HEADER_LEN
    while off < len(buf):
        opcode = buf[off]
        length = _instruction_length(buf, off)
        if opcode == 0x00:
            reg_off = struct.unpack_from("<Q", buf, off + 8)[0]
            value = struct.unpack_from("<I", buf, off + 16)[0]
            results.append((off, reg_off, value))
        off += length
    return results


def _npu_address(col: int, row: int, tile_offset: int) -> int:
    """Pack (col, row, offset) into the 32-bit NPU address used in
    insts.bin. See aie-rt / xaiemlgbl_params.h for the bit layout."""
    return (col << 25) | (row << 20) | tile_offset


def _pack_event_slots(events: List[int]) -> Tuple[int, int]:
    """Pack 8 event IDs (each 0-255) into (Trace_Event0, Trace_Event1)
    little-endian-byte values. Slots 0-3 go to Event0, 4-7 go to Event1."""
    padded = list(events) + [0] * (8 - len(events))
    if len(padded) > 8:
        raise ValueError("at most 8 events per tile")
    event0 = padded[0] | (padded[1] << 8) | (padded[2] << 16) | (padded[3] << 24)
    event1 = padded[4] | (padded[5] << 8) | (padded[6] << 16) | (padded[7] << 24)
    return event0 & 0xFFFFFFFF, event1 & 0xFFFFFFFF


def probe_slot_capacity(
    data: bytes, col: int, row: int, tile_type: str,
) -> int:
    """Return the number of event slots this xclbin actually exposes for
    the target tile: 8 if both Trace_Event0 and Trace_Event1 writes are
    present in insts.bin, 4 if only Trace_Event0, 0 if neither.

    Used by the sweep orchestrator to pick a batch size that matches the
    compiled trace config -- some tests come with 3-event trace blocks
    baked into their source MLIR, which compile to a single Trace_Event0
    write and no Trace_Event1; asking the patcher for 8 events there
    would be a lie.
    """
    if tile_type not in _TRACE_EVENT_REGS:
        raise ValueError(f"unknown tile_type {tile_type!r}")
    off_e0, off_e1 = _TRACE_EVENT_REGS[tile_type]
    target_e0 = _npu_address(col, row, off_e0)
    target_e1 = _npu_address(col, row, off_e1)
    has_e0 = has_e1 = False
    for _rec_off, reg_off, _value in _walk_write32(data):
        if reg_off == target_e0:
            has_e0 = True
        elif reg_off == target_e1:
            has_e1 = True
    if has_e0 and has_e1:
        return 8
    if has_e0:
        return 4
    return 0


def patch_events(
    data: bytes,
    col: int,
    row: int,
    tile_type: str,
    events: List[int],
) -> Tuple[bytes, int]:
    """Patch the Trace_Event register(s) for (col, row, tile_type).
    Returns (patched_bytes, num_writes_patched).

    Works whether the xclbin has both Trace_Event0 and Trace_Event1 (full
    8 slots) or just Trace_Event0 (4 slots); if only Trace_Event0 exists
    the caller must have passed <=4 events -- more than that is a bug in
    the caller, not something to silently truncate, because the extra
    events would simply never fire and we'd misattribute "0 fires" to
    them.

    Raises ValueError if neither Trace_Event register is present (xclbin
    compiled without trace on this tile, or for a different tile type)
    or if the caller's event count exceeds the xclbin's slot capacity.
    """
    if tile_type not in _TRACE_EVENT_REGS:
        raise ValueError(f"unknown tile_type {tile_type!r}; want one of "
                         f"{sorted(_TRACE_EVENT_REGS)}")
    capacity = probe_slot_capacity(data, col, row, tile_type)
    if capacity == 0:
        raise ValueError(
            f"no Trace_Event writes found for tile ({col},{row}) "
            f"type={tile_type}. xclbin was compiled without trace on "
            f"this tile or for a different tile type."
        )
    if len(events) > capacity:
        raise ValueError(
            f"xclbin exposes {capacity} trace slots for tile ({col},{row}) "
            f"type={tile_type} but caller supplied {len(events)} events. "
            f"Reduce the batch size (compiled MLIR only wrote "
            f"{'Trace_Event0' if capacity == 4 else 'both Trace_Event regs'})."
        )
    off_e0, off_e1 = _TRACE_EVENT_REGS[tile_type]
    target_e0 = _npu_address(col, row, off_e0)
    target_e1 = _npu_address(col, row, off_e1)
    packed_e0, packed_e1 = _pack_event_slots(events)

    writes = _walk_write32(data)
    buf = bytearray(data)
    patched = 0
    for rec_off, reg_off, _old_value in writes:
        if reg_off == target_e0:
            struct.pack_into("<I", buf, rec_off + 16, packed_e0)
            patched += 1
        elif reg_off == target_e1:
            struct.pack_into("<I", buf, rec_off + 16, packed_e1)
            patched += 1
    if patched not in (1, 2):
        raise ValueError(
            f"expected 1 or 2 Trace_Event writes for tile ({col},{row}) "
            f"type={tile_type}; found {patched}. Internal inconsistency "
            f"with probe_slot_capacity."
        )
    return bytes(buf), patched


def patch_trace_control(
    data: bytes,
    col: int,
    row: int,
    tile_type: str,
    start_event: int | None = None,
    stop_event: int | None = None,
    mode: int | None = None,
) -> Tuple[bytes, int]:
    """Patch the Trace_Control0 register's start_event, stop_event, and/or
    mode fields. Any field set to None is left as the existing value
    (read from the existing Write32 in insts.bin).

    Returns (patched_bytes, n_writes_patched). Raises ValueError if no
    Trace_Control0 write is found for the target tile.
    """
    if tile_type not in _TRACE_CONTROL0_REGS:
        raise ValueError(f"unknown tile_type {tile_type!r}; want one of "
                         f"{sorted(_TRACE_CONTROL0_REGS)}")
    width = _EVENT_FIELD_WIDTHS[tile_type]
    max_event = (1 << width) - 1
    for name, val in [("start_event", start_event), ("stop_event", stop_event)]:
        if val is not None and not (0 <= val <= max_event):
            raise ValueError(f"{name}={val} exceeds {width}-bit field "
                             f"(max {max_event}) for tile_type={tile_type}")
    if mode is not None and not (0 <= mode <= 3):
        raise ValueError(f"mode={mode} exceeds 2-bit field")

    target = _npu_address(col, row, _TRACE_CONTROL0_REGS[tile_type])
    buf = bytearray(data)
    patched = 0
    for rec_off, reg_off, old_value in _walk_write32(data):
        if reg_off != target:
            continue
        new = old_value
        if start_event is not None:
            mask = ((1 << width) - 1) << 16
            new = (new & ~mask) | ((start_event & ((1 << width) - 1)) << 16)
        if stop_event is not None:
            mask = ((1 << width) - 1) << 24
            new = (new & ~mask) | ((stop_event & ((1 << width) - 1)) << 24)
        if mode is not None:
            new = (new & ~0x3) | (mode & 0x3)
        struct.pack_into("<I", buf, rec_off + 16, new & 0xFFFFFFFF)
        patched += 1
    if patched == 0:
        raise ValueError(
            f"no Trace_Control0 write found for tile ({col},{row}) "
            f"type={tile_type}. xclbin compiled without trace on this tile?"
        )
    if patched != 1:
        raise ValueError(
            f"expected exactly 1 Trace_Control0 write for tile ({col},{row}) "
            f"type={tile_type}; found {patched}. insts.bin layout unexpected."
        )
    return bytes(buf), patched


def _parse_events_arg(spec: str) -> List[int]:
    """Parse a comma-separated event list. Each entry is decimal or 0xHEX.
    Trailing empty entries are ignored so callers can write '-events=33,,'
    when they mean 'only slot 0 matters'. Maximum 8.
    """
    parts = [p.strip() for p in spec.split(",")]
    events: List[int] = []
    for p in parts:
        if not p:
            events.append(0)
            continue
        base = 16 if p.lower().startswith("0x") else 10
        events.append(int(p, base))
    # Trim trailing zeros so '33,,,,,,,' and '33' both produce [33].
    while len(events) > 0 and events[-1] == 0:
        events.pop()
    if len(events) > 8:
        raise ValueError("max 8 events per tile")
    return events


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__.strip().splitlines()[0],
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("input", help="path to compiled insts.bin")
    ap.add_argument("--multi-tile", type=Path, default=None,
                    help="JSON file containing a list of patch specs: "
                         "[{col, row, tile_type, events?, start_event?, "
                         "stop_event?, mode?}, ...]. Applies all patches in "
                         "one process invocation (avoids per-tile subprocess "
                         "overhead in trace-sweep). Mutually exclusive with "
                         "--col/--row/--tile-type.")
    ap.add_argument("--col", type=int, default=None,
                    help="absolute tile column (single-tile mode)")
    ap.add_argument("--row", type=int, default=None,
                    help="absolute tile row (single-tile mode)")
    ap.add_argument("--tile-type", default=None,
                    choices=sorted(_TRACE_EVENT_REGS),
                    help="tile-type event-register set to patch (single-tile mode)")
    ap.add_argument("--events", default=None,
                    help="comma-separated event IDs (decimal or 0xHEX), "
                         "up to 8; missing trailing slots default to 0. "
                         "Omit to leave Trace_Event0/1 untouched (use with "
                         "--start-event/--stop-event for control-only patching)")
    ap.add_argument("--start-event", type=lambda s: int(s, 0), default=None,
                    help="override Trace_Control0 TRACE_START event id "
                         "(default: leave existing value untouched). mlir-aie "
                         "compiles to BROADCAST_15 (122 on core); replacing "
                         "with a kernel-internal event eliminates broadcast "
                         "latency from entry/exit jitter")
    ap.add_argument("--stop-event", type=lambda s: int(s, 0), default=None,
                    help="override Trace_Control0 TRACE_STOP event id "
                         "(default: leave existing value untouched). mlir-aie "
                         "compiles to BROADCAST_14 (121 on core)")
    ap.add_argument("--mode", type=lambda s: int(s, 0), default=None,
                    help="override Trace_Control0 MODE field "
                         "(0=event-time, 1=event-PC, 2=instr-exec)")
    ap.add_argument("--output", required=True, help="path to write patched insts.bin")
    args = ap.parse_args()

    # --multi-tile: batch mode -- one invocation, N tile patches.
    if args.multi_tile is not None:
        if any(x is not None for x in [args.col, args.row, args.tile_type]):
            ap.error("--multi-tile is mutually exclusive with --col/--row/--tile-type")
        spec_list = json.loads(args.multi_tile.read_text())
        data = Path(args.input).read_bytes()
        summaries: list[str] = []
        try:
            for s in spec_list:
                col = int(s["col"]); row = int(s["row"])
                tile_type = s["tile_type"]
                if "events" in s:
                    events = _parse_events_arg(
                        ",".join(str(e) for e in s["events"])
                    )
                    data, n = patch_events(data, col, row, tile_type, events)
                    summaries.append(
                        f"({col},{row},{tile_type}) events={events} ({n})"
                    )
                if any(k in s for k in ("start_event", "stop_event", "mode")):
                    data, n = patch_trace_control(
                        data, col, row, tile_type,
                        start_event=s.get("start_event"),
                        stop_event=s.get("stop_event"),
                        mode=s.get("mode"),
                    )
                    summaries.append(f"({col},{row},{tile_type}) control ({n})")
        except ValueError as e:
            print(f"trace-patch-events: {e}", file=sys.stderr)
            return 2
        Path(args.output).write_bytes(data)
        print("trace-patch-events multi-tile: " + (
            "; ".join(summaries) if summaries else "(no patches)"
        ))
        return 0

    # Single-tile mode: validate that required args are present.
    if args.col is None or args.row is None or args.tile_type is None:
        ap.error("single-tile mode requires --col, --row, and --tile-type "
                 "(or use --multi-tile for batch patching)")

    if (args.events is None and args.start_event is None
            and args.stop_event is None and args.mode is None):
        ap.error("nothing to patch: pass --events and/or "
                 "--start-event/--stop-event/--mode")

    data = Path(args.input).read_bytes()
    summary_parts: list[str] = []
    try:
        if args.events is not None:
            events = _parse_events_arg(args.events)
            data, n = patch_events(
                data, args.col, args.row, args.tile_type, events,
            )
            summary_parts.append(f"events={events} ({n} write32 patched)")
        if (args.start_event is not None or args.stop_event is not None
                or args.mode is not None):
            data, n = patch_trace_control(
                data, args.col, args.row, args.tile_type,
                start_event=args.start_event,
                stop_event=args.stop_event,
                mode=args.mode,
            )
            ctl_bits = []
            if args.start_event is not None:
                ctl_bits.append(f"start={args.start_event}")
            if args.stop_event is not None:
                ctl_bits.append(f"stop={args.stop_event}")
            if args.mode is not None:
                ctl_bits.append(f"mode={args.mode}")
            summary_parts.append(f"control[{','.join(ctl_bits)}] ({n} patched)")
    except ValueError as e:
        print(f"trace-patch-events: {e}", file=sys.stderr)
        return 2

    Path(args.output).write_bytes(data)
    print(f"trace-patch-events: tile ({args.col},{args.row}) "
          f"type={args.tile_type} -> {args.output} :: "
          + "; ".join(summary_parts))
    return 0


if __name__ == "__main__":
    sys.exit(main())
