#!/usr/bin/env python3
"""Patch trace-event selection registers in a compiled insts.bin.

Background
----------
mlir-aie lowers `aie.trace` declarative ops through
AIEInlineTraceConfigPass (lib/Dialect/AIEX/Transforms/AIEInlineTraceConfig.cpp)
into a sequence of `aiex.npu.write32` ops in the `runtime_sequence`. Those
become Write32 entries in the compiled `insts.bin`.

For a given tile type, exactly two registers carry the 8-event selection
(one byte per event ID, four events per 32-bit register). This tool
patches the value field of those two writes in an existing insts.bin so
the same xclbin can trace different events without recompilation -- the
stream-switch routing, BD programming, and control wiring generated by
aiecc are invariant across event sets.

Register offsets (AM025 / aie-rt xaiemlgbl_params.h, verified against
compiled output):
  core      : Trace_Event0=0x340E0 Trace_Event1=0x340E4
  memmod    : Trace_Event0=0x140E0 Trace_Event1=0x140E4
  memtile   : Trace_Event0=0x940E0 Trace_Event1=0x940E4
  shim      : Trace_Event0=0x340E0 Trace_Event1=0x340E4

NPU address encoding in insts.bin:
  (col << 25) | (row << 20) | tile_offset

insts.bin format:
  [0..16]   16-byte header (starts with 0x00 0x01 0x03 0x06 ...)
  Then variable-length instructions. Each starts with a 4-byte opcode
  header (opcode_byte, 0, 0, 0) and a size field specific to the opcode.

  Write32   : 24 bytes total -- 4 opcode + 4 zero + 8 reg_off + 4 value + 4 size
  MaskWrite : 28 bytes total -- 4 opcode + 4 zero + 8 reg_off + 4 value + 4 mask + 4 size
  BlockWrite: variable     -- 4 opcode + 4 zero + 4 reg_off + 4 size + payload
  DmaBdWrite: variable     -- opcode >= 128, size field immediately after opcode

Instruction walking here handles the three fixed-size forms (Write32,
MaskWrite) plus custom ops (opcode >= 128) that carry their own size; for
other standard ops we skip by querying a size LUT. The parser intentionally
mirrors xdna-emu's src/npu/parser.rs -- divergence between the two would
produce silent misreads.

Event IDs
---------
Per-tile-type event IDs live in the upstream aie-rt header
  mlir-aie/build/include/xaienginecdo_static/xaiengine/xaie_events_aieml.h
and the declarative ops use the symbolic names in
  mlir-aie/include/aie/Dialect/AIE/IR/AIETraceOps.td
This tool takes integer IDs; the caller (typically trace-sweep.py) is
responsible for mapping names to IDs via the target model.

Usage
-----
  trace-patch-events.py INPUT --col C --row R --tile-type TYPE \
      --events E0,E1,E2,E3,E4,E5,E6,E7 --output PATCHED

  TYPE in {core, memmod, memtile, shim}. Events are 8 integer event IDs
  (0-255 each); missing trailing events default to 0 (TRUE / no-event).
"""
import argparse
import io
import struct
import sys
from pathlib import Path
from typing import List, Tuple


# Per-tile-type (Trace_Event0, Trace_Event1) offsets. See module docstring
# for source references.
_TRACE_EVENT_REGS = {
    "core":    (0x340E0, 0x340E4),
    "memmod":  (0x140E0, 0x140E4),
    "memtile": (0x940E0, 0x940E4),
    "shim":    (0x340E0, 0x340E4),
}

# Fixed-size standard-op byte lengths. Entries not here are either
# variable-length (resolved from an embedded size field) or custom
# (opcode >= 128; size at offset +4). Numbers derived from the cursor-read
# patterns in xdna-emu/src/npu/parser.rs; keep both sides in sync or
# insts.bin walking will silently desynchronise.
_STANDARD_OP_SIZES = {
    0x00: 24,   # Write32    : 8 hdr + 8 reg + 4 value + 4 size
    0x03: 28,   # MaskWrite  : 8 hdr + 8 reg + 4 value + 4 mask + 4 size
    0x04: 28,   # MaskPoll   : same shape as MaskWrite
    0x05: 8,    # Noop       : 4-byte opcode header + 4 bytes zero
    0x06: 16,   # Preempt    : opcode + 4 zero + 8 conservative (parser)
    0x08: 16,   # LoadPdi    : firmware-level; same skip shape as Preempt
    0x09: 16,   # LoadPmStart
    0x0A: 16,   # CreateScratchpad
    0x0B: 16,   # UpdateStateTable
    0x0C: 16,   # UpdateReg
    0x0D: 16,   # UpdateScratch
    0xC8: 16,   # LoadPmEndInternal (= 200)
    # BlockWrite (0x01): size field at +12 carries total length
    # BlockSet (0x02), ConfigShimDmaBd (0x0E/0x0F): not handled here --
    #   the patcher panics so a sweep doesn't silently mis-walk past
    #   them.  Add when a test needs them.
}

_INSTS_HEADER_LEN = 16


def _instruction_length(buf: bytes, off: int) -> int:
    """Return the total byte length of the instruction starting at `off`.

    Handles: Write32, MaskWrite, BlockWrite, and custom ops (opcode >= 128
    where the size field sits at offset+4). Raises ValueError on an
    unrecognised standard opcode so we don't silently misparse.
    """
    if off + 8 > len(buf):
        raise ValueError(f"truncated instruction at {off:#x}")
    opcode = buf[off]
    if opcode >= 128:
        # Custom op: [opcode:u8][pad:u24][size:u32][payload...]
        size = struct.unpack_from("<I", buf, off + 4)[0]
        return max(size, 8)
    if opcode == 0x01:
        # BlockWrite: [hdr:u32=opcode+pad][reg_off:u32][size:u32][payload...]
        size = struct.unpack_from("<I", buf, off + 12)[0]
        return max(size, 16)
    length = _STANDARD_OP_SIZES.get(opcode)
    if length is None:
        raise ValueError(
            f"unknown standard opcode {opcode:#04x} at {off:#x} -- "
            f"add to _STANDARD_OP_SIZES or extend parser"
        )
    return length


def _walk_write32(buf: bytes) -> List[Tuple[int, int, int]]:
    """Iterate insts.bin; yield (record_offset, reg_off, value) for every
    Write32 in stream order. record_offset is the byte offset of the
    instruction start (so value sits at record_offset+16).
    """
    results: List[Tuple[int, int, int]] = []
    off = _INSTS_HEADER_LEN
    while off < len(buf):
        opcode = buf[off]
        length = _instruction_length(buf, off)
        if opcode == 0x00:
            reg_off = struct.unpack_from("<Q", buf, off + 8)[0]
            value = struct.unpack_from("<I", buf, off + 16)[0]
            results.append((off, reg_off, value))
        off += length
    return results


def _npu_address(col: int, row: int, tile_offset: int) -> int:
    """Pack (col, row, offset) into the 32-bit NPU address used in
    insts.bin. See aie-rt / xaiemlgbl_params.h for the bit layout."""
    return (col << 25) | (row << 20) | tile_offset


def _pack_event_slots(events: List[int]) -> Tuple[int, int]:
    """Pack 8 event IDs (each 0-255) into (Trace_Event0, Trace_Event1)
    little-endian-byte values. Slots 0-3 go to Event0, 4-7 go to Event1."""
    padded = list(events) + [0] * (8 - len(events))
    if len(padded) > 8:
        raise ValueError("at most 8 events per tile")
    event0 = padded[0] | (padded[1] << 8) | (padded[2] << 16) | (padded[3] << 24)
    event1 = padded[4] | (padded[5] << 8) | (padded[6] << 16) | (padded[7] << 24)
    return event0 & 0xFFFFFFFF, event1 & 0xFFFFFFFF


def patch_events(
    data: bytes,
    col: int,
    row: int,
    tile_type: str,
    events: List[int],
) -> Tuple[bytes, int]:
    """Patch the two Trace_Event registers for (col, row, tile_type) to the
    packed event IDs. Returns (patched_bytes, num_writes_patched).

    Raises ValueError if the target writes aren't found -- the xclbin was
    either compiled without trace on that tile, or with a different tile
    type.  Either way, patching silently would be a bug: the sweep would
    run with stale events and we'd attribute the result to the wrong
    config.
    """
    if tile_type not in _TRACE_EVENT_REGS:
        raise ValueError(f"unknown tile_type {tile_type!r}; want one of "
                         f"{sorted(_TRACE_EVENT_REGS)}")
    off_e0, off_e1 = _TRACE_EVENT_REGS[tile_type]
    target_e0 = _npu_address(col, row, off_e0)
    target_e1 = _npu_address(col, row, off_e1)

    packed_e0, packed_e1 = _pack_event_slots(events)

    writes = _walk_write32(data)
    buf = bytearray(data)
    patched = 0
    for rec_off, reg_off, _old_value in writes:
        if reg_off == target_e0:
            struct.pack_into("<I", buf, rec_off + 16, packed_e0)
            patched += 1
        elif reg_off == target_e1:
            struct.pack_into("<I", buf, rec_off + 16, packed_e1)
            patched += 1
    if patched != 2:
        raise ValueError(
            f"expected 2 Trace_Event writes for tile ({col},{row}) "
            f"type={tile_type}; found {patched}. xclbin may have been "
            f"compiled without trace on this tile or for a different type."
        )
    return bytes(buf), patched


def _parse_events_arg(spec: str) -> List[int]:
    """Parse a comma-separated event list. Each entry is decimal or 0xHEX.
    Trailing empty entries are ignored so callers can write '-events=33,,'
    when they mean 'only slot 0 matters'. Maximum 8.
    """
    parts = [p.strip() for p in spec.split(",")]
    events: List[int] = []
    for p in parts:
        if not p:
            events.append(0)
            continue
        base = 16 if p.lower().startswith("0x") else 10
        events.append(int(p, base))
    # Trim trailing zeros so '33,,,,,,,' and '33' both produce [33].
    while len(events) > 0 and events[-1] == 0:
        events.pop()
    if len(events) > 8:
        raise ValueError("max 8 events per tile")
    return events


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__.strip().splitlines()[0],
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("input", help="path to compiled insts.bin")
    ap.add_argument("--col", type=int, required=True, help="absolute tile column")
    ap.add_argument("--row", type=int, required=True, help="absolute tile row")
    ap.add_argument("--tile-type", required=True,
                    choices=sorted(_TRACE_EVENT_REGS),
                    help="tile-type event-register set to patch")
    ap.add_argument("--events", required=True,
                    help="comma-separated event IDs (decimal or 0xHEX), "
                         "up to 8; missing trailing slots default to 0")
    ap.add_argument("--output", required=True, help="path to write patched insts.bin")
    args = ap.parse_args()

    data = Path(args.input).read_bytes()
    try:
        events = _parse_events_arg(args.events)
        patched_bytes, n = patch_events(
            data, args.col, args.row, args.tile_type, events,
        )
    except ValueError as e:
        print(f"trace-patch-events: {e}", file=sys.stderr)
        return 2

    Path(args.output).write_bytes(patched_bytes)
    print(f"trace-patch-events: patched {n} Write32 ops in {args.output} "
          f"(tile ({args.col},{args.row}) type={args.tile_type} events={events})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
