//! xdna-emu library
//!
//! Core emulation logic for AMD XDNA NPUs.
//!
//! # Module Organization
//!
//! - [`config`]: Configuration management (paths, settings)
//! - [`parser`]: Binary format parsers (xclbin, CDO, ELF)
//! - [`device`]: Hardware state model (tiles, registers, memory)
//! - [`interpreter`]: Accurate AIE2 interpreter
//! - [`tablegen`]: TableGen parser for instruction definitions
//! - [`npu`]: Host-to-NPU instruction execution
//! - [`visual`]: Trace comparison visualizer (egui-based)
//! - [`integration`]: External tool integration
//! - [`testing`]: Test harness for XCLBIN binary compatibility
//! - `ffi`: C-compatible FFI (separate crate: `xdna-emu-ffi`)
//! - [`fuzzer`]: Differential logic fuzzer for emulator validation
//! - [`aiesim`]: aiesimulator subprocess harness for VCD cross-validation

// Core emulation engine (always available)
pub mod config;
pub mod parser;
pub mod device;
pub mod interpreter;
pub mod tablegen;
pub mod npu;
pub mod trace;
pub mod aiesim;
pub mod debug;

// GUI (requires eframe/egui)
#[cfg(feature = "gui")]
pub mod visual;

// VCD deep extraction (requires wellen)
#[cfg(feature = "analysis")]
pub mod vcd;

// Test harness, external tool wrappers, fuzzer (requires crossterm)
#[cfg(feature = "tooling")]
pub mod build_progress;
#[cfg(feature = "tooling")]
pub mod testing;
#[cfg(feature = "tooling")]
pub mod integration;
#[cfg(feature = "tooling")]
pub mod fuzzer;

/// Compile-time architecture constants generated from the validated ArchModel.
///
/// This module is generated by build.rs from the architecture specification
/// (device model + register database, cross-validated via Confirmed<T>).
/// It replaces scattered hardcoded constants with spec-derived values.
///
/// Includes:
/// - Array topology and per-tile-type resource counts (gen_arch.rs)
/// - Per-tile-type subsystem address ranges (gen_subsystems.rs)
/// - Stream switch port type arrays (gen_stream_ports.rs)
/// - Stream switch port ranges and config bits (gen_stream_ranges.rs)
pub mod arch {
    include!(concat!(env!("OUT_DIR"), "/gen_arch.rs"));

    /// Stream switch port type identifier.
    ///
    /// These are our encoding convention (not hardware register values).
    /// Each port index in the port arrays maps to one of these types.
    pub mod port_type {
        pub const CORE: u8 = 0;
        pub const FIFO: u8 = 1;
        pub const TRACE: u8 = 2;
        /// Tile control port (configuration/debug).
        /// Per AM025: compute=port 3, memtile=port 6, shim=port 0.
        pub const CTRL: u8 = 3;
        pub const NORTH_BASE: u8 = 10;
        pub const SOUTH_BASE: u8 = 20;
        pub const EAST_BASE: u8 = 30;
        pub const WEST_BASE: u8 = 40;
        pub const DMA_BASE: u8 = 50;

        pub const fn north(n: u8) -> u8 { NORTH_BASE + n }
        pub const fn south(n: u8) -> u8 { SOUTH_BASE + n }
        pub const fn east(n: u8) -> u8 { EAST_BASE + n }
        pub const fn west(n: u8) -> u8 { WEST_BASE + n }
        pub const fn dma(n: u8) -> u8 { DMA_BASE + n }
    }

    /// Subsystem address ranges per tile type (generated from ArchModel).
    pub mod subsystem {
        include!(concat!(env!("OUT_DIR"), "/gen_subsystems.rs"));
    }

    // Port type arrays generated from AM025 Stream_Switch_*_Config registers.
    include!(concat!(env!("OUT_DIR"), "/gen_stream_ports.rs"));

    /// Stream switch port ranges and config bits (derived from port arrays).
    pub mod stream_switch {
        include!(concat!(env!("OUT_DIR"), "/gen_stream_ranges.rs"));
    }
}
