//! xdna-emu library
//!
//! Core emulation logic for AMD XDNA NPUs.
//!
//! # Module Organization
//!
//! - [`config`]: Configuration management (paths, settings)
//! - [`parser`]: Binary format parsers (xclbin, CDO, ELF)
//! - [`device`]: Hardware state model (tiles, registers, memory)
//! - [`interpreter`]: Accurate AIE2 interpreter
//! - [`tablegen`]: TableGen parser for instruction definitions
//! - [`npu`]: Host-to-NPU instruction execution
//! - [`visual`]: GUI visualization (egui-based)
//! - [`integration`]: External tool integration
//! - [`testing`]: Test harness for XCLBIN binary compatibility
//! - [`ffi`]: C-compatible Foreign Function Interface
//! - [`fuzzer`]: Differential logic fuzzer for emulator validation

pub mod config;
pub mod parser;
pub mod device;
pub mod interpreter;
pub mod tablegen;
pub mod npu;
pub mod trace;
pub mod visual;
pub mod integration;
pub mod testing;
pub mod ffi;
pub mod build_progress;
pub mod fuzzer;
pub mod archspec;

/// Compile-time architecture constants generated from the validated ArchModel.
///
/// This module is generated by build.rs from the architecture specification
/// (device model + register database, cross-validated via Confirmed<T>).
/// It replaces scattered hardcoded constants with spec-derived values.
pub mod arch {
    include!(concat!(env!("OUT_DIR"), "/gen_arch.rs"));
}
