//! AIE2 ISA decoder tables extracted at build time from llvm-aie TableGen.
//!
//! The full decoder table data (`gen_tablegen.rs`) is generated by
//! `build_helpers::codegen::generate_tablegen_file` and written to
//! `$OUT_DIR/gen_tablegen.rs`. However, the generated code references
//! runtime types (`InstrEncoding`, `TblgenOutput`, etc.) that currently
//! live in xdna-emu's `src/tablegen/` module, not in this crate.
//!
//! Until those types are migrated to xdna-archspec (a future task), this
//! module is a placeholder. The actual ISA tables are included directly by
//! xdna-emu's `src/tablegen/mod.rs` via a `mod generated { include!() }`
//! block using xdna-emu's own OUT_DIR.
//!
//! When the type migration is complete, this file will become:
//! ```ignore
//! include!(concat!(env!("OUT_DIR"), "/gen_tablegen.rs"));
//! ```
